//------------------------------------------------------------------------------
//Create A Hero Weapon Upgrade definitions
//------------------------------------------------------------------------------

//------------------------------------------------------------------------------
// Special Create A Hero System upgrades.
Upgrade Upgrade_CreateAHeroMapMode
	Type = OBJECT
End

Upgrade	Upgrade_CreateAHeroGameMode
	Type = OBJECT
End

Upgrade	Upgrade_AllowBuildCreateAHero
	Type = PLAYER
End

//------------------------------------------------------------------------------
// Create a Hero weapon upgrades
Upgrade Upgrade_CHWRemoveAll	//' This upgrade removes all weapons
	Type	= OBJECT
End

Upgrade Upgrade_CHW01	//' Dwarf Axe_01
	Type	= OBJECT
	GroupName = CreateAHero_Weapon
End

Upgrade Upgrade_CHW02	//' Currently unused
	Type	= OBJECT
	GroupName = CreateAHero_Weapon
End

Upgrade Upgrade_CHW03	//' Gurthang sword
	Type	= OBJECT
	GroupName = CreateAHero_Weapon
End

Upgrade Upgrade_CHW04	//'Westron (Sword) Weapon upgrade.
	Type	= OBJECT
	GroupName = CreateAHero_Weapon
End

Upgrade Upgrade_CHW05	//'TrollBane (Sword) Weapon upgrade.
	Type	= OBJECT
	GroupName = CreateAHero_Weapon
End

Upgrade Upgrade_CHW06	//'FireBrand (Sword) Weapon upgrade.
	Type	= OBJECT
	GroupName = CreateAHero_Weapon
End

Upgrade Upgrade_CHW07	//'Wizard Staff 1 Weapon upgrade.
	Type	= OBJECT
	GroupName = CreateAHero_Weapon
End

Upgrade Upgrade_CHW08	//'Bow Weapon upgrade.
	Type	= OBJECT
	GroupName = CreateAHero_Weapon
End

Upgrade Upgrade_CHW09	//'Wizard Staff 2 Weapon upgrade.
	Type	= OBJECT
	GroupName = CreateAHero_Weapon
End

Upgrade Upgrade_CHW10	//'Wizard Staff 3 Weapon upgrade.
	Type	= OBJECT
	GroupName = CreateAHero_Weapon
End

Upgrade Upgrade_CHW11	//'Wizard Staff 4 Weapon upgrade.
	Type	= OBJECT
	GroupName = CreateAHero_Weapon
End

Upgrade Upgrade_CHW12
	Type	= OBJECT
	GroupName = CreateAHero_Weapon
End

Upgrade Upgrade_CHW13
	Type	= OBJECT
	GroupName = CreateAHero_Weapon
End

Upgrade Upgrade_CHW14
	Type	= OBJECT
	GroupName = CreateAHero_Weapon
End

Upgrade Upgrade_CHW15
	Type	= OBJECT
	GroupName = CreateAHero_Weapon
End

Upgrade Upgrade_CHW16
	Type	= OBJECT
	GroupName = CreateAHero_Weapon
End

Upgrade Upgrade_CHW17
	Type	= OBJECT
	GroupName = CreateAHero_Weapon
End

Upgrade Upgrade_CHW18
	Type	= OBJECT
	GroupName = CreateAHero_Weapon
End

Upgrade Upgrade_CHW19
	Type	= OBJECT
	GroupName = CreateAHero_Weapon
End

Upgrade Upgrade_CHW20
	Type	= OBJECT
	GroupName = CreateAHero_Weapon
End

Upgrade Upgrade_CHW21	//' CM Club
	Type	= OBJECT
	GroupName = CreateAHero_Weapon
End

Upgrade Upgrade_CHW22	//' CM Hammer
	Type	= OBJECT
	GroupName = CreateAHero_Weapon
End

Upgrade Upgrade_CHW23	//' CM Sword 03
	Type	= OBJECT
	GroupName = CreateAHero_Weapon
End

Upgrade Upgrade_CHW24	//' CM Sword 04
	Type	= OBJECT
	GroupName = CreateAHero_Weapon
End

Upgrade Upgrade_CHW25 	//Corrupted Man Sword 1
	Type	= OBJECT
	GroupName = CreateAHero_Weapon
End

Upgrade Upgrade_CHW26	//Corrupted Man Sword 2
	Type	= OBJECT
	GroupName = CreateAHero_Weapon
End

Upgrade Upgrade_CHW27	// Hero of the West Axe
	Type	= OBJECT
	GroupName = CreateAHero_Weapon
End

Upgrade Upgrade_CHW28	// Hero of the West Sword
	Type	= OBJECT
	GroupName = CreateAHero_Weapon
End

Upgrade Upgrade_CHW29	// Troll Spiked Club
	Type	= OBJECT
	GroupName = CreateAHero_Weapon
End

Upgrade Upgrade_CHW30	// Troll Metal Hammer
	Type	= OBJECT
	GroupName = CreateAHero_Weapon
End

Upgrade Upgrade_CHW31	// Dwarf Hammer
	Type	= OBJECT
	GroupName = CreateAHero_Weapon
End

Upgrade Upgrade_CHW32  // Dwarf Axe 02
	Type	= OBJECT
	GroupName = CreateAHero_Weapon
End

//------------------------------------------------------------------------------
//Create A Hero Upgrade definitions
Upgrade Upgrade_CreateAHeroBladeMaster
	Type = OBJECT
End

Upgrade Upgrade_CreateAHeroAthelas
	Type = OBJECT
End

Upgrade Upgrade_CreateAHeroElendil
	Type = OBJECT
End

Upgrade Upgrade_CreateAHeroShieldMaiden
	Type = OBJECT
End

Upgrade Upgrade_CreateAHeroTeleportToCaster
	Type = OBJECT
End
						   
Upgrade Upgrade_CreateAHeroStoreObjectsForLevel2Teleport
	Type = OBJECT
End

Upgrade Upgrade_CreateAHeroStoreObjectsForLevel3Teleport
	Type = OBJECT
End

Upgrade Upgrade_CreateAHeroTeleportAnyUnits
	Type = OBJECT
End

Upgrade Upgrade_CreateAHeroKingsFavor
	Type = OBJECT
End

Upgrade Upgrade_CreateAHeroConvert_Level1
	Type = OBJECT
End

Upgrade Upgrade_CreateAHeroConvert_Level2
	Type = OBJECT
End

Upgrade Upgrade_CreateAHeroCurse_Level1
	Type = OBJECT
End

Upgrade Upgrade_CreateAHeroCurse_Level2
	Type = OBJECT
End

Upgrade Upgrade_CreateAHeroCurse_Level3
	Type = OBJECT
End

Upgrade Upgrade_CreateAHeroToggleWeapon
	Type = OBJECT
End

Upgrade Upgrade_CreateAHeroToggleWeapon_Level2
	Type = OBJECT
End

Upgrade Upgrade_CreateAHeroForcePush_Level1
	Type = OBJECT
End

Upgrade Upgrade_CreateAHeroForcePush_Level2
	Type = OBJECT
End

Upgrade Upgrade_CreateAHeroForcePush_Level3
	Type = OBJECT
End

Upgrade Upgrade_CreateAHeroBlink
	Type = OBJECT
End

Upgrade Upgrade_CreateAHeroFireBall
	Type = OBJECT
End

Upgrade Upgrade_CreateAHeroFireBall_Level2
	Type = OBJECT
End

Upgrade Upgrade_CreateAHeroFireBall_Level3
	Type = OBJECT
End

Upgrade Upgrade_CreateAHeroLightBlast_Level1
	Type = OBJECT
End

Upgrade Upgrade_CreateAHeroLightBlast_Level2
	Type = OBJECT
End

Upgrade Upgrade_CreateAHeroLightBlast_Level3
	Type = OBJECT
End

Upgrade Upgrade_CreateAHeroBallLightning_Level1
	Type = OBJECT
End

Upgrade Upgrade_CreateAHeroBallLightning_Level2
	Type = OBJECT
End

Upgrade Upgrade_CreateAHeroBallLightning_Level3
	Type = OBJECT
End

Upgrade Upgrade_CreateAHeroWordOfDoom_Level1
	Type = OBJECT
End

Upgrade Upgrade_CreateAHeroWordOfDoom_Level2
	Type = OBJECT
End

Upgrade Upgrade_CreateAHeroInvulnerability_Level1
	Type = OBJECT
End

Upgrade Upgrade_CreateAHeroInvulnerability_Level2
	Type = OBJECT
End

Upgrade Upgrade_CreateAHeroInvulnerability_Level3
	Type = OBJECT
End

Upgrade Upgrade_CreateAHeroCrippleStrikeRanged_Level1
	Type = OBJECT
End

Upgrade Upgrade_CreateAHeroCrippleStrikeRanged_Level2
	Type = OBJECT
End

Upgrade Upgrade_CreateAHeroCrippleStrikeRanged_Level3
	Type = OBJECT
End

Upgrade Upgrade_CreateAHeroCrippleStrikeRanged_Level4
	Type = OBJECT
End


Upgrade Upgrade_CreateAHeroCrippleStrikeMelee_Level1
	Type = OBJECT
End

Upgrade Upgrade_CreateAHeroCrippleStrikeMelee_Level2
	Type = OBJECT
End

Upgrade Upgrade_CreateAHeroCrippleStrikeMelee_Level3
	Type = OBJECT
End

Upgrade Upgrade_CreateAHeroCrippleStrikeMelee_Level4
	Type = OBJECT
End

Upgrade Upgrade_CreateAHeroHotWSummonAllies_Level1
	Type = OBJECT
End

Upgrade Upgrade_CreateAHeroHotWSummonAllies_Level2
	Type = OBJECT
End

Upgrade Upgrade_CreateAHeroHotWSummonAllies_Level3
	Type = OBJECT
End

Upgrade Upgrade_CreateAHeroHotWSummonAllies_Level4
	Type = OBJECT
End

Upgrade Upgrade_CreateAHeroSoSSummonAllies_Level1
	Type = OBJECT
End

Upgrade Upgrade_CreateAHeroSoSSummonAllies_Level2
	Type = OBJECT
End

Upgrade Upgrade_CreateAHeroSoSSummonAllies_Level3
	Type = OBJECT
End

Upgrade Upgrade_CreateAHeroSoSSummonAllies_Level4
	Type = OBJECT
End

Upgrade Upgrade_CreateAHeroClearGarrisoned
	Type = OBJECT
End

Upgrade Upgrade_CreateAHeroToggleMounted
	Type = OBJECT
End

Upgrade Upgrade_CreateAHeroCreateAHeroTrainAllies_Level_1
	Type = OBJECT
End

Upgrade Upgrade_CreateAHeroCreateAHeroTrainAllies_Level_2
	Type = OBJECT
End

Upgrade Upgrade_CreateAHeroCreateAHeroTrainAllies_Level_3
	Type = OBJECT
End

Upgrade Upgrade_CreateAHeroLeadership
	Type = OBJECT
End

Upgrade Upgrade_CreateAHeroWordOfPoultry_Level1
	Type = OBJECT
End

Upgrade Upgrade_CreateAHeroWordOfPoultry_Level2
	Type = OBJECT
End

Upgrade Upgrade_CreateAHeroShieldCrush_Level1
	Type = OBJECT
End

Upgrade Upgrade_CreateAHeroShieldCrush_Level3
	Type = OBJECT
End

Upgrade Upgrade_CreateAHeroHotWConquer
	Type = OBJECT
End

Upgrade Upgrade_CreateAHeroCMConquer
	Type = OBJECT
End

Upgrade Upgrade_CreateAHeroStarlight
	Type = OBJECT
End

Upgrade Upgrade_CreateAHeroThrowSpear_Level1
	Type				= OBJECT
End

Upgrade Upgrade_CreateAHeroThrowSpear_Level2
	Type				= OBJECT
End

Upgrade Upgrade_CreateAHeroThrowSpear_Level3
	Type				= OBJECT
End

Upgrade Upgrade_CreateAHeroHeroicCharge
	Type				= OBJECT
End

Upgrade Upgrade_CreateAHeroOilFire_Level1
	Type				= OBJECT
End

Upgrade Upgrade_CreateAHeroOilFire_Level2
	Type				= OBJECT
End

Upgrade Upgrade_CreateAHeroOilFire_Level3
	Type				= OBJECT
End

Upgrade Upgrade_CreateAHeroInspireFear_Level1
	Type				= OBJECT
End

Upgrade Upgrade_CreateAHeroInspireFear_Level2
	Type				= OBJECT
End

//Upgrade Upgrade_CreateAHeroInspireFear_Level3
//	Type				= OBJECT
//End

Upgrade Upgrade_CreateAHeroHowlOfRage_Level1
	Type				= OBJECT
End

Upgrade Upgrade_CreateAHeroHowlOfRage_Level2
	Type				= OBJECT
End

Upgrade Upgrade_CreateAHeroHowlOfRage_Level3
	Type				= OBJECT
End

Upgrade Upgrade_CreateAHeroInfernal_Level1
	Type = OBJECT
End

Upgrade Upgrade_CreateAHeroInfernal_Level2
	Type = OBJECT
End

Upgrade Upgrade_CreateAHeroBerserkerRage_Level1
	Type = OBJECT
End

Upgrade Upgrade_CreateAHeroBerserkerRage_Level2
	Type = OBJECT
End

Upgrade Upgrade_CreateAHeroBerserkerRage_Level3
	Type = OBJECT
End

Upgrade Upgrade_CreateAHeroBerserkerRage_Level4
	Type = OBJECT
End

Upgrade Upgrade_CreateAHeroFireBomb_Level1
	Type = OBJECT
End

Upgrade Upgrade_CreateAHeroFireBomb_Level2
	Type = OBJECT
End

Upgrade Upgrade_CreateAHeroFireBomb_Level3
	Type = OBJECT
End

Upgrade Upgrade_CreateAHeroFireBomb_Level4
	Type = OBJECT
End

Upgrade Upgrade_CreateAHeroPoisonAttack_Level1
	Type = OBJECT
End

Upgrade Upgrade_CreateAHeroPoisonAttack_Level2
	Type = OBJECT
End

Upgrade Upgrade_CreateAHeroPoisonAttack_Level3
	Type = OBJECT
End

Upgrade Upgrade_CreateAHeroPoisonAttack_Level4
	Type = OBJECT
End

Upgrade Upgrade_CreateAHeroUntamedAllegiance
	Type = OBJECT
End

Upgrade Upgrade_CreateAHeroAttachSpy_Level1
	Type = OBJECT
End

Upgrade Upgrade_CreateAHeroAttachSpy_Level2
	Type = OBJECT
End

Upgrade Upgrade_CreateAHeroCoerce_Level1
	Type = OBJECT
End

Upgrade Upgrade_CreateAHeroCoerce_Level2
	Type = OBJECT
End

Upgrade Upgrade_CreateAHeroCoerce_Level3
	Type = OBJECT
End

Upgrade Upgrade_CreateAHeroDisguise
	Type = OBJECT
End

Upgrade Upgrade_CreateAHeroCMStealth_Level1
	Type = OBJECT
End

Upgrade Upgrade_CreateAHeroCMStealth_Level2
	Type = OBJECT
End

Upgrade Upgrade_CreateAHeroAStealth_Level1
	Type = OBJECT
End

Upgrade Upgrade_CreateAHeroElvenCloak
	Type = OBJECT
End

Upgrade Upgrade_CreateAHeroClimbWalls
	Type = OBJECT
End

Upgrade Upgrade_CreateAHeroStealMoney_Level1
	Type = OBJECT
End

Upgrade Upgrade_CreateAHeroStealMoney_Level2
	Type = OBJECT
End

Upgrade Upgrade_CreateAHeroStealMoney_Level3
	Type = OBJECT
End

Upgrade Upgrade_CreateAHeroAssassin_Level1
	Type = OBJECT
End

Upgrade Upgrade_CreateAHeroAssassin_Level2
	Type = OBJECT
End

Upgrade Upgrade_CreateAHeroAssassin_Level3
	Type = OBJECT
End

Upgrade Upgrade_CreateAHeroAssassin_Level4
	Type = OBJECT
End

Upgrade Upgrade_CreateAHeroRainOfArrows_Level1
	Type = OBJECT
End

Upgrade Upgrade_CreateAHeroRainOfArrows_Level2
	Type = OBJECT
End

Upgrade Upgrade_CreateAHeroRainOfArrows_Level3
	Type = OBJECT
End

Upgrade Upgrade_CreateAHeroWTrueSight
	Type = OBJECT
End

Upgrade Upgrade_CreateAHeroATrueSight
	Type = OBJECT
End

Upgrade Upgrade_CreateAHeroHealing_Level1
	Type = OBJECT
End

Upgrade Upgrade_CreateAHeroHealing_Level2
	Type = OBJECT
End

Upgrade Upgrade_CreateAHeroArrowBonus_Level1
	Type = OBJECT
End

Upgrade Upgrade_CreateAHeroArrowBonus_Level2
	Type = OBJECT
End

Upgrade Upgrade_CreateAHeroArrowBonus_Level3
	Type = OBJECT
End

Upgrade Upgrade_CreateAHeroArrowBonus_Level4
	Type = OBJECT
End

Upgrade Upgrade_CreateAHeroSummonFamiliar_Level1
	Type = OBJECT
End

Upgrade Upgrade_CreateAHeroSummonFamiliar_Level2
	Type = OBJECT
End

Upgrade Upgrade_CreateAHeroSummonFamiliar_Level3
	Type = OBJECT
End

Upgrade Upgrade_CreateAHeroSpawnTornado_Level1
	Type = OBJECT
End

Upgrade Upgrade_CreateAHeroSpawnTornado_Level2
	Type = OBJECT
End

Upgrade Upgrade_CreateAHeroSpawnTornado_Level3
	Type = OBJECT
End

Upgrade Upgrade_CreateAHeroAxeThrow_Level1
	Type = OBJECT
End

Upgrade Upgrade_CreateAHeroAxeThrow_Level2
	Type = OBJECT
End

Upgrade Upgrade_CreateAHeroAxeThrow_Level3
	Type = OBJECT
End

Upgrade Upgrade_CreateAHeroEarthShaker_Level1
	Type = OBJECT
End

Upgrade Upgrade_CreateAHeroEarthShaker_Level2
	Type = OBJECT
End

Upgrade Upgrade_CreateAHeroEarthShaker_Level3
	Type = OBJECT
End

Upgrade Upgrade_CreateAHeroLeap_Level1
	Type = OBJECT
End

Upgrade Upgrade_CreateAHeroLeap_Level2
	Type = OBJECT
End

Upgrade Upgrade_CreateAHeroCharge_Level1
	Type = OBJECT
End

Upgrade Upgrade_CreateAHeroCharge_Level2
	Type = OBJECT
End

Upgrade Upgrade_CreateAHeroCharge_Level3
	Type = OBJECT
End

Upgrade Upgrade_CreateAHeroSapper_Level1
	Type = OBJECT
End

Upgrade Upgrade_CreateAHeroSapper_Level2
	Type = OBJECT
End

Upgrade Upgrade_CreateAHeroSapper_Level3
	Type = OBJECT
End

Upgrade Upgrade_CreateAHeroBombard_Level1
	Type = OBJECT
End

Upgrade Upgrade_CreateAHeroBombard_Level2
	Type = OBJECT
End

Upgrade Upgrade_CreateAHeroBombard_Level3
	Type = OBJECT
End

Upgrade Upgrade_CreateAHeroToughness
	Type = OBJECT
End

Upgrade Upgrade_CreateAHeroBattleRage_Level1
	Type = OBJECT
End

Upgrade Upgrade_CreateAHeroBattleRage_Level2
	Type = OBJECT
End

Upgrade Upgrade_CreateAHeroBattleRage_Level3
	Type = OBJECT
End

Upgrade Upgrade_CreateAHeroBattleRage_Level4
	Type = OBJECT
End

//--------------------------------------------------------
// Create a Hero CLASS upgrades
//--------------------------------------------------------
Upgrade Upgrade_CreateAHero_ClassHeroOfTheWest
  Type              = OBJECT
End

Upgrade Upgrade_CreateAHero_ClassIstariWizard
  Type              = OBJECT
End

Upgrade Upgrade_CreateAHero_ClassDwarf
  Type              = OBJECT
End

Upgrade Upgrade_CreateAHero_ClassCorruptedMan
  Type              = OBJECT
End

Upgrade Upgrade_CreateAHero_ClassServantsOfSauron
  Type              = OBJECT
End

Upgrade Upgrade_CreateAHero_ClassArcher
  Type              = OBJECT
End
//-------------------------------------------------------
// Create a Hero SUB-CLASS upgrades
//-------------------------------------------------------
Upgrade Upgrade_CreateAHero_SubClass_0
  Type              = OBJECT
End

Upgrade Upgrade_CreateAHero_SubClass_1
  Type              = OBJECT
End

Upgrade Upgrade_CreateAHero_SubClass_2
  Type              = OBJECT
End

Upgrade Upgrade_CreateAHero_SubClass_3
  Type              = OBJECT
End

Upgrade Upgrade_CreateAHero_SubClass_4
  Type              = OBJECT
End

Upgrade Upgrade_CreateAHero_SubClass_5
  Type              = OBJECT
End

Upgrade Upgrade_CreateAHero_SubClass_6
  Type              = OBJECT
End

Upgrade Upgrade_CreateAHero_SubClass_7
  Type              = OBJECT
End

//-------------------------------------------------------
// Create a Hero Attribute upgrades
//-------------------------------------------------------

//-------------------------------------------------------
// ArmorAttribute
Upgrade Upgrade_ArmorAttribute01
  Type              = OBJECT
  GroupName			= CreateAHero_ArmorAttribute
  GroupOrder		= 0
End
Upgrade Upgrade_ArmorAttribute02
  Type              = OBJECT
  GroupName			= CreateAHero_ArmorAttribute
  GroupOrder		= 1
End
Upgrade Upgrade_ArmorAttribute03
  Type              = OBJECT
  GroupName			= CreateAHero_ArmorAttribute
  GroupOrder		= 2
End
Upgrade Upgrade_ArmorAttribute04
  Type              = OBJECT
  GroupName			= CreateAHero_ArmorAttribute
  GroupOrder		= 3
End
Upgrade Upgrade_ArmorAttribute05
  Type              = OBJECT
  GroupName			= CreateAHero_ArmorAttribute
  GroupOrder		= 4
End
Upgrade Upgrade_ArmorAttribute06
  Type              = OBJECT
  GroupName			= CreateAHero_ArmorAttribute
  GroupOrder		= 5
End
Upgrade Upgrade_ArmorAttribute07
  Type              = OBJECT
  GroupName			= CreateAHero_ArmorAttribute
  GroupOrder		= 6
End
Upgrade Upgrade_ArmorAttribute08
  Type              = OBJECT
  GroupName			= CreateAHero_ArmorAttribute
  GroupOrder		= 7
End
Upgrade Upgrade_ArmorAttribute09
  Type              = OBJECT
  GroupName			= CreateAHero_ArmorAttribute
  GroupOrder		= 8
End
Upgrade Upgrade_ArmorAttribute10
  Type              = OBJECT
  GroupName			= CreateAHero_ArmorAttribute
  GroupOrder		= 9
End
Upgrade Upgrade_ArmorAttribute11
  Type              = OBJECT
  GroupName			= CreateAHero_ArmorAttribute
  GroupOrder		= 10
End
Upgrade Upgrade_ArmorAttribute12
  Type              = OBJECT
  GroupName			= CreateAHero_ArmorAttribute
  GroupOrder		= 11
End
Upgrade Upgrade_ArmorAttribute13
  Type              = OBJECT
  GroupName			= CreateAHero_ArmorAttribute
  GroupOrder		= 12
End
Upgrade Upgrade_ArmorAttribute14
  Type              = OBJECT
  GroupName			= CreateAHero_ArmorAttribute
  GroupOrder		= 13
End
Upgrade Upgrade_ArmorAttribute15
  Type              = OBJECT
  GroupName			= CreateAHero_ArmorAttribute
  GroupOrder		= 14
End
Upgrade Upgrade_ArmorAttribute16
  Type              = OBJECT
  GroupName			= CreateAHero_ArmorAttribute
  GroupOrder		= 15
End
Upgrade Upgrade_ArmorAttribute17
  Type              = OBJECT
  GroupName			= CreateAHero_ArmorAttribute
  GroupOrder		= 16
End
Upgrade Upgrade_ArmorAttribute18
  Type              = OBJECT
  GroupName			= CreateAHero_ArmorAttribute
  GroupOrder		= 17
End
Upgrade Upgrade_ArmorAttribute19
  Type              = OBJECT
  GroupName			= CreateAHero_ArmorAttribute
  GroupOrder		= 18
End
Upgrade Upgrade_ArmorAttribute20
  Type              = OBJECT
  GroupName			= CreateAHero_ArmorAttribute
  GroupOrder		= 19
End

//-------------------------------------------------------
// DamageMultAttribute
Upgrade Upgrade_DamageMultAttribute01
  Type              = OBJECT
  GroupName			= CreateAHero_DamageMultAttribute
  GroupOrder		= 0
End
Upgrade Upgrade_DamageMultAttribute02
  Type              = OBJECT
  GroupName			= CreateAHero_DamageMultAttribute
  GroupOrder		= 1
End
Upgrade Upgrade_DamageMultAttribute03
  Type              = OBJECT
  GroupName			= CreateAHero_DamageMultAttribute
  GroupOrder		= 2
End
Upgrade Upgrade_DamageMultAttribute04
  Type              = OBJECT
  GroupName			= CreateAHero_DamageMultAttribute
  GroupOrder		= 3
End
Upgrade Upgrade_DamageMultAttribute05
  Type              = OBJECT
  GroupName			= CreateAHero_DamageMultAttribute
  GroupOrder		= 4
End
Upgrade Upgrade_DamageMultAttribute06
  Type              = OBJECT
  GroupName			= CreateAHero_DamageMultAttribute
  GroupOrder		= 5
End
Upgrade Upgrade_DamageMultAttribute07
  Type              = OBJECT
  GroupName			= CreateAHero_DamageMultAttribute
  GroupOrder		= 6
End
Upgrade Upgrade_DamageMultAttribute08
  Type              = OBJECT
  GroupName			= CreateAHero_DamageMultAttribute
  GroupOrder		= 7
End
Upgrade Upgrade_DamageMultAttribute09
  Type              = OBJECT
  GroupName			= CreateAHero_DamageMultAttribute
  GroupOrder		= 8
End
Upgrade Upgrade_DamageMultAttribute10
  Type              = OBJECT
  GroupName			= CreateAHero_DamageMultAttribute
  GroupOrder		= 9
End
Upgrade Upgrade_DamageMultAttribute11
  Type              = OBJECT
  GroupName			= CreateAHero_DamageMultAttribute
  GroupOrder		= 10
End
Upgrade Upgrade_DamageMultAttribute12
  Type              = OBJECT
  GroupName			= CreateAHero_DamageMultAttribute
  GroupOrder		= 11
End
Upgrade Upgrade_DamageMultAttribute13
  Type              = OBJECT
  GroupName			= CreateAHero_DamageMultAttribute
  GroupOrder		= 12
End
Upgrade Upgrade_DamageMultAttribute14
  Type              = OBJECT
  GroupName			= CreateAHero_DamageMultAttribute
  GroupOrder		= 13
End
Upgrade Upgrade_DamageMultAttribute15
  Type              = OBJECT
  GroupName			= CreateAHero_DamageMultAttribute
  GroupOrder		= 14
End
Upgrade Upgrade_DamageMultAttribute16
  Type              = OBJECT
  GroupName			= CreateAHero_DamageMultAttribute
  GroupOrder		= 15
End
Upgrade Upgrade_DamageMultAttribute17
  Type              = OBJECT
  GroupName			= CreateAHero_DamageMultAttribute
  GroupOrder		= 16
End
Upgrade Upgrade_DamageMultAttribute18
  Type              = OBJECT
  GroupName			= CreateAHero_DamageMultAttribute
  GroupOrder		= 17
End
Upgrade Upgrade_DamageMultAttribute19
  Type              = OBJECT
  GroupName			= CreateAHero_DamageMultAttribute
  GroupOrder		= 18
End
Upgrade Upgrade_DamageMultAttribute20
  Type              = OBJECT
  GroupName			= CreateAHero_DamageMultAttribute
  GroupOrder		= 19
End

//-------------------------------------------------------
// VisionAttribute
Upgrade Upgrade_VisionAttribute01
  Type              = OBJECT
  GroupName			= CreateAHero_VisionAttribute
  GroupOrder		= 0
End
Upgrade Upgrade_VisionAttribute02
  Type              = OBJECT
  GroupName			= CreateAHero_VisionAttribute
  GroupOrder		= 1
End
Upgrade Upgrade_VisionAttribute03
  Type              = OBJECT
  GroupName			= CreateAHero_VisionAttribute
  GroupOrder		= 2
End
Upgrade Upgrade_VisionAttribute04
  Type              = OBJECT
  GroupName			= CreateAHero_VisionAttribute
  GroupOrder		= 3
End
Upgrade Upgrade_VisionAttribute05
  Type              = OBJECT
  GroupName			= CreateAHero_VisionAttribute
  GroupOrder		= 4
End
Upgrade Upgrade_VisionAttribute06
  Type              = OBJECT
  GroupName			= CreateAHero_VisionAttribute
  GroupOrder		= 5
End
Upgrade Upgrade_VisionAttribute07
  Type              = OBJECT
  GroupName			= CreateAHero_VisionAttribute
  GroupOrder		= 6
End
Upgrade Upgrade_VisionAttribute08
  Type              = OBJECT
  GroupName			= CreateAHero_VisionAttribute
  GroupOrder		= 7
End
Upgrade Upgrade_VisionAttribute09
  Type              = OBJECT
  GroupName			= CreateAHero_VisionAttribute
  GroupOrder		= 8
End
Upgrade Upgrade_VisionAttribute10
  Type              = OBJECT
  GroupName			= CreateAHero_VisionAttribute
  GroupOrder		= 9
End
Upgrade Upgrade_VisionAttribute11
  Type              = OBJECT
  GroupName			= CreateAHero_VisionAttribute
  GroupOrder		= 10
End
Upgrade Upgrade_VisionAttribute12
  Type              = OBJECT
  GroupName			= CreateAHero_VisionAttribute
  GroupOrder		= 11
End
Upgrade Upgrade_VisionAttribute13
  Type              = OBJECT
  GroupName			= CreateAHero_VisionAttribute
  GroupOrder		= 12
End
Upgrade Upgrade_VisionAttribute14
  Type              = OBJECT
  GroupName			= CreateAHero_VisionAttribute
  GroupOrder		= 13
End
Upgrade Upgrade_VisionAttribute15
  Type              = OBJECT
  GroupName			= CreateAHero_VisionAttribute
  GroupOrder		= 14
End
Upgrade Upgrade_VisionAttribute16
  Type              = OBJECT
  GroupName			= CreateAHero_VisionAttribute
  GroupOrder		= 15
End
Upgrade Upgrade_VisionAttribute17
  Type              = OBJECT
  GroupName			= CreateAHero_VisionAttribute
  GroupOrder		= 16
End
Upgrade Upgrade_VisionAttribute18
  Type              = OBJECT
  GroupName			= CreateAHero_VisionAttribute
  GroupOrder		= 17
End
Upgrade Upgrade_VisionAttribute19
  Type              = OBJECT
  GroupName			= CreateAHero_VisionAttribute
  GroupOrder		= 18
End
Upgrade Upgrade_VisionAttribute20
  Type              = OBJECT
  GroupName			= CreateAHero_VisionAttribute
  GroupOrder		= 19
End

//-------------------------------------------------------
// AutoHealAttribute
Upgrade Upgrade_AutoHealAttribute01
  Type              = OBJECT
  GroupName			= CreateAHero_AutoHealAttribute
  GroupOrder		= 0
End
Upgrade Upgrade_AutoHealAttribute02
  Type              = OBJECT
  GroupName			= CreateAHero_AutoHealAttribute
  GroupOrder		= 1
End
Upgrade Upgrade_AutoHealAttribute03
  Type              = OBJECT
  GroupName			= CreateAHero_AutoHealAttribute
  GroupOrder		= 2
End
Upgrade Upgrade_AutoHealAttribute04
  Type              = OBJECT
  GroupName			= CreateAHero_AutoHealAttribute
  GroupOrder		= 3
End
Upgrade Upgrade_AutoHealAttribute05
  Type              = OBJECT
  GroupName			= CreateAHero_AutoHealAttribute
  GroupOrder		= 4
End
Upgrade Upgrade_AutoHealAttribute06
  Type              = OBJECT
  GroupName			= CreateAHero_AutoHealAttribute
  GroupOrder		= 5
End
Upgrade Upgrade_AutoHealAttribute07
  Type              = OBJECT
  GroupName			= CreateAHero_AutoHealAttribute
  GroupOrder		= 6
End
Upgrade Upgrade_AutoHealAttribute08
  Type              = OBJECT
  GroupName			= CreateAHero_AutoHealAttribute
  GroupOrder		= 7
End
Upgrade Upgrade_AutoHealAttribute09
  Type              = OBJECT
  GroupName			= CreateAHero_AutoHealAttribute
  GroupOrder		= 8
End
Upgrade Upgrade_AutoHealAttribute10
  Type              = OBJECT
  GroupName			= CreateAHero_AutoHealAttribute
  GroupOrder		= 9
End
Upgrade Upgrade_AutoHealAttribute11
  Type              = OBJECT
  GroupName			= CreateAHero_AutoHealAttribute
  GroupOrder		= 10
End
Upgrade Upgrade_AutoHealAttribute12
  Type              = OBJECT
  GroupName			= CreateAHero_AutoHealAttribute
  GroupOrder		= 11
End
Upgrade Upgrade_AutoHealAttribute13
  Type              = OBJECT
  GroupName			= CreateAHero_AutoHealAttribute
  GroupOrder		= 12
End
Upgrade Upgrade_AutoHealAttribute14
  Type              = OBJECT
  GroupName			= CreateAHero_AutoHealAttribute
  GroupOrder		= 13
End
Upgrade Upgrade_AutoHealAttribute15
  Type              = OBJECT
  GroupName			= CreateAHero_AutoHealAttribute
  GroupOrder		= 14
End
Upgrade Upgrade_AutoHealAttribute16
  Type              = OBJECT
  GroupName			= CreateAHero_AutoHealAttribute
  GroupOrder		= 15
End
Upgrade Upgrade_AutoHealAttribute17
  Type              = OBJECT
  GroupName			= CreateAHero_AutoHealAttribute
  GroupOrder		= 16
End
Upgrade Upgrade_AutoHealAttribute18
  Type              = OBJECT
  GroupName			= CreateAHero_AutoHealAttribute
  GroupOrder		= 17
End
Upgrade Upgrade_AutoHealAttribute19
  Type              = OBJECT
  GroupName			= CreateAHero_AutoHealAttribute
  GroupOrder		= 18
End
Upgrade Upgrade_AutoHealAttribute20
  Type              = OBJECT
  GroupName			= CreateAHero_AutoHealAttribute
  GroupOrder		= 19
End

//-------------------------------------------------------
// HealthMultAttribute
Upgrade Upgrade_HealthMultAttribute01
  Type              = OBJECT
  GroupName			= CreateAHero_HealthMultAttribute
  GroupOrder		= 0
End
Upgrade Upgrade_HealthMultAttribute02
  Type              = OBJECT
  GroupName			= CreateAHero_HealthMultAttribute
  GroupOrder		= 1
End
Upgrade Upgrade_HealthMultAttribute03
  Type              = OBJECT
  GroupName			= CreateAHero_HealthMultAttribute
  GroupOrder		= 2
End
Upgrade Upgrade_HealthMultAttribute04
  Type              = OBJECT
  GroupName			= CreateAHero_HealthMultAttribute
  GroupOrder		= 3
End
Upgrade Upgrade_HealthMultAttribute05
  Type              = OBJECT
  GroupName			= CreateAHero_HealthMultAttribute
  GroupOrder		= 4
End
Upgrade Upgrade_HealthMultAttribute06
  Type              = OBJECT
  GroupName			= CreateAHero_HealthMultAttribute
  GroupOrder		= 5
End
Upgrade Upgrade_HealthMultAttribute07
  Type              = OBJECT
  GroupName			= CreateAHero_HealthMultAttribute
  GroupOrder		= 6
End
Upgrade Upgrade_HealthMultAttribute08
  Type              = OBJECT
  GroupName			= CreateAHero_HealthMultAttribute
  GroupOrder		= 7
End
Upgrade Upgrade_HealthMultAttribute09
  Type              = OBJECT
  GroupName			= CreateAHero_HealthMultAttribute
  GroupOrder		= 8
End
Upgrade Upgrade_HealthMultAttribute10
  Type              = OBJECT
  GroupName			= CreateAHero_HealthMultAttribute
  GroupOrder		= 9
End
Upgrade Upgrade_HealthMultAttribute11
  Type              = OBJECT
  GroupName			= CreateAHero_HealthMultAttribute
  GroupOrder		= 10
End
Upgrade Upgrade_HealthMultAttribute12
  Type              = OBJECT
  GroupName			= CreateAHero_HealthMultAttribute
  GroupOrder		= 11
End
Upgrade Upgrade_HealthMultAttribute13
  Type              = OBJECT
  GroupName			= CreateAHero_HealthMultAttribute
  GroupOrder		= 12
End
Upgrade Upgrade_HealthMultAttribute14
  Type              = OBJECT
  GroupName			= CreateAHero_HealthMultAttribute
  GroupOrder		= 13
End
Upgrade Upgrade_HealthMultAttribute15
  Type              = OBJECT
  GroupName			= CreateAHero_HealthMultAttribute
  GroupOrder		= 14
End
Upgrade Upgrade_HealthMultAttribute16
  Type              = OBJECT
  GroupName			= CreateAHero_HealthMultAttribute
  GroupOrder		= 15
End
Upgrade Upgrade_HealthMultAttribute17
  Type              = OBJECT
  GroupName			= CreateAHero_HealthMultAttribute
  GroupOrder		= 16
End
Upgrade Upgrade_HealthMultAttribute18
  Type              = OBJECT
  GroupName			= CreateAHero_HealthMultAttribute
  GroupOrder		= 17
End
Upgrade Upgrade_HealthMultAttribute19
  Type              = OBJECT
  GroupName			= CreateAHero_HealthMultAttribute
  GroupOrder		= 18
End
Upgrade Upgrade_HealthMultAttribute20
  Type              = OBJECT
  GroupName			= CreateAHero_HealthMultAttribute
  GroupOrder		= 19
End

//----------------------------------------------------------
// Create A Hero Appearance Bling
//----------------------------------------------------------


//-------------------------------------------------------
// Shoulder Plates
Upgrade Upgrade_Uruk_CHSP01
  Type              = OBJECT
  GroupName			= CreateAHero_ShoulderPlates
  GroupOrder		= 1
End

Upgrade Upgrade_Uruk_CHSP02
  Type              = OBJECT
  GroupName			= CreateAHero_ShoulderPlates
  GroupOrder		= 2
End

Upgrade Upgrade_Uruk_CHSP03
  Type              = OBJECT
  GroupName			= CreateAHero_ShoulderPlates
  GroupOrder		= 3
End

Upgrade Upgrade_CorruptedMan_1_CHSP01
  Type              = OBJECT
  GroupName			= CreateAHero_ShoulderPlates
  GroupOrder		= 1
End

Upgrade Upgrade_CorruptedMan_1_CHSP02
  Type              = OBJECT
  GroupName			= CreateAHero_ShoulderPlates
  GroupOrder		= 2
End

Upgrade Upgrade_CorruptedMan_1_CHSP03
  Type              = OBJECT
  GroupName			= CreateAHero_ShoulderPlates
  GroupOrder		= 3
End

Upgrade Upgrade_CorruptedMan_1_CHSP04
  Type              = OBJECT
  GroupName			= CreateAHero_ShoulderPlates
  GroupOrder		= 4
End

Upgrade Upgrade_DWARF_CHSP01
  Type              = OBJECT
  GroupName			= CreateAHero_ShoulderPlates
  GroupOrder		= 1
End

Upgrade Upgrade_DWARF_CHSP02
  Type              = OBJECT
  GroupName			= CreateAHero_ShoulderPlates
  GroupOrder		= 2
End

Upgrade Upgrade_DWARF_CHSP03
  Type              = OBJECT
  GroupName			= CreateAHero_ShoulderPlates
  GroupOrder		= 3
End

Upgrade Upgrade_DWARF_CHSP04
  Type              = OBJECT
  GroupName			= CreateAHero_ShoulderPlates
  GroupOrder		= 4
End

Upgrade Upgrade_DWARF_CHSP05
  Type              = OBJECT
  GroupName			= CreateAHero_ShoulderPlates
  GroupOrder		= 5
End

Upgrade Upgrade_CaptainOfGondor_CHSP01
  Type              = OBJECT
  GroupName			= CreateAHero_ShoulderPlates
  GroupOrder		= 1
End

Upgrade Upgrade_CaptainOfGondor_CHSP02
  Type              = OBJECT
  GroupName			= CreateAHero_ShoulderPlates
  GroupOrder		= 2
End

Upgrade Upgrade_ELFA_CHSP01
  Type              = OBJECT
  GroupName			= CreateAHero_ShoulderPlates
  GroupOrder		= 1
End

Upgrade Upgrade_ELFA_CHSP02
  Type              = OBJECT
  GroupName			= CreateAHero_ShoulderPlates
  GroupOrder		= 2
End

Upgrade Upgrade_ELFA_CHSP03
  Type              = OBJECT
  GroupName			= CreateAHero_ShoulderPlates
  GroupOrder		= 3
End

Upgrade Upgrade_SHIM_CHSP01
  Type              = OBJECT
  GroupName			= CreateAHero_ShoulderPlates
  GroupOrder		= 1
End

Upgrade Upgrade_SHIM_CHSP02
  Type              = OBJECT
  GroupName			= CreateAHero_ShoulderPlates
  GroupOrder		= 2
End

Upgrade Upgrade_SHIM_CHSP03
  Type              = OBJECT
  GroupName			= CreateAHero_ShoulderPlates
  GroupOrder		= 3
End

Upgrade Upgrade_FEARCH_CHSP01
  Type              = OBJECT
  GroupName			= CreateAHero_ShoulderPlates
  GroupOrder		= 1
End

Upgrade Upgrade_FEARCH_CHSP02
  Type              = OBJECT
  GroupName			= CreateAHero_ShoulderPlates
  GroupOrder		= 2
End

Upgrade Upgrade_FEARCH_CHSP03
  Type              = OBJECT
  GroupName			= CreateAHero_ShoulderPlates
  GroupOrder		= 3
End

Upgrade Upgrade_FEARCH_CHSP04
  Type              = OBJECT
  GroupName			= CreateAHero_ShoulderPlates
  GroupOrder		= 4
End

Upgrade Upgrade_FEARCH_CHSP05
  Type              = OBJECT
  GroupName			= CreateAHero_ShoulderPlates
  GroupOrder		= 5
End

Upgrade Upgrade_WIZ_CHSP01
  Type              = OBJECT
  GroupName			= CreateAHero_ShoulderPlates
  GroupOrder		= 1
End

Upgrade Upgrade_WIZ_CHSP02
  Type              = OBJECT
  GroupName			= CreateAHero_ShoulderPlates
  GroupOrder		= 2
End

Upgrade Upgrade_TRLL_CHSP01
  Type              = OBJECT
  GroupName			= CreateAHero_ShoulderPlates
  GroupOrder		= 1
End

Upgrade Upgrade_TRLL_CHSP02
  Type              = OBJECT
  GroupName			= CreateAHero_ShoulderPlates
  GroupOrder		= 2
End

Upgrade Upgrade_TRLL_CHSP03
  Type              = OBJECT
  GroupName			= CreateAHero_ShoulderPlates
  GroupOrder		= 3
End

Upgrade Upgrade_TRLL_CHSP04
  Type              = OBJECT
  GroupName			= CreateAHero_ShoulderPlates
  GroupOrder		= 4
End

Upgrade Upgrade_TRLL_CHSP05
  Type              = OBJECT
  GroupName			= CreateAHero_ShoulderPlates
  GroupOrder		= 5
End

Upgrade Upgrade_ORC_CHSP01
  Type              = OBJECT
  GroupName			= CreateAHero_ShoulderPlates
  GroupOrder		= 4
End

//-------------------------------------------------------
// Helmet
Upgrade Upgrade_Uruk_CHHAIR01
  Type              = OBJECT
  GroupName			= CreateAHero_Helmet
  GroupOrder		= 1
End

Upgrade Upgrade_Uruk_CHH01
  Type              = OBJECT
  GroupName			= CreateAHero_Helmet
  GroupOrder		= 2
End

Upgrade Upgrade_Uruk_CHH02
  Type              = OBJECT
  GroupName			= CreateAHero_Helmet
  GroupOrder		= 3
End

Upgrade Upgrade_Uruk_CHH03
  Type              = OBJECT
  GroupName			= CreateAHero_Helmet
  GroupOrder		= 4
End

Upgrade Upgrade_Uruk_CHH04
  Type              = OBJECT
  GroupName			= CreateAHero_Helmet
  GroupOrder		= 5
End

Upgrade Upgrade_CorruptedMan_1_CHH01
  Type              = OBJECT
  GroupName			= CreateAHero_Helmet
  GroupOrder		= 1
End

Upgrade Upgrade_CorruptedMan_1_CHH02
  Type              = OBJECT
  GroupName			= CreateAHero_Helmet
  GroupOrder		= 2
End

Upgrade Upgrade_CorruptedMan_1_CHH03
  Type              = OBJECT
  GroupName			= CreateAHero_Helmet
  GroupOrder		= 3
End

Upgrade Upgrade_CorruptedMan_1_CHH04
  Type              = OBJECT
  GroupName			= CreateAHero_Helmet
  GroupOrder		= 4
End

Upgrade Upgrade_CorruptedMan_1_CHH05
  Type              = OBJECT
  GroupName			= CreateAHero_Helmet
  GroupOrder		= 5
End

Upgrade Upgrade_DWARF_CHH01
  Type              = OBJECT
  GroupName			= CreateAHero_Helmet
  GroupOrder		= 1
End

Upgrade Upgrade_DWARF_CHH02
  Type              = OBJECT
  GroupName			= CreateAHero_Helmet
  GroupOrder		= 2
End

Upgrade Upgrade_DWARF_CHH03
  Type              = OBJECT
  GroupName			= CreateAHero_Helmet
  GroupOrder		= 3
End

Upgrade Upgrade_DWARF_CHH04
  Type              = OBJECT
  GroupName			= CreateAHero_Helmet
  GroupOrder		=4
End

Upgrade Upgrade_DWARF_CHH05
  Type              = OBJECT
  GroupName			= CreateAHero_Helmet
  GroupOrder		= 5
End

Upgrade Upgrade_CaptainOfGondor_CHH01
  Type              = OBJECT
  GroupName			= CreateAHero_Helmet
  GroupOrder		= 1
End

Upgrade Upgrade_CaptainOfGondor_CHH02
  Type              = OBJECT
  GroupName			= CreateAHero_Helmet
  GroupOrder		= 2
End

Upgrade Upgrade_CaptainOfGondor_CHH03
  Type              = OBJECT
  GroupName			= CreateAHero_Helmet
  GroupOrder		= 3
End

Upgrade Upgrade_ELFA_CHH01
  Type              = OBJECT
  GroupName			= CreateAHero_Helmet
  GroupOrder		= 1
End

Upgrade Upgrade_ELFA_CHH02
  Type              = OBJECT
  GroupName			= CreateAHero_Helmet
  GroupOrder		= 2
End

Upgrade Upgrade_SHIM_CHH01
  Type              = OBJECT
  GroupName			= CreateAHero_Helmet
  GroupOrder		= 1
End

Upgrade Upgrade_SHIM_CHH02
  Type              = OBJECT
  GroupName			= CreateAHero_Helmet
  GroupOrder		= 2
End

Upgrade Upgrade_SHIM_CHH03
  Type              = OBJECT
  GroupName			= CreateAHero_Helmet
  GroupOrder		= 3
End

Upgrade Upgrade_WIZ_CHH01
  Type              = OBJECT
  GroupName			= CreateAHero_Helmet
  GroupOrder		= 1
End

Upgrade Upgrade_WIZ_CHH02
  Type              = OBJECT
  GroupName			= CreateAHero_Helmet
  GroupOrder		= 2
End

Upgrade Upgrade_WIZ_CHH03
  Type              = OBJECT
  GroupName			= CreateAHero_Helmet
  GroupOrder		= 3
End

Upgrade Upgrade_WIZ_CHH04
  Type              = OBJECT
  GroupName			= CreateAHero_Helmet
  GroupOrder		= 4
End

Upgrade Upgrade_WIZ_CHH05
  Type              = OBJECT
  GroupName			= CreateAHero_Helmet
  GroupOrder		= 5
End

Upgrade Upgrade_WIZ_CHH06
  Type              = OBJECT
  GroupName			= CreateAHero_Helmet
  GroupOrder		= 6
End

Upgrade Upgrade_WIZ_CHH07
  Type              = OBJECT
  GroupName			= CreateAHero_Helmet
  GroupOrder		= 7
End

Upgrade Upgrade_FEARCH_CHH01
  Type              = OBJECT
  GroupName			= CreateAHero_Helmet
  GroupOrder		= 1
End

Upgrade Upgrade_FEARCH_CHH02
  Type              = OBJECT
  GroupName			= CreateAHero_Helmet
  GroupOrder		= 2
End

Upgrade Upgrade_FEARCH_CHH03
  Type              = OBJECT
  GroupName			= CreateAHero_Helmet
  GroupOrder		= 3
End

Upgrade Upgrade_FEARCH_CHH04
  Type              = OBJECT
  GroupName			= CreateAHero_Helmet
  GroupOrder		= 4
End

Upgrade Upgrade_FEARCH_CHH05
  Type              = OBJECT
  GroupName			= CreateAHero_Helmet
  GroupOrder		= 5
End

Upgrade Upgrade_TRLL_CHH01
  Type              = OBJECT
  GroupName			= CreateAHero_Helmet
  GroupOrder		= 1
End

Upgrade Upgrade_TRLL_CHH02
  Type              = OBJECT
  GroupName			= CreateAHero_Helmet
  GroupOrder		= 2
End

Upgrade Upgrade_TRLL_CHH03
  Type              = OBJECT
  GroupName			= CreateAHero_Helmet
  GroupOrder		= 3
End

Upgrade Upgrade_ORC_CHH01
  Type              = OBJECT
  GroupName			= CreateAHero_Helmet
  GroupOrder		= 6
End
//-------------------------------------------------------
// Gauntlets
Upgrade Upgrade_Uruk_CHG01
  Type              = OBJECT
  GroupName			= CreateAHero_Gauntlets
  GroupOrder		= 1
End

Upgrade Upgrade_Uruk_CHG02
  Type              = OBJECT
  GroupName			= CreateAHero_Gauntlets
  GroupOrder		= 2
End

Upgrade Upgrade_Uruk_CHG03
  Type              = OBJECT
  GroupName			= CreateAHero_Gauntlets
  GroupOrder		= 3
End

Upgrade Upgrade_CorruptedMan_1_CHG01
  Type              = OBJECT
  GroupName			= CreateAHero_Gauntlets
  GroupOrder		= 1
End

Upgrade Upgrade_CorruptedMan_1_CHG02
  Type              = OBJECT
  GroupName			= CreateAHero_Gauntlets
  GroupOrder		= 2
End

Upgrade Upgrade_CaptainOfGondor_CHG01
  Type              = OBJECT
  GroupName			= CreateAHero_Gauntlets
  GroupOrder		= 1
End

Upgrade Upgrade_CaptainOfGondor_CHG02
  Type              = OBJECT
  GroupName			= CreateAHero_Gauntlets
  GroupOrder		= 2
End

Upgrade Upgrade_CaptainOfGondor_CHG03
  Type              = OBJECT
  GroupName			= CreateAHero_Gauntlets
  GroupOrder		= 3
End

Upgrade Upgrade_ELFA_CHG01
  Type              = OBJECT
  GroupName			= CreateAHero_Gauntlets
  GroupOrder		= 1
End

Upgrade Upgrade_ELFA_CHG02
  Type              = OBJECT
  GroupName			= CreateAHero_Gauntlets
  GroupOrder		= 2
End

Upgrade Upgrade_ELFA_CHG03
  Type              = OBJECT
  GroupName			= CreateAHero_Gauntlets
  GroupOrder		= 3
End

Upgrade Upgrade_SHIM_CHG01
  Type              = OBJECT
  GroupName			= CreateAHero_Gauntlets
  GroupOrder		= 1
End

Upgrade Upgrade_SHIM_CHG02
  Type              = OBJECT
  GroupName			= CreateAHero_Gauntlets
  GroupOrder		= 2
End

Upgrade Upgrade_SHIM_CHG03
  Type              = OBJECT
  GroupName			= CreateAHero_Gauntlets
  GroupOrder		= 3
End


Upgrade Upgrade_FEARCH_CHG01
  Type              = OBJECT
  GroupName			= CreateAHero_Gauntlets
  GroupOrder		= 1
End

Upgrade Upgrade_FEARCH_CHG02
  Type              = OBJECT
  GroupName			= CreateAHero_Gauntlets
  GroupOrder		= 2
End

Upgrade Upgrade_FEARCH_CHG03
  Type              = OBJECT
  GroupName			= CreateAHero_Gauntlets
  GroupOrder		= 3
End

Upgrade Upgrade_FEARCH_CHG04
  Type              = OBJECT
  GroupName			= CreateAHero_Gauntlets
  GroupOrder		= 4
End

Upgrade Upgrade_FEARCH_CHG05
  Type              = OBJECT
  GroupName			= CreateAHero_Gauntlets
  GroupOrder		= 5
End

Upgrade Upgrade_TRLL_CHG01
  Type              = OBJECT
  GroupName			= CreateAHero_Gauntlets
  GroupOrder		= 1
End

Upgrade Upgrade_TRLL_CHG02
  Type              = OBJECT
  GroupName			= CreateAHero_Gauntlets
  GroupOrder		= 2
End

Upgrade Upgrade_TRLL_CHG03
  Type              = OBJECT
  GroupName			= CreateAHero_Gauntlets
  GroupOrder		= 3
End

Upgrade Upgrade_TRLL_CHG04
  Type              = OBJECT
  GroupName			= CreateAHero_Gauntlets
  GroupOrder		= 4
End

Upgrade Upgrade_TRLL_CHG05
  Type              = OBJECT
  GroupName			= CreateAHero_Gauntlets
  GroupOrder		= 5
End


Upgrade Upgrade_DWARF_CHG01
  Type              = OBJECT
  GroupName			= CreateAHero_Gauntlets
  GroupOrder		= 1
End

Upgrade Upgrade_DWARF_CHG02
  Type              = OBJECT
  GroupName			= CreateAHero_Gauntlets
  GroupOrder		= 2
End

Upgrade Upgrade_DWARF_CHG03
  Type              = OBJECT
  GroupName			= CreateAHero_Gauntlets
  GroupOrder		= 3
End

Upgrade Upgrade_ORC_CHG01
  Type              = OBJECT
  GroupName			= CreateAHero_Gauntlets
  GroupOrder		= 4
End
//-------------------------------------------------------
// Shield
Upgrade Upgrade_Uruk_CHS01
  Type              = OBJECT
  GroupName			= CreateAHero_Shield
  GroupOrder		= 0
End

Upgrade Upgrade_Uruk_CHS02
  Type              = OBJECT
  GroupName			= CreateAHero_Shield
  GroupOrder		= 1
End

Upgrade Upgrade_Uruk_CHS03
  Type              = OBJECT
  GroupName			= CreateAHero_Shield
  GroupOrder		= 2
End

Upgrade Upgrade_Uruk_CHS04
  Type              = OBJECT
  GroupName			= CreateAHero_Shield
  GroupOrder		= 3
End

Upgrade Upgrade_CAPG_CHS01
  Type              = OBJECT
  GroupName			= CreateAHero_Shield
  GroupOrder		= 0
End

Upgrade Upgrade_CAPG_CHS02
  Type              = OBJECT
  GroupName			= CreateAHero_Shield
  GroupOrder		= 1
End

Upgrade Upgrade_CAPG_CHS03
  Type              = OBJECT
  GroupName			= CreateAHero_Shield
  GroupOrder		= 3
End

Upgrade Upgrade_CAPG_CHS04
  Type              = OBJECT
  GroupName			= CreateAHero_Shield
  GroupOrder		= 4
End


//-------------------------------------------------------
// Boots
Upgrade Upgrade_Uruk_CHB01
  Type              = OBJECT
  GroupName			= CreateAHero_Boots
  GroupOrder		= 1
End

Upgrade Upgrade_Uruk_CHB02
  Type              = OBJECT
  GroupName			= CreateAHero_Boots
  GroupOrder		= 2
End

Upgrade Upgrade_Uruk_CHB03
  Type              = OBJECT
  GroupName			= CreateAHero_Boots
  GroupOrder		= 3
End

Upgrade Upgrade_CorruptedMan_1_CHB01
  Type              = OBJECT
  GroupName			= CreateAHero_Boots
  GroupOrder		= 1
End

Upgrade Upgrade_CorruptedMan_1_CHB02
  Type              = OBJECT
  GroupName			= CreateAHero_Boots
  GroupOrder		= 2
End

Upgrade Upgrade_CaptainOfGondor_CHB01
  Type              = OBJECT
  GroupName			= CreateAHero_Boots
  GroupOrder		= 1
End

Upgrade Upgrade_CaptainOfGondor_CHB02
  Type              = OBJECT
  GroupName			= CreateAHero_Boots
  GroupOrder		= 2
End

Upgrade Upgrade_CaptainOfGondor_CHB03
  Type              = OBJECT
  GroupName			= CreateAHero_Boots
  GroupOrder		= 3
End

Upgrade Upgrade_ELFA_CHB01
  Type              = OBJECT
  GroupName			= CreateAHero_Boots
  GroupOrder		= 1
End

Upgrade Upgrade_ELFA_CHB02
  Type              = OBJECT
  GroupName			= CreateAHero_Boots
  GroupOrder		= 2
End

Upgrade Upgrade_SHIM_CHB01
  Type              = OBJECT
  GroupName			= CreateAHero_Boots
  GroupOrder		= 1
End

Upgrade Upgrade_SHIM_CHB02
  Type              = OBJECT
  GroupName			= CreateAHero_Boots
  GroupOrder		= 2
End

Upgrade Upgrade_SHIM_CHB03
  Type              = OBJECT
  GroupName			= CreateAHero_Boots
  GroupOrder		= 3
End

Upgrade Upgrade_FEARCH_CHB01
  Type              = OBJECT
  GroupName			= CreateAHero_Boots
  GroupOrder		= 1
End

Upgrade Upgrade_FEARCH_CHB02
  Type              = OBJECT
  GroupName			= CreateAHero_Boots
  GroupOrder		= 2
End

Upgrade Upgrade_FEARCH_CHB03
  Type              = OBJECT
  GroupName			= CreateAHero_Boots
  GroupOrder		= 3
End

Upgrade Upgrade_FEARCH_CHB04
  Type              = OBJECT
  GroupName			= CreateAHero_Boots
  GroupOrder		= 4
End

Upgrade Upgrade_FEARCH_CHB05
  Type              = OBJECT
  GroupName			= CreateAHero_Boots
  GroupOrder		= 5
End

Upgrade Upgrade_DWARF_CHB01
  Type              = OBJECT
  GroupName			= CreateAHero_Boots
  GroupOrder		= 1
End

Upgrade Upgrade_DWARF_CHB02
  Type              = OBJECT
  GroupName			= CreateAHero_Boots
  GroupOrder		= 2
End

Upgrade Upgrade_DWARF_CHB03
  Type              = OBJECT
  GroupName			= CreateAHero_Boots
  GroupOrder		= 3
End

Upgrade Upgrade_ORC_CHB01
  Type              = OBJECT
  GroupName			= CreateAHero_Boots
  GroupOrder		= 4
End
//-------------------------------------------------------
// Generic No Upgrades

Upgrade Upgrade_NoHelmet
	Type			= OBJECT
	GroupName		= CreateAHero_Helmet
	GroupOrder		= 0
End

Upgrade Upgrade_NoShoulderPlates
	Type			= OBJECT
	GroupName		= CreateAHero_ShoulderPlates
	GroupOrder		= 0
End

Upgrade Upgrade_NoGauntlets
	Type			= OBJECT
	GroupName		= CreateAHero_Gauntlets
	GroupOrder		= 0
End

Upgrade Upgrade_NoShield
	Type			= OBJECT
	GroupName		= CreateAHero_Shield
	GroupOrder		= 0
End

Upgrade Upgrade_NoBoots
	Type			= OBJECT
	GroupName		= CreateAHero_Boots
	GroupOrder		= 0
End
//-------------------------------------------------------
// Body
Upgrade Upgrade_CM01_CHBOD01
  Type              = OBJECT
  GroupName			= CreateAHero_Body
  GroupOrder		= 0
End

Upgrade Upgrade_CM01_CHBOD02
  Type              = OBJECT
  GroupName			= CreateAHero_Body
  GroupOrder		= 1
End

Upgrade Upgrade_CM01_CHBOD03
  Type              = OBJECT
  GroupName			= CreateAHero_Body
  GroupOrder		= 2
End

Upgrade Upgrade_CM01_CHBOD04
  Type              = OBJECT
  GroupName			= CreateAHero_Body
  GroupOrder		= 3
End

Upgrade Upgrade_CM01_CHBOD05
  Type              = OBJECT
  GroupName			= CreateAHero_Body
  GroupOrder		= 4
End

Upgrade Upgrade_CM02_CHBOD01
  Type              = OBJECT
  GroupName			= CreateAHero_Body
  GroupOrder		= 0
End

Upgrade Upgrade_CM02_CHBOD02
  Type              = OBJECT
  GroupName			= CreateAHero_Body
  GroupOrder		= 1
End

Upgrade Upgrade_CM02_CHBOD03
  Type              = OBJECT
  GroupName			= CreateAHero_Body
  GroupOrder		= 2
End

Upgrade Upgrade_CM02_CHBOD04
  Type              = OBJECT
  GroupName			= CreateAHero_Body
  GroupOrder		= 3
End

Upgrade Upgrade_CM02_CHBOD05
  Type              = OBJECT
  GroupName			= CreateAHero_Body
  GroupOrder		= 4
End

Upgrade Upgrade_URUK_CHBOD01
  Type              = OBJECT
  GroupName			= CreateAHero_Body
  GroupOrder		= 0
End

Upgrade Upgrade_URUK_CHBOD02
  Type              = OBJECT
  GroupName			= CreateAHero_Body
  GroupOrder		= 1
End

Upgrade Upgrade_URUK_CHBOD03
  Type              = OBJECT
  GroupName			= CreateAHero_Body
  GroupOrder		= 2
End

Upgrade Upgrade_ELFA_CHBOD01
  Type              = OBJECT
  GroupName			= CreateAHero_Body
  GroupOrder		= 0
End

Upgrade Upgrade_ELFA_CHBOD02
  Type              = OBJECT
  GroupName			= CreateAHero_Body
  GroupOrder		= 1
End

Upgrade Upgrade_ELFA_CHBOD03
  Type              = OBJECT
  GroupName			= CreateAHero_Body
  GroupOrder		= 2
End

Upgrade Upgrade_FEARCH_CHBOD01
  Type              = OBJECT
  GroupName			= CreateAHero_Body
  GroupOrder		= 0
End

Upgrade Upgrade_FEARCH_CHBOD02
  Type              = OBJECT
  GroupName			= CreateAHero_Body
  GroupOrder		= 1
End

Upgrade Upgrade_FEARCH_CHBOD03
  Type              = OBJECT
  GroupName			= CreateAHero_Body
  GroupOrder		= 2
End

Upgrade Upgrade_CAPG_CHBOD01
  Type              = OBJECT
  GroupName			= CreateAHero_Body
  GroupOrder		= 0
End

Upgrade Upgrade_CAPG_CHBOD02
  Type              = OBJECT
  GroupName			= CreateAHero_Body
  GroupOrder		= 1
End

Upgrade Upgrade_CAPG_CHBOD03
  Type              = OBJECT
  GroupName			= CreateAHero_Body
  GroupOrder		= 2
End

Upgrade Upgrade_SHIM_CHBOD01
  Type              = OBJECT
  GroupName			= CreateAHero_Body
  GroupOrder		= 0
End

Upgrade Upgrade_SHIM_CHBOD02
  Type              = OBJECT
  GroupName			= CreateAHero_Body
  GroupOrder		= 1
End

Upgrade Upgrade_SHIM_CHBOD03
  Type              = OBJECT
  GroupName			= CreateAHero_Body
  GroupOrder		= 2
End

Upgrade Upgrade_WIZ_CHBOD01
  Type              = OBJECT
  GroupName			= CreateAHero_Body
  GroupOrder		= 0
End

Upgrade Upgrade_WIZ_CHBOD02
  Type              = OBJECT
  GroupName			= CreateAHero_Body
  GroupOrder		= 1
End

Upgrade Upgrade_WIZ_CHBOD03
  Type              = OBJECT
  GroupName			= CreateAHero_Body
  GroupOrder		= 2
End

Upgrade Upgrade_ORC_CHBOD01
  Type              = OBJECT
  GroupName			= CreateAHero_Body
  GroupOrder		= 0
End

Upgrade Upgrade_ORC_CHBOD02
  Type              = OBJECT
  GroupName			= CreateAHero_Body
  GroupOrder		= 1
End

Upgrade Upgrade_TRLL_CHBOD01
  Type              = OBJECT
  GroupName			= CreateAHero_Body
  GroupOrder		= 0
End

Upgrade Upgrade_TRLL_CHBOD02
  Type              = OBJECT
  GroupName			= CreateAHero_Body
  GroupOrder		= 1
End

Upgrade Upgrade_TRLL_CHBOD03
  Type              = OBJECT
  GroupName			= CreateAHero_Body
  GroupOrder		= 2
End

Upgrade Upgrade_DWARF_CHBOD01
  Type              = OBJECT
  GroupName			= CreateAHero_Body
  GroupOrder		= 0
End

Upgrade Upgrade_DWARF_CHBOD02
  Type              = OBJECT
  GroupName			= CreateAHero_Body
  GroupOrder		= 1
End

Upgrade Upgrade_DWARF_CHBOD03
  Type              = OBJECT
  GroupName			= CreateAHero_Body
  GroupOrder		= 2
End

Upgrade Upgrade_DSAGE_CHBOD01
  Type              = OBJECT
  GroupName			= CreateAHero_Body
  GroupOrder		= 0
End

Upgrade Upgrade_DSAGE_CHBOD02
  Type              = OBJECT
  GroupName			= CreateAHero_Body
  GroupOrder		= 1
End

Upgrade Upgrade_DSAGE_CHBOD03
  Type              = OBJECT
  GroupName			= CreateAHero_Body
  GroupOrder		= 2
End

