//-------------------------------------------------------------------------------------
//						CREATE A HERO WEAPON DEFINITIONS                               
//-------------------------------------------------------------------------------------
	CreateAHeroBling	// Dwarf Axe 01
		NameTag			 = CreateAHero:BlingName_DwarfAxe_01
		DescriptionTag	 = CreateAHero:BlingDesc_DwarfAxe_01
		GroupName		 = CreateAHero_Weapon
		BlingUpgradeName = Upgrade_CHW01	 
	End


	CreateAHeroBling //	Gurthang sword
		NameTag			 = CreateAHero:BlingName_Gurthang
		DescriptionTag	 = CreateAHero:BlingDesc_Gurthang
		GroupName		 = CreateAHero_Weapon
		BlingUpgradeName = Upgrade_CHW03	 
	End

	CreateAHeroBling //	Westron	Sword
		NameTag			 = CreateAHero:BlingName_Westron
		DescriptionTag	 = CreateAHero:BlingDesc_Westron
		GroupName		 = CreateAHero_Weapon
		BlingUpgradeName = Upgrade_CHW04	 
	End
	CreateAHeroBling //	Troll Bane Sword
		NameTag			 = CreateAHero:BlingName_TrollBane
		DescriptionTag	 = CreateAHero:BlingDesc_TrollBane
		GroupName		 = CreateAHero_Weapon
		BlingUpgradeName = Upgrade_CHW05	 
	End

	CreateAHeroBling //	Fire Brand Sword
		NameTag			 = CreateAHero:BlingName_FireBrand
		DescriptionTag	 = CreateAHero:BlingDesc_FireBrand
		GroupName		 = CreateAHero_Weapon
		BlingUpgradeName = Upgrade_CHW06 
	End

	CreateAHeroBling //	Belthronding Bow
		NameTag			 = CreateAHero:BlingName_Belthronding
		DescriptionTag	 = CreateAHero:BlingDesc_Belthronding
		GroupName		 = CreateAHero_Weapon
		BlingUpgradeName = Upgrade_CHW02
	End

	CreateAHeroBling //	MithlondBow	Bow
		NameTag			 = CreateAHero:BlingName_MithlondBow
		DescriptionTag	 = CreateAHero:BlingDesc_MithlondBow
		GroupName		 = CreateAHero_Weapon
		BlingUpgradeName = Upgrade_CHW08
	End

	CreateAHeroBling //	WizardStaff	01
		NameTag			 = CreateAHero:BlingName_WizardStaff01
		DescriptionTag	 = CreateAHero:BlingDesc_WizardStaff01
		GroupName		 = CreateAHero_Weapon
		BlingUpgradeName = Upgrade_CHW07
	End

	CreateAHeroBling //	WizardStaff	02
		NameTag			 = CreateAHero:BlingName_WizardStaff02
		DescriptionTag	 = CreateAHero:BlingDesc_WizardStaff02
		GroupName		 = CreateAHero_Weapon
		BlingUpgradeName = Upgrade_CHW09
	End

	CreateAHeroBling //	WizardStaff	03
		NameTag			 = CreateAHero:BlingName_WizardStaff03
		DescriptionTag	 = CreateAHero:BlingDesc_WizardStaff03
		GroupName		 = CreateAHero_Weapon
		BlingUpgradeName = Upgrade_CHW10
	End

	CreateAHeroBling //	WizardStaff	04
		NameTag			 = CreateAHero:BlingName_WizardStaff04
		DescriptionTag	 = CreateAHero:BlingDesc_WizardStaff04
		GroupName		 = CreateAHero_Weapon
		BlingUpgradeName = Upgrade_CHW11
	End

	CreateAHeroBling //	Troll Mace
		NameTag			 = CreateAHero:BlingName_TrollMace
		DescriptionTag	 = CreateAHero:BlingDesc_TrollMace
		GroupName		 = CreateAHero_Weapon
		BlingUpgradeName = Upgrade_CHW12
	End

	CreateAHeroBling //	Troll Sword
		NameTag			 = CreateAHero:BlingName_TrollSword
		DescriptionTag	 = CreateAHero:BlingDesc_TrollSword
		GroupName		 = CreateAHero_Weapon
		BlingUpgradeName = Upgrade_CHW13
	End

	CreateAHeroBling //	Troll Hammer
		NameTag			 = CreateAHero:BlingName_TrollSword
		DescriptionTag	 = CreateAHero:BlingDesc_TrollSword
		GroupName		 = CreateAHero_Weapon
		BlingUpgradeName = Upgrade_CHW14
	End

	CreateAHeroBling //	Troll Tree
		NameTag			 = CreateAHero:BlingName_TrollTree
		DescriptionTag	 = CreateAHero:BlingDesc_TrollTree
		GroupName		 = CreateAHero_Weapon
		BlingUpgradeName = Upgrade_CHW15
	End

	// Uruk Weapons
	CreateAHeroBling // Uruk Sword 01
		NameTag			 = CreateAHero:BlingName_Uruk_Sword_01
		DescriptionTag	 = CreateAHero:BlingDesc_Uruk_Sword_01
		GroupName		 = CreateAHero_Weapon
		BlingUpgradeName = Upgrade_CHW18
	End

	CreateAHeroBling // Uruk Sword 01
		NameTag			 = CreateAHero:BlingName_Uruk_Sword_02
		DescriptionTag	 = CreateAHero:BlingDesc_Uruk_Sword_02
		GroupName		 = CreateAHero_Weapon
		BlingUpgradeName = Upgrade_CHW19
	End

	CreateAHeroBling // Uruk Sword 01
		NameTag			 = CreateAHero:BlingName_Uruk_Sword_03
		DescriptionTag	 = CreateAHero:BlingDesc_Uruk_Sword_03
		GroupName		 = CreateAHero_Weapon
		BlingUpgradeName = Upgrade_CHW20
	End
	
	CreateAHeroBling //	Corrupted Man Club
		NameTag			 = CreateAHero:BlingName_CM_Club
		DescriptionTag	 = CreateAHero:BlingDesc_CM_Club
		GroupName		 = CreateAHero_Weapon
		BlingUpgradeName = Upgrade_CHW21	 
	End

	CreateAHeroBling //	Corrupted Man Hammer
		NameTag			 = CreateAHero:BlingName_CM_Hammer
		DescriptionTag	 = CreateAHero:BlingDesc_CM_Hammer
		GroupName		 = CreateAHero_Weapon
		BlingUpgradeName = Upgrade_CHW22	 
	End
	CreateAHeroBling //	Corrupted Man Sword 03
		NameTag			 = CreateAHero:BlingName_CM_Sword03
		DescriptionTag	 = CreateAHero:BlingDesc_CM_Sword03
		GroupName		 = CreateAHero_Weapon
		BlingUpgradeName = Upgrade_CHW23	 
	End

	CreateAHeroBling //	Corrupted Man Sword 04
		NameTag			 = CreateAHero:BlingName_CM_Sword04
		DescriptionTag	 = CreateAHero:BlingDesc_CM_Sword04
		GroupName		 = CreateAHero_Weapon
		BlingUpgradeName = Upgrade_CHW24 
	End
	
	CreateAHeroBling //	Corrupted Man Sword 1
		NameTag			 = CreateAHero:BlingName_CMSword01
		DescriptionTag	 = CreateAHero:BlingDesc_CMSword01
		GroupName		 = CreateAHero_Weapon
		BlingUpgradeName = Upgrade_CHW25 
	End
	
	CreateAHeroBling //	Corrupted Man Sword 2
		NameTag			 = CreateAHero:BlingName_CMSword02
		DescriptionTag	 = CreateAHero:BlingDesc_CMSword02
		GroupName		 = CreateAHero_Weapon
		BlingUpgradeName = Upgrade_CHW26 
	End

	CreateAHeroBling //	Hero of the West Axe
		NameTag			 = CreateAHero:BlingName_BelthrondingSword
		DescriptionTag	 = CreateAHero:BlingDesc_BelthrondingSword
		GroupName		 = CreateAHero_Weapon
		BlingUpgradeName = Upgrade_CHW27
	End

	CreateAHeroBling //	Hero of the West Sword
		NameTag			 = CreateAHero:BlingName_MithlondBowSword
		DescriptionTag	 = CreateAHero:BlingDesc_MithlondBowSword
		GroupName		 = CreateAHero_Weapon
		BlingUpgradeName = Upgrade_CHW28
	End
	
	CreateAHeroBling // SpikedClub
		NameTag			 = CreateAHero:BlingName_SpikedClub
		DescriptionTag	 = CreateAHero:BlingDesc_SpikedClub
		GroupName		 = CreateAHero_Weapon
		BlingUpgradeName = Upgrade_CHW29
	End

	CreateAHeroBling //	MetalHammer
		NameTag			 = CreateAHero:BlingName_MetalHammer
		DescriptionTag	 = CreateAHero:BlingDesc_MetalHammer
		GroupName		 = CreateAHero_Weapon
		BlingUpgradeName = Upgrade_CHW30
	End
	
	CreateAHeroBling //	Dwarf Hammer
		NameTag			 = CreateAHero:BlingName_DwarfHammer
		DescriptionTag	 = CreateAHero:BlingDesc_DwarfHammer
		GroupName		 = CreateAHero_Weapon
		BlingUpgradeName = Upgrade_CHW31 
	End
	
	CreateAHeroBling //	Dwarf Axe 02
		NameTag			 = CreateAHero:BlingName_DwarfHammer
		DescriptionTag	 = CreateAHero:BlingDesc_DwarfHammer
		GroupName		 = CreateAHero_Weapon
		BlingUpgradeName = Upgrade_CHW32 
	End
