//-------------------------------
// Create a Hero Appearance Bling.
//-------------------------------


//-------------------------------
// Head	Gear
CreateAHeroBling // Uruk
	NameTag			 = CreateAHero:BlingName_Uruk_CHHAIR01
	DescriptionTag	 = CreateAHero:BlingDesc_Uruk_CHHAIR01
	GroupName		 = CreateAHero_Helmet
	BlingUpgradeName = Upgrade_Uruk_CHHAIR01
End

CreateAHeroBling // Uruk 
	NameTag			 = CreateAHero:BlingName_Uruk_CHH01
	DescriptionTag	 = CreateAHero:BlingDesc_Uruk_CHH01
	GroupName		 = CreateAHero_Helmet
	BlingUpgradeName = Upgrade_Uruk_CHH01
End

CreateAHeroBling // Uruk 
	NameTag			 = CreateAHero:BlingName_Uruk_CHH02
	DescriptionTag	 = CreateAHero:BlingDesc_Uruk_CHH02
	GroupName		 = CreateAHero_Helmet
	BlingUpgradeName = Upgrade_Uruk_CHH02
End

CreateAHeroBling // Uruk 
	NameTag			 = CreateAHero:BlingName_Uruk_CHH03
	DescriptionTag	 = CreateAHero:BlingDesc_Uruk_CHH03
	GroupName		 = CreateAHero_Helmet
	BlingUpgradeName = Upgrade_Uruk_CHH03
End

CreateAHeroBling // Uruk 
	NameTag			 = CreateAHero:BlingName_Uruk_CHH04
	DescriptionTag	 = CreateAHero:BlingDesc_Uruk_CHH04
	GroupName		 = CreateAHero_Helmet
	BlingUpgradeName = Upgrade_Uruk_CHH04
End

CreateAHeroBling // DWARF
	NameTag			 = CreateAHero:BlingName_DWARF_CHH01
	DescriptionTag	 = CreateAHero:BlingName_DWARF_CHH01
	GroupName		 = CreateAHero_Helmet
	BlingUpgradeName = Upgrade_DWARF_CHH01
End

CreateAHeroBling // DWARF
	NameTag			 = CreateAHero:BlingName_DWARF_CHH02
	DescriptionTag	 = CreateAHero:BlingName_DWARF_CHH02
	GroupName		 = CreateAHero_Helmet
	BlingUpgradeName = Upgrade_DWARF_CHH02
End

CreateAHeroBling // DWARF
	NameTag			 = CreateAHero:BlingName_DWARF_CHH03
	DescriptionTag	 = CreateAHero:BlingName_DWARF_CHH03
	GroupName		 = CreateAHero_Helmet
	BlingUpgradeName = Upgrade_DWARF_CHH03
End

CreateAHeroBling // DWARF
	NameTag			 = CreateAHero:BlingName_DWARF_CHH04
	DescriptionTag	 = CreateAHero:BlingName_DWARF_CHH04
	GroupName		 = CreateAHero_Helmet
	BlingUpgradeName = Upgrade_DWARF_CHH04
End

CreateAHeroBling // DWARF
	NameTag			 = CreateAHero:BlingName_DWARF_CHH05
	DescriptionTag	 = CreateAHero:BlingName_DWARF_CHH05
	GroupName		 = CreateAHero_Helmet
	BlingUpgradeName = Upgrade_DWARF_CHH05
End

CreateAHeroBling // DWARF
	NameTag			 = CreateAHero:BlingName_DWARF_CHH06
	DescriptionTag	 = CreateAHero:BlingName_DWARF_CHH06
	GroupName		 = CreateAHero_Helmet
	BlingUpgradeName = Upgrade_DWARF_CHH06
End

CreateAHeroBling // CorruptedMan 1
	NameTag			 = CreateAHero:BlingName_CorruptedMan_1_CHH01
	DescriptionTag	 = CreateAHero:BlingName_CorruptedMan_1_CHH01
	GroupName		 = CreateAHero_Helmet
	BlingUpgradeName = Upgrade_CorruptedMan_1_CHH01
End

CreateAHeroBling // CorruptedMan 1
	NameTag			 = CreateAHero:BlingName_CorruptedMan_1_CHH02
	DescriptionTag	 = CreateAHero:BlingName_CorruptedMan_1_CHH02
	GroupName		 = CreateAHero_Helmet
	BlingUpgradeName = Upgrade_CorruptedMan_1_CHH02
End

CreateAHeroBling // CorruptedMan 1
	NameTag			 = CreateAHero:BlingName_CorruptedMan_1_CHH03
	DescriptionTag	 = CreateAHero:BlingName_CorruptedMan_1_CHH03
	GroupName		 = CreateAHero_Helmet
	BlingUpgradeName = Upgrade_CorruptedMan_1_CHH03
End

CreateAHeroBling // CorruptedMan 1
	NameTag			 = CreateAHero:BlingName_CorruptedMan_1_CHH04
	DescriptionTag	 = CreateAHero:BlingName_CorruptedMan_1_CHH04
	GroupName		 = CreateAHero_Helmet
	BlingUpgradeName = Upgrade_CorruptedMan_1_CHH04
End

CreateAHeroBling // CorruptedMan 1
	NameTag			 = CreateAHero:BlingName_CorruptedMan_1_CHH05
	DescriptionTag	 = CreateAHero:BlingName_CorruptedMan_1_CHH05
	GroupName		 = CreateAHero_Helmet
	BlingUpgradeName = Upgrade_CorruptedMan_1_CHH05
End

CreateAHeroBling // CorruptedMan 1
	NameTag			 = CreateAHero:BlingName_CorruptedMan_1_CHH08
	DescriptionTag	 = CreateAHero:BlingName_CorruptedMan_1_CHH08
	GroupName		 = CreateAHero_Helmet
	BlingUpgradeName = Upgrade_CorruptedMan_1_CHH08
End

CreateAHeroBling // Captain of Gondor
	NameTag			 = CreateAHero:BlingName_CaptainOfGondor_CHH01
	DescriptionTag	 = CreateAHero:BlingName_CaptainOfGondor_CHH01
	GroupName		 = CreateAHero_Helmet
	BlingUpgradeName = Upgrade_CaptainOfGondor_CHH01
End

CreateAHeroBling // Captain of Gondor
	NameTag			 = CreateAHero:BlingName_CaptainOfGondor_CHH02
	DescriptionTag	 = CreateAHero:BlingName_CaptainOfGondor_CHH02
	GroupName		 = CreateAHero_Helmet
	BlingUpgradeName = Upgrade_CaptainOfGondor_CHH02
End

CreateAHeroBling // Captain of Gondor
	NameTag			 = CreateAHero:BlingName_CaptainOfGondor_CHH03
	DescriptionTag	 = CreateAHero:BlingName_CaptainOfGondor_CHH03
	GroupName		 = CreateAHero_Helmet
	BlingUpgradeName = Upgrade_CaptainOfGondor_CHH03
End

CreateAHeroBling // Captain of Gondor
	NameTag			 = CreateAHero:BlingName_CaptainOfGondor_CHH05
	DescriptionTag	 = CreateAHero:BlingName_CaptainOfGondor_CHH05
	GroupName		 = CreateAHero_Helmet
	BlingUpgradeName = Upgrade_CaptainOfGondor_CHH05
End

CreateAHeroBling // Captain of Gondor
	NameTag			 = CreateAHero:BlingName_CaptainOfGondor_CHH06
	DescriptionTag	 = CreateAHero:BlingName_CaptainOfGondor_CHH06
	GroupName		 = CreateAHero_Helmet
	BlingUpgradeName = Upgrade_CaptainOfGondor_CHH06
End

CreateAHeroBling // ElfArcher 
	NameTag			 = CreateAHero:BlingName_ElfArcher_CHH01
	DescriptionTag	 = CreateAHero:BlingDesc_ElfArcher_CHH01
	GroupName		 = CreateAHero_Helmet
	BlingUpgradeName = Upgrade_ELFA_CHH01
End

CreateAHeroBling // ElfArcher 
	NameTag			 = CreateAHero:BlingName_ElfArcher_CHH02
	DescriptionTag	 = CreateAHero:BlingDesc_ElfArcher_CHH02
	GroupName		 = CreateAHero_Helmet
	BlingUpgradeName = Upgrade_ELFA_CHH02
End

CreateAHeroBling // ElfArcher 
	NameTag			 = CreateAHero:BlingName_ElfArcher_CHH03
	DescriptionTag	 = CreateAHero:BlingDesc_ElfArcher_CHH03
	GroupName		 = CreateAHero_Helmet
	BlingUpgradeName = Upgrade_ELFA_CHH03
End

CreateAHeroBling // ShieldMaiden 
	NameTag			 = CreateAHero:BlingName_ShieldMaiden_CHH01
	DescriptionTag	 = CreateAHero:BlingDesc_ShieldMaiden_CHH01
	GroupName		 = CreateAHero_Helmet
	BlingUpgradeName = Upgrade_SHIM_CHH01
End

CreateAHeroBling // ShieldMaiden 
	NameTag			 = CreateAHero:BlingName_ShieldMaiden_CHH02
	DescriptionTag	 = CreateAHero:BlingDesc_ShieldMaiden_CHH02
	GroupName		 = CreateAHero_Helmet
	BlingUpgradeName = Upgrade_SHIM_CHH02
End

CreateAHeroBling // ShieldMaiden 
	NameTag			 = CreateAHero:BlingName_ShieldMaiden_CHH03
	DescriptionTag	 = CreateAHero:BlingDesc_ShieldMaiden_CHH03
	GroupName		 = CreateAHero_Helmet
	BlingUpgradeName = Upgrade_SHIM_CHH03
End

CreateAHeroBling // Wizard 
	NameTag			 = CreateAHero:BlingName_Wizard_CHH01
	DescriptionTag	 = CreateAHero:BlingDesc_Wizard_CHH01
	GroupName		 = CreateAHero_Helmet
	BlingUpgradeName = Upgrade_WIZ_CHH01
End

CreateAHeroBling // Wizard 
	NameTag			 = CreateAHero:BlingName_Wizard_CHH02
	DescriptionTag	 = CreateAHero:BlingDesc_Wizard_CHH02
	GroupName		 = CreateAHero_Helmet
	BlingUpgradeName = Upgrade_WIZ_CHH02
End
CreateAHeroBling // Wizard 
	NameTag			 = CreateAHero:BlingName_Wizard_CHH03
	DescriptionTag	 = CreateAHero:BlingDesc_Wizard_CHH03
	GroupName		 = CreateAHero_Helmet
	BlingUpgradeName = Upgrade_WIZ_CHH03
End

CreateAHeroBling // Wizard 
	NameTag			 = CreateAHero:BlingName_Wizard_CHH04
	DescriptionTag	 = CreateAHero:BlingDesc_Wizard_CHH04
	GroupName		 = CreateAHero_Helmet
	BlingUpgradeName = Upgrade_WIZ_CHH04
End

CreateAHeroBling // Wizard 
	NameTag			 = CreateAHero:BlingName_Wizard_CHH05
	DescriptionTag	 = CreateAHero:BlingDesc_Wizard_CHH05
	GroupName		 = CreateAHero_Helmet
	BlingUpgradeName = Upgrade_WIZ_CHH05
End

CreateAHeroBling // Wizard 
	NameTag			 = CreateAHero:BlingName_Wizard_CHH06
	DescriptionTag	 = CreateAHero:BlingDesc_Wizard_CHH06
	GroupName		 = CreateAHero_Helmet
	BlingUpgradeName = Upgrade_WIZ_CHH06
End

CreateAHeroBling // Wizard 
	NameTag			 = CreateAHero:BlingName_Wizard_CHH07
	DescriptionTag	 = CreateAHero:BlingDesc_Wizard_CHH07
	GroupName		 = CreateAHero_Helmet
	BlingUpgradeName = Upgrade_WIZ_CHH07
End

CreateAHeroBling // Female Elven rcher 
	NameTag			 = CreateAHero:BlingName_FemaleElvenArcher_CHH01
	DescriptionTag	 = CreateAHero:BlingDesc_FemaleElvenArcher_CHH01
	GroupName		 = CreateAHero_Helmet
	BlingUpgradeName = Upgrade_FEARCH_CHH01
End

CreateAHeroBling // Female Elven Archer 
	NameTag			 = CreateAHero:BlingName_FemaleElvenArcher_CHH02
	DescriptionTag	 = CreateAHero:BlingDesc_FemaleElvenArcher_CHH02
	GroupName		 = CreateAHero_Helmet
	BlingUpgradeName = Upgrade_FEARCH_CHH02
End

CreateAHeroBling // Female Elven rcher 
	NameTag			 = CreateAHero:BlingName_FemaleElvenArcher_CHH03
	DescriptionTag	 = CreateAHero:BlingDesc_FemaleElvenArcher_CHH03
	GroupName		 = CreateAHero_Helmet
	BlingUpgradeName = Upgrade_FEARCH_CHH03
End

CreateAHeroBling // Female Elven Archer 
	NameTag			 = CreateAHero:BlingName_FemaleElvenArcher_CHH04
	DescriptionTag	 = CreateAHero:BlingDesc_FemaleElvenArcher_CHH04
	GroupName		 = CreateAHero_Helmet
	BlingUpgradeName = Upgrade_FEARCH_CHH04
End

CreateAHeroBling // Female Elven Archer 
	NameTag			 = CreateAHero:BlingName_FemaleElvenArcher_CHH05
	DescriptionTag	 = CreateAHero:BlingDesc_FemaleElvenArcher_CHH05
	GroupName		 = CreateAHero_Helmet
	BlingUpgradeName = Upgrade_FEARCH_CHH05
End

CreateAHeroBling // Female Elven Archer 
	NameTag			 = CreateAHero:BlingName_FemaleElvenArcher_CHH06
	DescriptionTag	 = CreateAHero:BlingDesc_FemaleElvenArcher_CHH06
	GroupName		 = CreateAHero_Helmet
	BlingUpgradeName = Upgrade_FEARCH_CHH06
End

CreateAHeroBling // TROLL 
	NameTag			 = CreateAHero:BlingName_TRLL_CHH01
	DescriptionTag	 = CreateAHero:BlingDesc_TRLL_CHH01
	GroupName		 = CreateAHero_Helmet
	BlingUpgradeName = Upgrade_TRLL_CHH01
End

CreateAHeroBling // TROLL 
	NameTag			 = CreateAHero:BlingName_TRLL_CHH02
	DescriptionTag	 = CreateAHero:BlingDesc_TRLL_CHH02
	GroupName		 = CreateAHero_Helmet
	BlingUpgradeName = Upgrade_TRLL_CHH02
End

CreateAHeroBling // TROLL 
	NameTag			 = CreateAHero:BlingName_TRLL_CHH03
	DescriptionTag	 = CreateAHero:BlingDesc_TRLL_CHH03
	GroupName		 = CreateAHero_Helmet
	BlingUpgradeName = Upgrade_TRLL_CHH03
End

CreateAHeroBling // TROLL 
	NameTag			 = CreateAHero:BlingName_TRLL_CHH04
	DescriptionTag	 = CreateAHero:BlingDesc_TRLL_CHH04
	GroupName		 = CreateAHero_Helmet
	BlingUpgradeName = Upgrade_TRLL_CHH04
End

CreateAHeroBling // TROLL 
	NameTag			 = CreateAHero:BlingName_TRLL_CHH05
	DescriptionTag	 = CreateAHero:BlingDesc_TRLL_CHH05
	GroupName		 = CreateAHero_Helmet
	BlingUpgradeName = Upgrade_TRLL_CHH05
End

CreateAHeroBling // TROLL 
	NameTag			 = CreateAHero:BlingName_TRLL_CHH06
	DescriptionTag	 = CreateAHero:BlingDesc_TRLL_CHH06
	GroupName		 = CreateAHero_Helmet
	BlingUpgradeName = Upgrade_TRLL_CHH06
End

CreateAHeroBling // TROLL 
	NameTag			 = CreateAHero:BlingName_TRLL_CHH07
	DescriptionTag	 = CreateAHero:BlingDesc_TRLL_CHH07
	GroupName		 = CreateAHero_Helmet
	BlingUpgradeName = Upgrade_TRLL_CHH07
End

CreateAHeroBling // TROLL 
	NameTag			 = CreateAHero:BlingName_TRLL_CHH08
	DescriptionTag	 = CreateAHero:BlingDesc_TRLL_CHH08
	GroupName		 = CreateAHero_Helmet
	BlingUpgradeName = Upgrade_TRLL_CHH08
End

CreateAHeroBling // ORC 
	NameTag			 = CreateAHero:BlingName_ORC_CHH01
	DescriptionTag	 = CreateAHero:BlingDesc_ORC_CHH01
	GroupName		 = CreateAHero_Helmet
	BlingUpgradeName = Upgrade_ORC_CHH01
End

CreateAHeroBling // ORC 
	NameTag			 = CreateAHero:BlingName_ORC_CHH02
	DescriptionTag	 = CreateAHero:BlingDesc_ORC_CHH02
	GroupName		 = CreateAHero_Helmet
	BlingUpgradeName = Upgrade_ORC_CHH02
End

//-------------------------------
// Shoulder	Plates
CreateAHeroBling // Uruk
	NameTag			 = CreateAHero:BlingName_Uruk_CHSP01
	DescriptionTag	 = CreateAHero:BlingDesc_Uruk_CHSP01
	GroupName		 = CreateAHero_ShoulderPlates
	BlingUpgradeName = Upgrade_Uruk_CHSP01
End

CreateAHeroBling // Uruk 
	NameTag			 = CreateAHero:BlingName_Uruk_CHSP02
	DescriptionTag	 = CreateAHero:BlingDesc_Uruk_CHSP02
	GroupName		 = CreateAHero_ShoulderPlates
	BlingUpgradeName = Upgrade_Uruk_CHSP02
End

CreateAHeroBling // Uruk
	NameTag			 = CreateAHero:BlingName_Uruk_CHSP03
	DescriptionTag	 = CreateAHero:BlingDesc_Uruk_CHSP03
	GroupName		 = CreateAHero_ShoulderPlates
	BlingUpgradeName = Upgrade_Uruk_CHSP03
End

CreateAHeroBling // DWARF
	NameTag			 = CreateAHero:BlingName_DWARF_CHSP01
	DescriptionTag	 = CreateAHero:BlingDesc_DWARF_CHSP01
	GroupName		 = CreateAHero_ShoulderPlates
	BlingUpgradeName = Upgrade_DWARF_CHSP01
End

CreateAHeroBling // DWARF 
	NameTag			 = CreateAHero:BlingName_DWARF_CHSP02
	DescriptionTag	 = CreateAHero:BlingDesc_DWARF_CHSP02
	GroupName		 = CreateAHero_ShoulderPlates
	BlingUpgradeName = Upgrade_DWARF_CHSP02
End

CreateAHeroBling // DWARF
	NameTag			 = CreateAHero:BlingName_DWARF_CHSP03
	DescriptionTag	 = CreateAHero:BlingDesc_DWARF_CHSP03
	GroupName		 = CreateAHero_ShoulderPlates
	BlingUpgradeName = Upgrade_DWARF_CHSP03
End

CreateAHeroBling // DWARF 
	NameTag			 = CreateAHero:BlingName_DWARF_CHSP04
	DescriptionTag	 = CreateAHero:BlingDesc_DWARF_CHSP04
	GroupName		 = CreateAHero_ShoulderPlates
	BlingUpgradeName = Upgrade_DWARF_CHSP04
End

CreateAHeroBling // DWARF
	NameTag			 = CreateAHero:BlingName_DWARF_CHSP05
	DescriptionTag	 = CreateAHero:BlingDesc_DWARF_CHSP05
	GroupName		 = CreateAHero_ShoulderPlates
	BlingUpgradeName = Upgrade_DWARF_CHSP05
End

CreateAHeroBling // DWARF
	NameTag			 = CreateAHero:BlingName_DWARF_CHSP06
	DescriptionTag	 = CreateAHero:BlingDesc_DWARF_CHSP06
	GroupName		 = CreateAHero_ShoulderPlates
	BlingUpgradeName = Upgrade_DWARF_CHSP06
End

CreateAHeroBling // CorruptedMan 1
	NameTag		 = CreateAHero:BlingName_CorruptedMan_1_CHSP01
	DescriptionTag	 = CreateAHero:BlingDesc_CorruptedMan_1_CHSP01
	GroupName		 = CreateAHero_ShoulderPlates
	BlingUpgradeName = Upgrade_CorruptedMan_1_CHSP01
End

CreateAHeroBling // CorruptedMan 1
	NameTag		 = CreateAHero:BlingName_CorruptedMan_1_CHSP02
	DescriptionTag	 = CreateAHero:BlingDesc_CorruptedMan_1_CHSP02
	GroupName		 = CreateAHero_ShoulderPlates
	BlingUpgradeName = Upgrade_CorruptedMan_1_CHSP02
End

CreateAHeroBling // CorruptedMan 1 *****Special linked to Body
	NameTag		 = CreateAHero:BlingName_CorruptedMan_1_CHSP03
	DescriptionTag	 = CreateAHero:BlingDesc_CorruptedMan_1_CHSP03
	GroupName		 = CreateAHero_ShoulderPlates
	BlingUpgradeName = Upgrade_CorruptedMan_1_CHSP03
End

CreateAHeroBling // CorruptedMan 1 *****Special linked to Body
	NameTag		 = CreateAHero:BlingName_CorruptedMan_1_CHSP04
	DescriptionTag	 = CreateAHero:BlingDesc_CorruptedMan_1_CHSP04
	GroupName		 = CreateAHero_ShoulderPlates
	BlingUpgradeName = Upgrade_CorruptedMan_1_CHSP04
End

CreateAHeroBling // CorruptedMan 1
	NameTag		 = CreateAHero:BlingName_CorruptedMan_1_CHSP07
	DescriptionTag	 = CreateAHero:BlingDesc_CorruptedMan_1_CHSP07
	GroupName		 = CreateAHero_ShoulderPlates
	BlingUpgradeName = Upgrade_CorruptedMan_1_CHSP07
End

CreateAHeroBling // Captain of Gondor
	NameTag		 = CreateAHero:BlingName_CaptainOfGondor_CHSP01
	DescriptionTag	 = CreateAHero:BlingDesc_CaptainOfGondor_CHSP01
	GroupName		 = CreateAHero_ShoulderPlates
	BlingUpgradeName = Upgrade_CaptainOfGondor_CHSP01
End

CreateAHeroBling // Captain of Gondor
	NameTag		 = CreateAHero:BlingName_CaptainOfGondor_CHSP02
	DescriptionTag	 = CreateAHero:BlingDesc_CaptainOfGondor_CHSP02
	GroupName		 = CreateAHero_ShoulderPlates
	BlingUpgradeName = Upgrade_CaptainOfGondor_CHSP02
End

CreateAHeroBling // Captain of Gondor
	NameTag		 = CreateAHero:BlingName_CaptainOfGondor_CHSP04
	DescriptionTag	 = CreateAHero:BlingDesc_CaptainOfGondor_CHSP04
	GroupName		 = CreateAHero_ShoulderPlates
	BlingUpgradeName = Upgrade_CaptainOfGondor_CHSP04
End

CreateAHeroBling // Captain of Gondor
	NameTag		 = CreateAHero:BlingName_CaptainOfGondor_CHSP05
	DescriptionTag	 = CreateAHero:BlingDesc_CaptainOfGondor_CHSP05
	GroupName		 = CreateAHero_ShoulderPlates
	BlingUpgradeName = Upgrade_CaptainOfGondor_CHSP05
End

CreateAHeroBling // ElfArcher
	NameTag			 = CreateAHero:BlingName_ElfArcher_CHSP01
	DescriptionTag	 = CreateAHero:BlingDesc_ElfArcher_CHSP01
	GroupName		 = CreateAHero_ShoulderPlates
	BlingUpgradeName = Upgrade_ELFA_CHSP01
End

CreateAHeroBling // ElfArcher 
	NameTag			 = CreateAHero:BlingName_ElfArcher_CHSP02
	DescriptionTag	 = CreateAHero:BlingDesc_ElfArcher_CHSP02
	GroupName		 = CreateAHero_ShoulderPlates
	BlingUpgradeName = Upgrade_ELFA_CHSP02
End

CreateAHeroBling // ElfArcher 
	NameTag			 = CreateAHero:BlingName_ElfArcher_CHSP03
	DescriptionTag	 = CreateAHero:BlingDesc_ElfArcher_CHSP03
	GroupName		 = CreateAHero_ShoulderPlates
	BlingUpgradeName = Upgrade_ELFA_CHSP03
End

CreateAHeroBling // ElfArcher 
	NameTag			 = CreateAHero:BlingName_ElfArcher_CHSP04
	DescriptionTag	 = CreateAHero:BlingDesc_ElfArcher_CHSP04
	GroupName		 = CreateAHero_ShoulderPlates
	BlingUpgradeName = Upgrade_ELFA_CHSP04
End

CreateAHeroBling // ShieldMaiden
	NameTag			 = CreateAHero:BlingName_ShieldMaiden_CHSP01
	DescriptionTag	 = CreateAHero:BlingDesc_ShieldMaiden_CHSP01
	GroupName		 = CreateAHero_ShoulderPlates
	BlingUpgradeName = Upgrade_SHIM_CHSP01
End

CreateAHeroBling // ShieldMaiden 
	NameTag			 = CreateAHero:BlingName_ShieldMaiden_CHSP02
	DescriptionTag	 = CreateAHero:BlingDesc_ShieldMaiden_CHSP02
	GroupName		 = CreateAHero_ShoulderPlates
	BlingUpgradeName = Upgrade_SHIM_CHSP02
End

CreateAHeroBling // ShieldMaiden 
	NameTag			 = CreateAHero:BlingName_ShieldMaiden_CHSP03
	DescriptionTag	 = CreateAHero:BlingDesc_ShieldMaiden_CHSP03
	GroupName		 = CreateAHero_ShoulderPlates
	BlingUpgradeName = Upgrade_SHIM_CHSP03
End

CreateAHeroBling // Female Elven Archer
	NameTag			 = CreateAHero:BlingName_FemaleElvenArcher_CHSP01
	DescriptionTag	 = CreateAHero:BlingDesc_FemaleElvenArcher_CHSP01
	GroupName		 = CreateAHero_ShoulderPlates
	BlingUpgradeName = Upgrade_FEARCH_CHSP01
End

CreateAHeroBling // Female Elven Archer 
	NameTag			 = CreateAHero:BlingName_FemaleElvenArcher_CHSP02
	DescriptionTag	 = CreateAHero:BlingDesc_FemaleElvenArcher_CHSP02
	GroupName		 = CreateAHero_ShoulderPlates
	BlingUpgradeName = Upgrade_FEARCH_CHSP02
End

CreateAHeroBling // Female Elven Archer
	NameTag			 = CreateAHero:BlingName_FemaleElvenArcher_CHSP03
	DescriptionTag	 = CreateAHero:BlingDesc_FemaleElvenArcher_CHSP03
	GroupName		 = CreateAHero_ShoulderPlates
	BlingUpgradeName = Upgrade_FEARCH_CHSP03
End

CreateAHeroBling // Female Elven Archer 
	NameTag			 = CreateAHero:BlingName_FemaleElvenArcher_CHSP04
	DescriptionTag	 = CreateAHero:BlingDesc_FemaleElvenArcher_CHSP04
	GroupName		 = CreateAHero_ShoulderPlates
	BlingUpgradeName = Upgrade_FEARCH_CHSP04
End

CreateAHeroBling // Female Elven Archer 
	NameTag			 = CreateAHero:BlingName_FemaleElvenArcher_CHSP05
	DescriptionTag	 = CreateAHero:BlingDesc_FemaleElvenArcher_CHSP05
	GroupName		 = CreateAHero_ShoulderPlates
	BlingUpgradeName = Upgrade_FEARCH_CHSP05
End

CreateAHeroBling // Female Elven Archer 
	NameTag			 = CreateAHero:BlingName_FemaleElvenArcher_CHSP06
	DescriptionTag	 = CreateAHero:BlingDesc_FemaleElvenArcher_CHSP06
	GroupName		 = CreateAHero_ShoulderPlates
	BlingUpgradeName = Upgrade_FEARCH_CHSP06
End

CreateAHeroBling // Wizard
	NameTag			 = CreateAHero:BlingName_Wizard_CHSP01
	DescriptionTag	 = CreateAHero:BlingDesc_Wizard_CHSP01
	GroupName		 = CreateAHero_ShoulderPlates
	BlingUpgradeName = Upgrade_WIZ_CHSP01
End

CreateAHeroBling // Wizard 
	NameTag			 = CreateAHero:BlingName_Wizard_CHSP02
	DescriptionTag	 = CreateAHero:BlingDesc_Wizard_CHSP02
	GroupName		 = CreateAHero_ShoulderPlates
	BlingUpgradeName = Upgrade_WIZ_CHSP02
End

CreateAHeroBling // TROLL
	NameTag			 = CreateAHero:BlingName_TRLL_CHSP01
	DescriptionTag	 = CreateAHero:BlingDesc_TRLL_CHSP01
	GroupName		 = CreateAHero_ShoulderPlates
	BlingUpgradeName = Upgrade_TRLL_CHSP01
End

CreateAHeroBling // TROLL 
	NameTag			 = CreateAHero:BlingName_TRLL_CHSP02
	DescriptionTag	 = CreateAHero:BlingDesc_TRLL_CHSP02
	GroupName		 = CreateAHero_ShoulderPlates
	BlingUpgradeName = Upgrade_TRLL_CHSP02
End

CreateAHeroBling // TROLL
	NameTag			 = CreateAHero:BlingName_TRLL_CHSP03
	DescriptionTag	 = CreateAHero:BlingDesc_TRLL_CHSP03
	GroupName		 = CreateAHero_ShoulderPlates
	BlingUpgradeName = Upgrade_TRLL_CHSP03
End

CreateAHeroBling // TROLL
	NameTag			 = CreateAHero:BlingName_TRLL_CHSP04
	DescriptionTag	 = CreateAHero:BlingDesc_TRLL_CHSP04
	GroupName		 = CreateAHero_ShoulderPlates
	BlingUpgradeName = Upgrade_TRLL_CHSP04
End

CreateAHeroBling // TROLL
	NameTag			 = CreateAHero:BlingName_TRLL_CHSP05
	DescriptionTag	 = CreateAHero:BlingDesc_TRLL_CHSP05
	GroupName		 = CreateAHero_ShoulderPlates
	BlingUpgradeName = Upgrade_TRLL_CHSP05
End

CreateAHeroBling // TROLL
	NameTag			 = CreateAHero:BlingName_TRLL_CHSP06
	DescriptionTag	 = CreateAHero:BlingDesc_TRLL_CHSP06
	GroupName		 = CreateAHero_ShoulderPlates
	BlingUpgradeName = Upgrade_TRLL_CHSP06
End

CreateAHeroBling // ORC
	NameTag			 = CreateAHero:BlingName_ORC_CHSP01
	DescriptionTag	 = CreateAHero:BlingDesc_ORC_CHSP01
	GroupName		 = CreateAHero_ShoulderPlates
	BlingUpgradeName = Upgrade_ORC_CHSP01
End

CreateAHeroBling // ORC
	NameTag			 = CreateAHero:BlingName_ORC_CHSP02
	DescriptionTag	 = CreateAHero:BlingDesc_ORC_CHSP02
	GroupName		 = CreateAHero_ShoulderPlates
	BlingUpgradeName = Upgrade_ORC_CHSP02
End

//-------------------------------
// Gauntlets
CreateAHeroBling // Uruk
	NameTag			 = CreateAHero:BlingName_Uruk_CHG01
	DescriptionTag	 = CreateAHero:BlingDesc_Uruk_CHG01
	GroupName		 = CreateAHero_Gauntlets
	BlingUpgradeName = Upgrade_Uruk_CHG01
End

CreateAHeroBling // Uruk
	NameTag			 = CreateAHero:BlingName_Uruk_CHG02
	DescriptionTag	 = CreateAHero:BlingDesc_Uruk_CHG02
	GroupName		 = CreateAHero_Gauntlets
	BlingUpgradeName = Upgrade_Uruk_CHG02
End

CreateAHeroBling // Uruk
	NameTag			 = CreateAHero:BlingName_Uruk_CHG03
	DescriptionTag	 = CreateAHero:BlingDesc_Uruk_CHG03
	GroupName		 = CreateAHero_Gauntlets
	BlingUpgradeName = Upgrade_Uruk_CHG03
End

CreateAHeroBling // CorruptedMan 1
	NameTag			 = CreateAHero:BlingName_CorruptedMan_1_CHG01
	DescriptionTag	 = CreateAHero:BlingDesc_CorruptedMan_1_CHG01
	GroupName		 = CreateAHero_Gauntlets
	BlingUpgradeName = Upgrade_CorruptedMan_1_CHG01
End

CreateAHeroBling // CorruptedMan 1
	NameTag			 = CreateAHero:BlingName_CorruptedMan_1_CHG02
	DescriptionTag	 = CreateAHero:BlingDesc_CorruptedMan_1_CHG02
	GroupName		 = CreateAHero_Gauntlets
	BlingUpgradeName = Upgrade_CorruptedMan_1_CHG02
End

CreateAHeroBling // CorruptedMan 1
	NameTag			 = CreateAHero:BlingName_CorruptedMan_1_CHG03
	DescriptionTag	 = CreateAHero:BlingDesc_CorruptedMan_1_CHG03
	GroupName		 = CreateAHero_Gauntlets
	BlingUpgradeName = Upgrade_CorruptedMan_1_CHG03
End

CreateAHeroBling // Captain of Gondor
	NameTag			 = CreateAHero:BlingName_CaptainOfGondor_CHG01
	DescriptionTag	 = CreateAHero:BlingDesc_CaptainOfGondor_CHG01
	GroupName		 = CreateAHero_Gauntlets
	BlingUpgradeName = Upgrade_CaptainOfGondor_CHG01
End

CreateAHeroBling // Captain of Gondor
	NameTag			 = CreateAHero:BlingName_CaptainOfGondor_CHG02
	DescriptionTag	 = CreateAHero:BlingDesc_CaptainOfGondor_CHG02
	GroupName		 = CreateAHero_Gauntlets
	BlingUpgradeName = Upgrade_CaptainOfGondor_CHG02
End

CreateAHeroBling // Captain of Gondor
	NameTag			 = CreateAHero:BlingName_CaptainOfGondor_CHG03
	DescriptionTag	 = CreateAHero:BlingDesc_CaptainOfGondor_CHG03
	GroupName		 = CreateAHero_Gauntlets
	BlingUpgradeName = Upgrade_CaptainOfGondor_CHG03
End

CreateAHeroBling // Captain of Gondor
	NameTag			 = CreateAHero:BlingName_CaptainOfGondor_CHG04
	DescriptionTag	 = CreateAHero:BlingDesc_CaptainOfGondor_CHG04
	GroupName		 = CreateAHero_Gauntlets
	BlingUpgradeName = Upgrade_CaptainOfGondor_CHG04
End

CreateAHeroBling // Captain of Gondor
	NameTag			 = CreateAHero:BlingName_CaptainOfGondor_CHG05
	DescriptionTag	 = CreateAHero:BlingDesc_CaptainOfGondor_CHG05
	GroupName		 = CreateAHero_Gauntlets
	BlingUpgradeName = Upgrade_CaptainOfGondor_CHG05
End

CreateAHeroBling // ElfArcher
	NameTag			 = CreateAHero:BlingName_ElfArcher_CHG01
	DescriptionTag	 = CreateAHero:BlingDesc_ElfArcher_CHG01
	GroupName		 = CreateAHero_Gauntlets
	BlingUpgradeName = Upgrade_ELFA_CHG01
End

CreateAHeroBling // ElfArcher
	NameTag			 = CreateAHero:BlingName_ElfArcher_CHG02
	DescriptionTag	 = CreateAHero:BlingDesc_ElfArcher_CHG02
	GroupName		 = CreateAHero_Gauntlets
	BlingUpgradeName = Upgrade_ELFA_CHG02
End

CreateAHeroBling // ElfArcher
	NameTag			 = CreateAHero:BlingName_ElfArcher_CHG03
	DescriptionTag	 = CreateAHero:BlingDesc_ElfArcher_CHG03
	GroupName		 = CreateAHero_Gauntlets
	BlingUpgradeName = Upgrade_ELFA_CHG03
End

CreateAHeroBling // ElfArcher
	NameTag			 = CreateAHero:BlingName_ElfArcher_CHG04
	DescriptionTag	 = CreateAHero:BlingDesc_ElfArcher_CHG04
	GroupName		 = CreateAHero_Gauntlets
	BlingUpgradeName = Upgrade_ELFA_CHG04
End

CreateAHeroBling // ShieldMaiden
	NameTag			 = CreateAHero:BlingName_ShieldMaiden_CHG01
	DescriptionTag	 = CreateAHero:BlingDesc_ShieldMaiden_CHG01
	GroupName		 = CreateAHero_Gauntlets
	BlingUpgradeName = Upgrade_SHIM_CHG01
End

CreateAHeroBling // ShieldMaiden
	NameTag			 = CreateAHero:BlingName_ShieldMaiden_CHG02
	DescriptionTag	 = CreateAHero:BlingDesc_ShieldMaiden_CHG02
	GroupName		 = CreateAHero_Gauntlets
	BlingUpgradeName = Upgrade_SHIM_CHG02
End

CreateAHeroBling // ShieldMaiden
	NameTag			 = CreateAHero:BlingName_ShieldMaiden_CHG03
	DescriptionTag	 = CreateAHero:BlingDesc_ShieldMaiden_CHG03
	GroupName		 = CreateAHero_Gauntlets
	BlingUpgradeName = Upgrade_SHIM_CHG03
End

CreateAHeroBling // Female Elven Archer
	NameTag			 = CreateAHero:BlingName_FemaleElvenArcher_CHG01
	DescriptionTag	 = CreateAHero:BlingDesc_FemaleElvenArcher_CHG01
	GroupName		 = CreateAHero_Gauntlets
	BlingUpgradeName = Upgrade_FEARCH_CHG01
End

CreateAHeroBling // Female Elven Archer
	NameTag			 = CreateAHero:BlingName_FemaleElvenArcher_CHG02
	DescriptionTag	 = CreateAHero:BlingDesc_FemaleElvenArcher_CHG02
	GroupName		 = CreateAHero_Gauntlets
	BlingUpgradeName = Upgrade_FEARCH_CHG02
End

CreateAHeroBling // Female Elven Archer
	NameTag			 = CreateAHero:BlingName_FemaleElvenArcher_CHG03
	DescriptionTag	 = CreateAHero:BlingDesc_FemaleElvenArcher_CHG03
	GroupName		 = CreateAHero_Gauntlets
	BlingUpgradeName = Upgrade_FEARCH_CHG03
End

CreateAHeroBling // Female Elven Archer
	NameTag			 = CreateAHero:BlingName_FemaleElvenArcher_CHG04
	DescriptionTag	 = CreateAHero:BlingDesc_FemaleElvenArcher_CHG04
	GroupName		 = CreateAHero_Gauntlets
	BlingUpgradeName = Upgrade_FEARCH_CHG04
End

CreateAHeroBling // Female Elven Archer
	NameTag			 = CreateAHero:BlingName_FemaleElvenArcher_CHG05
	DescriptionTag	 = CreateAHero:BlingDesc_FemaleElvenArcher_CHG05
	GroupName		 = CreateAHero_Gauntlets
	BlingUpgradeName = Upgrade_FEARCH_CHG05
End

CreateAHeroBling // Female Elven Archer
	NameTag			 = CreateAHero:BlingName_FemaleElvenArcher_CHG06
	DescriptionTag	 = CreateAHero:BlingDesc_FemaleElvenArcher_CHG06
	GroupName		 = CreateAHero_Gauntlets
	BlingUpgradeName = Upgrade_FEARCH_CHG06
End

CreateAHeroBling // TROLL
	NameTag			 = CreateAHero:BlingName_TRLL_CHG01
	DescriptionTag	 = CreateAHero:BlingDesc_TRLL_CHG01
	GroupName		 = CreateAHero_Gauntlets
	BlingUpgradeName = Upgrade_TRLL_CHG01
End

CreateAHeroBling // TROLL
	NameTag			 = CreateAHero:BlingName_TRLL_CHG02
	DescriptionTag	 = CreateAHero:BlingDesc_TRLL_CHG02
	GroupName		 = CreateAHero_Gauntlets
	BlingUpgradeName = Upgrade_TRLL_CHG02
End

CreateAHeroBling // TROLL
	NameTag			 = CreateAHero:BlingName_TRLL_CHG03
	DescriptionTag	 = CreateAHero:BlingDesc_TRLL_CHG03
	GroupName		 = CreateAHero_Gauntlets
	BlingUpgradeName = Upgrade_TRLL_CHG03
End

CreateAHeroBling // TROLL
	NameTag			 = CreateAHero:BlingName_TRLL_CHG04
	DescriptionTag	 = CreateAHero:BlingDesc_TRLL_CHG04
	GroupName		 = CreateAHero_Gauntlets
	BlingUpgradeName = Upgrade_TRLL_CHG04
End

CreateAHeroBling // TROLL
	NameTag			 = CreateAHero:BlingName_TRLL_CHG05
	DescriptionTag	 = CreateAHero:BlingDesc_TRLL_CHG05
	GroupName		 = CreateAHero_Gauntlets
	BlingUpgradeName = Upgrade_TRLL_CHG05
End

CreateAHeroBling // TROLL
	NameTag			 = CreateAHero:BlingName_TRLL_CHG06
	DescriptionTag	 = CreateAHero:BlingDesc_TRLL_CHG06
	GroupName		 = CreateAHero_Gauntlets
	BlingUpgradeName = Upgrade_TRLL_CHG06
End

CreateAHeroBling // TROLL
	NameTag			 = CreateAHero:BlingName_TRLL_CHG07
	DescriptionTag	 = CreateAHero:BlingDesc_TRLL_CHG07
	GroupName		 = CreateAHero_Gauntlets
	BlingUpgradeName = Upgrade_TRLL_CHG07
End

CreateAHeroBling // TROLL
	NameTag			 = CreateAHero:BlingName_TRLL_CHG08
	DescriptionTag	 = CreateAHero:BlingDesc_TRLL_CHG08
	GroupName		 = CreateAHero_Gauntlets
	BlingUpgradeName = Upgrade_TRLL_CHG08
End

CreateAHeroBling // TROLL
	NameTag			 = CreateAHero:BlingName_TRLL_CHG09
	DescriptionTag	 = CreateAHero:BlingDesc_TRLL_CHG09
	GroupName		 = CreateAHero_Gauntlets
	BlingUpgradeName = Upgrade_TRLL_CHG09
End

CreateAHeroBling // TROLL
	NameTag			 = CreateAHero:BlingName_TRLL_CHG10
	DescriptionTag	 = CreateAHero:BlingDesc_TRLL_CHG10
	GroupName		 = CreateAHero_Gauntlets
	BlingUpgradeName = Upgrade_TRLL_CHG10
End

CreateAHeroBling // DWARF
	NameTag			 = CreateAHero:BlingName_DWARF_CHG01
	DescriptionTag	 = CreateAHero:BlingDesc_DWARF_CHG01
	GroupName		 = CreateAHero_Gauntlets
	BlingUpgradeName = Upgrade_DWARF_CHG01
End

CreateAHeroBling // DWARF
	NameTag			 = CreateAHero:BlingName_DWARF_CHG02
	DescriptionTag	 = CreateAHero:BlingDesc_DWARF_CHG02
	GroupName		 = CreateAHero_Gauntlets
	BlingUpgradeName = Upgrade_DWARF_CHG02
End

CreateAHeroBling // DWARF
	NameTag			 = CreateAHero:BlingName_DWARF_CHG03
	DescriptionTag	 = CreateAHero:BlingDesc_DWARF_CHG03
	GroupName		 = CreateAHero_Gauntlets
	BlingUpgradeName = Upgrade_DWARF_CHG03
End

CreateAHeroBling // DWARF
	NameTag			 = CreateAHero:BlingName_DWARF_CHG04
	DescriptionTag	 = CreateAHero:BlingDesc_DWARF_CHG04
	GroupName		 = CreateAHero_Gauntlets
	BlingUpgradeName = Upgrade_DWARF_CHG04
End

CreateAHeroBling // ORC
	NameTag			 = CreateAHero:BlingName_ORC_CHG01
	DescriptionTag	 = CreateAHero:BlingDesc_ORC_CHG01
	GroupName		 = CreateAHero_Gauntlets
	BlingUpgradeName = Upgrade_ORC_CHG01
End

CreateAHeroBling // ORC
	NameTag			 = CreateAHero:BlingName_ORC_CHG02
	DescriptionTag	 = CreateAHero:BlingDesc_ORC_CHG02
	GroupName		 = CreateAHero_Gauntlets
	BlingUpgradeName = Upgrade_ORC_CHG02
End
//-------------------------------
// Shield
CreateAHeroBling 
	NameTag			 = CreateAHero:BlingName_Uruk_CHS01
	DescriptionTag	 = CreateAHero:BlingName_Uruk_CHS01
	GroupName		 = CreateAHero_Shield
	BlingUpgradeName = Upgrade_Uruk_CHS01
End

CreateAHeroBling 
	NameTag			 = CreateAHero:BlingName_Uruk_CHS02
	DescriptionTag	 = CreateAHero:BlingName_Uruk_CHS02
	GroupName		 = CreateAHero_Shield
	BlingUpgradeName = Upgrade_Uruk_CHS02
End

CreateAHeroBling 
	NameTag			 = CreateAHero:BlingName_Uruk_CHS03
	DescriptionTag	 = CreateAHero:BlingName_Uruk_CHS03
	GroupName		 = CreateAHero_Shield
	BlingUpgradeName = Upgrade_Uruk_CHS03
End

CreateAHeroBling 
	NameTag			 = CreateAHero:BlingName_Uruk_CHS04
	DescriptionTag	 = CreateAHero:BlingName_Uruk_CHS04
	GroupName		 = CreateAHero_Shield
	BlingUpgradeName = Upgrade_Uruk_CHS04
End

CreateAHeroBling 
	NameTag			 = CreateAHero:BlingName_CAPG_CHS01
	DescriptionTag	 = CreateAHero:BlingName_CAPG_CHS01
	GroupName		 = CreateAHero_Shield
	BlingUpgradeName = Upgrade_CAPG_CHS01
End

CreateAHeroBling 
	NameTag			 = CreateAHero:BlingName_CAPG_CHS02
	DescriptionTag	 = CreateAHero:BlingName_CAPG_CHS02
	GroupName		 = CreateAHero_Shield
	BlingUpgradeName = Upgrade_CAPG_CHS02
End

CreateAHeroBling 
	NameTag			 = CreateAHero:BlingName_CAPG_CHS03
	DescriptionTag	 = CreateAHero:BlingName_CAPG_CHS03
	GroupName		 = CreateAHero_Shield
	BlingUpgradeName = Upgrade_CAPG_CHS03
End

CreateAHeroBling 
	NameTag			 = CreateAHero:BlingName_CAPG_CHS04
	DescriptionTag	 = CreateAHero:BlingName_CAPG_CHS04
	GroupName		 = CreateAHero_Shield
	BlingUpgradeName = Upgrade_CAPG_CHS04
End
//-------------------------------
// Boots
CreateAHeroBling // Uruk
	NameTag			 = CreateAHero:BlingName_Uruk_CHB01
	DescriptionTag	 = CreateAHero:BlingName_Uruk_CHB01
	GroupName		 = CreateAHero_Boots
	BlingUpgradeName = Upgrade_Uruk_CHB01
End

CreateAHeroBling // Uruk
	NameTag			 = CreateAHero:BlingName_Uruk_CHB02
	DescriptionTag	 = CreateAHero:BlingName_Uruk_CHB02
	GroupName		 = CreateAHero_Boots
	BlingUpgradeName = Upgrade_Uruk_CHB02
End

CreateAHeroBling // Uruk
	NameTag			 = CreateAHero:BlingName_Uruk_CHB03
	DescriptionTag	 = CreateAHero:BlingName_Uruk_CHB03
	GroupName		 = CreateAHero_Boots
	BlingUpgradeName = Upgrade_Uruk_CHB03
End

CreateAHeroBling // CorruptedMan 1
	NameTag			 = CreateAHero:BlingName_CorruptedMan_1_CHB01
	DescriptionTag	 = CreateAHero:BlingName_CorruptedMan_1_CHB01
	GroupName		 = CreateAHero_Boots
	BlingUpgradeName = Upgrade_CorruptedMan_1_CHB01
End

CreateAHeroBling // CorruptedMan 1
	NameTag			 = CreateAHero:BlingName_CorruptedMan_1_CHB02
	DescriptionTag	 = CreateAHero:BlingName_CorruptedMan_1_CHB02
	GroupName		 = CreateAHero_Boots
	BlingUpgradeName = Upgrade_CorruptedMan_1_CHB02
End

CreateAHeroBling // CorruptedMan 1
	NameTag			 = CreateAHero:BlingName_CorruptedMan_1_CHB03
	DescriptionTag	 = CreateAHero:BlingName_CorruptedMan_1_CHB03
	GroupName		 = CreateAHero_Boots
	BlingUpgradeName = Upgrade_CorruptedMan_1_CHB03
End

CreateAHeroBling // Captain of Gondor
	NameTag			 = CreateAHero:BlingName_CaptainOfGondor_CHB01
	DescriptionTag	 = CreateAHero:BlingName_CaptainOfGondor_CHB01
	GroupName		 = CreateAHero_Boots
	BlingUpgradeName = Upgrade_CaptainOfGondor_CHB01
End

CreateAHeroBling // Captain of Gondor
	NameTag			 = CreateAHero:BlingName_CaptainOfGondor_CHB02
	DescriptionTag	 = CreateAHero:BlingName_CaptainOfGondor_CHB02
	GroupName		 = CreateAHero_Boots
	BlingUpgradeName = Upgrade_CaptainOfGondor_CHB02
End

CreateAHeroBling // Captain of Gondor
	NameTag			 = CreateAHero:BlingName_CaptainOfGondor_CHB03
	DescriptionTag	 = CreateAHero:BlingName_CaptainOfGondor_CHB03
	GroupName		 = CreateAHero_Boots
	BlingUpgradeName = Upgrade_CaptainOfGondor_CHB03
End

CreateAHeroBling // Captain of Gondor
	NameTag			 = CreateAHero:BlingName_CaptainOfGondor_CHB04
	DescriptionTag	 = CreateAHero:BlingName_CaptainOfGondor_CHB04
	GroupName		 = CreateAHero_Boots
	BlingUpgradeName = Upgrade_CaptainOfGondor_CHB04
End

CreateAHeroBling // Captain of Gondor
	NameTag			 = CreateAHero:BlingName_CaptainOfGondor_CHB05
	DescriptionTag	 = CreateAHero:BlingName_CaptainOfGondor_CHB05
	GroupName		 = CreateAHero_Boots
	BlingUpgradeName = Upgrade_CaptainOfGondor_CHB05
End

CreateAHeroBling // ElfArcher
	NameTag			 = CreateAHero:BlingName_ElfArcher_CHB01
	DescriptionTag	 = CreateAHero:BlingName_ElfArcher_CHB01
	GroupName		 = CreateAHero_Boots
	BlingUpgradeName = Upgrade_ELFA_CHB01
End

CreateAHeroBling // ElfArcher
	NameTag			 = CreateAHero:BlingName_ElfArcher_CHB02
	DescriptionTag	 = CreateAHero:BlingName_ElfArcher_CHB02
	GroupName		 = CreateAHero_Boots
	BlingUpgradeName = Upgrade_ELFA_CHB02
End

CreateAHeroBling // ElfArcher
	NameTag			 = CreateAHero:BlingName_ElfArcher_CHB03
	DescriptionTag	 = CreateAHero:BlingName_ElfArcher_CHB03
	GroupName		 = CreateAHero_Boots
	BlingUpgradeName = Upgrade_ELFA_CHB03
End

CreateAHeroBling // ShieldMaiden
	NameTag			 = CreateAHero:BlingName_ShieldMaiden_CHB01
	DescriptionTag	 = CreateAHero:BlingName_ShieldMaiden_CHB01
	GroupName		 = CreateAHero_Boots
	BlingUpgradeName = Upgrade_SHIM_CHB01
End

CreateAHeroBling // ShieldMaiden
	NameTag			 = CreateAHero:BlingName_ShieldMaiden_CHB02
	DescriptionTag	 = CreateAHero:BlingName_ShieldMaiden_CHB02
	GroupName		 = CreateAHero_Boots
	BlingUpgradeName = Upgrade_SHIM_CHB02
End

CreateAHeroBling // ShieldMaiden
	NameTag			 = CreateAHero:BlingName_ShieldMaiden_CHB03
	DescriptionTag	 = CreateAHero:BlingName_ShieldMaiden_CHB03
	GroupName		 = CreateAHero_Boots
	BlingUpgradeName = Upgrade_SHIM_CHB03
End

CreateAHeroBling // Female Elven Archer
	NameTag			 = CreateAHero:BlingName_FemaleElvenArcher_CHB01
	DescriptionTag	 = CreateAHero:BlingName_FemaleElvenArcher_CHB01
	GroupName		 = CreateAHero_Boots
	BlingUpgradeName = Upgrade_FEARCH_CHB01
End

CreateAHeroBling // Female Elven Archer
	NameTag			 = CreateAHero:BlingName_FemaleElvenArcher_CHB02
	DescriptionTag	 = CreateAHero:BlingName_FemaleElvenArcher_CHB02
	GroupName		 = CreateAHero_Boots
	BlingUpgradeName = Upgrade_FEARCH_CHB02
End

CreateAHeroBling // Female Elven Archer
	NameTag			 = CreateAHero:BlingName_FemaleElvenArcher_CHB03
	DescriptionTag	 = CreateAHero:BlingName_FemaleElvenArcher_CHB03
	GroupName		 = CreateAHero_Boots
	BlingUpgradeName = Upgrade_FEARCH_CHB03
End

CreateAHeroBling // Female Elven Archer
	NameTag			 = CreateAHero:BlingName_FemaleElvenArcher_CHB04
	DescriptionTag	 = CreateAHero:BlingName_FemaleElvenArcher_CHB04
	GroupName		 = CreateAHero_Boots
	BlingUpgradeName = Upgrade_FEARCH_CHB04
End

CreateAHeroBling // Female Elven Archer
	NameTag			 = CreateAHero:BlingName_FemaleElvenArcher_CHB05
	DescriptionTag	 = CreateAHero:BlingName_FemaleElvenArcher_CHB05
	GroupName		 = CreateAHero_Boots
	BlingUpgradeName = Upgrade_FEARCH_CHB05
End

CreateAHeroBling // Female Elven Archer
	NameTag			 = CreateAHero:BlingName_FemaleElvenArcher_CHB06
	DescriptionTag	 = CreateAHero:BlingName_FemaleElvenArcher_CHB06
	GroupName		 = CreateAHero_Boots
	BlingUpgradeName = Upgrade_FEARCH_CHB06
End

CreateAHeroBling // DWARF
	NameTag			 = CreateAHero:BlingName_DWARF_CHB01
	DescriptionTag	 = CreateAHero:BlingName_DWARF_CHB01
	GroupName		 = CreateAHero_Boots
	BlingUpgradeName = Upgrade_DWARF_CHB01
End

CreateAHeroBling // DWARF
	NameTag			 = CreateAHero:BlingName_DWARF_CHB02
	DescriptionTag	 = CreateAHero:BlingName_DWARF_CHB02
	GroupName		 = CreateAHero_Boots
	BlingUpgradeName = Upgrade_DWARF_CHB02
End

CreateAHeroBling // DWARF
	NameTag			 = CreateAHero:BlingName_DWARF_CHB03
	DescriptionTag	 = CreateAHero:BlingName_DWARF_CHB03
	GroupName		 = CreateAHero_Boots
	BlingUpgradeName = Upgrade_DWARF_CHB03
End

CreateAHeroBling // DWARF
	NameTag			 = CreateAHero:BlingName_DWARF_CHB04
	DescriptionTag	 = CreateAHero:BlingName_DWARF_CHB04
	GroupName		 = CreateAHero_Boots
	BlingUpgradeName = Upgrade_DWARF_CHB04
End

CreateAHeroBling // ORC
	NameTag			 = CreateAHero:BlingName_ORC_CHB01
	DescriptionTag	 = CreateAHero:BlingName_ORC_CHB01
	GroupName		 = CreateAHero_Boots
	BlingUpgradeName = Upgrade_ORC_CHB01
End

CreateAHeroBling // ORC
	NameTag			 = CreateAHero:BlingName_ORC_CHB02
	DescriptionTag	 = CreateAHero:BlingName_ORC_CHB02
	GroupName		 = CreateAHero_Boots
	BlingUpgradeName = Upgrade_ORC_CHB02
End

CreateAHeroBling // ORC
	NameTag			 = CreateAHero:BlingName_ORC_CHB03
	DescriptionTag	 = CreateAHero:BlingName_ORC_CHB03
	GroupName		 = CreateAHero_Boots
	BlingUpgradeName = Upgrade_ORC_CHB03
End

CreateAHeroBling // Troll
	NameTag			 = CreateAHero:BlingName_TRLL_CHB01
	DescriptionTag	 = CreateAHero:BlingName_TRLL_CHB01
	GroupName		 = CreateAHero_Boots
	BlingUpgradeName = Upgrade_TRLL_CHBO01
End

//-------------------------------
// Generic No Upgrades
CreateAHeroBling // No Head Gear
	NameTag			 = CreateAHero:BlingName_NoHelmet
	DescriptionTag	 = CreateAHero:BlingDesc_NoHelmet
	GroupName		 = CreateAHero_Helmet
	BlingUpgradeName = Upgrade_NoHelmet
End
CreateAHeroBling // No Gauntlets
	NameTag			 = CreateAHero:BlingName_NoGauntlets
	DescriptionTag	 = CreateAHero:BlingDesc_NoGauntlets
	GroupName		 = CreateAHero_Gauntlets
	BlingUpgradeName = Upgrade_NoGauntlets
End
CreateAHeroBling // No Shoulder Plates
	NameTag			 = CreateAHero:BlingName_NoShoulderPlates
	DescriptionTag	 = CreateAHero:BlingDesc_NoShoulderPlates
	GroupName		 = CreateAHero_ShoulderPlates
	BlingUpgradeName = Upgrade_NoShoulderPlates
End
CreateAHeroBling // No Shield
	NameTag			 = CreateAHero:BlingName_NoShield
	DescriptionTag	 = CreateAHero:BlingDesc_NoShield
	GroupName		 = CreateAHero_Shield
	BlingUpgradeName = Upgrade_NoShield
End
CreateAHeroBling // No Boots
	NameTag			 = CreateAHero:BlingName_NoBoots
	DescriptionTag	 = CreateAHero:BlingDesc_NoBoots
	GroupName		 = CreateAHero_Boots
	BlingUpgradeName = Upgrade_NoBoots
End

//-------------------------------
// Body
CreateAHeroBling  // Body_CMBOD01 // Corrupted Man
	NameTag			 = CreateAHero:BlingName_CM_CHBOD01
	DescriptionTag	 = CreateAHero:BlingName_CM_CHBOD01
	GroupName		 = CreateAHero_Body
	BlingUpgradeName = Upgrade_CM01_CHBOD01
End

CreateAHeroBling  // Body_CMBOD02 // Corrupted Man
	NameTag			 = CreateAHero:BlingName_CM_CHBOD02
	DescriptionTag	 = CreateAHero:BlingName_CM_CHBOD02
	GroupName		 = CreateAHero_Body
	BlingUpgradeName = Upgrade_CM01_CHBOD02
End
CreateAHeroBling  // Body_CMBOD03 // Corrupted Man
	NameTag			 = CreateAHero:BlingName_CM_CHBOD03
	DescriptionTag	 = CreateAHero:BlingName_CM_CHBOD03
	GroupName		 = CreateAHero_Body
	BlingUpgradeName = Upgrade_CM01_CHBOD03
End
CreateAHeroBling  // Body_CMBOD04 // Corrupted Man
	NameTag			 = CreateAHero:BlingName_CM_CHBOD04
	DescriptionTag	 = CreateAHero:BlingName_CM_CHBOD04
	GroupName		 = CreateAHero_Body
	BlingUpgradeName = Upgrade_CM01_CHBOD04
End

CreateAHeroBling  // Body_CMBOD05 // Corrupted Man
	NameTag			 = CreateAHero:BlingName_CM_CHBOD05
	DescriptionTag	 = CreateAHero:BlingName_CM_CHBOD05
	GroupName		 = CreateAHero_Body
	BlingUpgradeName = Upgrade_CM01_CHBOD05
End

CreateAHeroBling  // Body_CMBOD07 // Corrupted Man
	NameTag			 = CreateAHero:BlingName_CM_CHBOD07
	DescriptionTag	 = CreateAHero:BlingName_CM_CHBOD07
	GroupName		 = CreateAHero_Body
	BlingUpgradeName = Upgrade_CM01_CHBOD07
End

CreateAHeroBling  // Body_CMBOD08 // Corrupted Man
	NameTag			 = CreateAHero:BlingName_CM_CHBOD08
	DescriptionTag	 = CreateAHero:BlingName_CM_CHBOD08
	GroupName		 = CreateAHero_Body
	BlingUpgradeName = Upgrade_CM01_CHBOD08
End

CreateAHeroBling  // Body_CM02BOD01 // Corrupted Man 2
	NameTag			 = CreateAHero:BlingName_CM02_CHBOD01
	DescriptionTag	 = CreateAHero:BlingName_CM02_CHBOD01
	GroupName		 = CreateAHero_Body
	BlingUpgradeName = Upgrade_CM02_CHBOD01
End

CreateAHeroBling  // Body_CM02BOD02 // Corrupted Man 2
	NameTag			 = CreateAHero:BlingName_CM02_CHBOD02
	DescriptionTag	 = CreateAHero:BlingName_CM02_CHBOD02
	GroupName		 = CreateAHero_Body
	BlingUpgradeName = Upgrade_CM02_CHBOD02
End
CreateAHeroBling  // Body_CM02BOD03 // Corrupted Man 2
	NameTag			 = CreateAHero:BlingName_CM02_CHBOD03
	DescriptionTag	 = CreateAHero:BlingName_CM02_CHBOD03
	GroupName		 = CreateAHero_Body
	BlingUpgradeName = Upgrade_CM02_CHBOD03
End

CreateAHeroBling  // Body_CM02BOD04 // Corrupted Man 2
	NameTag			 = CreateAHero:BlingName_CM02_CHBOD04
	DescriptionTag	 = CreateAHero:BlingName_CM02_CHBOD04
	GroupName		 = CreateAHero_Body
	BlingUpgradeName = Upgrade_CM02_CHBOD04
End

CreateAHeroBling  // Body_CM02BOD05 // Corrupted Man 2
	NameTag			 = CreateAHero:BlingName_CM02_CHBOD05
	DescriptionTag	 = CreateAHero:BlingName_CM02_CHBOD05
	GroupName		 = CreateAHero_Body
	BlingUpgradeName = Upgrade_CM02_CHBOD05
End

CreateAHeroBling  // Body_CM02BOD07 // Corrupted Man 2
	NameTag			 = CreateAHero:BlingName_CM02_CHBOD07
	DescriptionTag	 = CreateAHero:BlingName_CM02_CHBOD07
	GroupName		 = CreateAHero_Body
	BlingUpgradeName = Upgrade_CM02_CHBOD07
End

CreateAHeroBling  // Body_CM02BOD08 // Corrupted Man 2
	NameTag			 = CreateAHero:BlingName_CM02_CHBOD08
	DescriptionTag	 = CreateAHero:BlingName_CM02_CHBOD08
	GroupName		 = CreateAHero_Body
	BlingUpgradeName = Upgrade_CM02_CHBOD08
End

CreateAHeroBling  // Body_UKBOD01 // Uruk Hai
	NameTag			 = CreateAHero:BlingName_UK_CHBOD01
	DescriptionTag	 = CreateAHero:BlingName_UK_CHBOD01
	GroupName		 = CreateAHero_Body
	BlingUpgradeName = Upgrade_URUK_CHBOD01
End

CreateAHeroBling  // Body_UKBOD02 // Uruk Hai
	NameTag			 = CreateAHero:BlingName_UK_CHBOD02
	DescriptionTag	 = CreateAHero:BlingName_UK_CHBOD02
	GroupName		 = CreateAHero_Body
	BlingUpgradeName = Upgrade_URUK_CHBOD02
End
CreateAHeroBling  // Body_UKBOD03 // Uruk Hai
	NameTag			 = CreateAHero:BlingName_UK_CHBOD03
	DescriptionTag	 = CreateAHero:BlingName_UK_CHBOD03
	GroupName		 = CreateAHero_Body
	BlingUpgradeName = Upgrade_URUK_CHBOD03
End

CreateAHeroBling  // Body_UKBOD04 // Uruk Hai
	NameTag			 = CreateAHero:BlingName_UK_CHBOD04
	DescriptionTag	 = CreateAHero:BlingName_UK_CHBOD04
	GroupName		 = CreateAHero_Body
	BlingUpgradeName = Upgrade_URUK_CHBOD04
End

CreateAHeroBling  // Body_EABOD01 // Elf Archer
	NameTag			 = CreateAHero:BlingName_EA_CHBOD01
	DescriptionTag	 = CreateAHero:BlingName_EA_CHBOD01
	GroupName		 = CreateAHero_Body
	BlingUpgradeName = Upgrade_ELFA_CHBOD01
End

CreateAHeroBling  // Body_EABOD02 // Elf Archer
	NameTag			 = CreateAHero:BlingName_EA_CHBOD02
	DescriptionTag	 = CreateAHero:BlingName_EA_CHBOD02
	GroupName		 = CreateAHero_Body
	BlingUpgradeName = Upgrade_ELFA_CHBOD02
End

CreateAHeroBling  // Body_EABOD03 // Elf Archer
	NameTag			 = CreateAHero:BlingName_EA_CHBOD03
	DescriptionTag	 = CreateAHero:BlingName_EA_CHBOD03
	GroupName		 = CreateAHero_Body
	BlingUpgradeName = Upgrade_ELFA_CHBOD03
End

CreateAHeroBling  // Body_EABOD04 // Elf Archer
	NameTag			 = CreateAHero:BlingName_EA_CHBOD04
	DescriptionTag	 = CreateAHero:BlingName_EA_CHBOD04
	GroupName		 = CreateAHero_Body
	BlingUpgradeName = Upgrade_ELFA_CHBOD04
End

CreateAHeroBling  // Body_FEBOD01 // Female Elf Archer
	NameTag			 = CreateAHero:BlingName_FE_CHBOD01
	DescriptionTag	 = CreateAHero:BlingName_FE_CHBOD01
	GroupName		 = CreateAHero_Body
	BlingUpgradeName = Upgrade_FEARCH_CHBOD01
End

CreateAHeroBling  // Body_FEBOD02 // Female Elf Archer
	NameTag			 = CreateAHero:BlingName_FE_CHBOD02
	DescriptionTag	 = CreateAHero:BlingName_FE_CHBOD02
	GroupName		 = CreateAHero_Body
	BlingUpgradeName = Upgrade_FEARCH_CHBOD02
End

CreateAHeroBling  // Body_FEBOD03 // Female Elf Archer
	NameTag			 = CreateAHero:BlingName_FE_CHBOD03
	DescriptionTag	 = CreateAHero:BlingName_FE_CHBOD03
	GroupName		 = CreateAHero_Body
	BlingUpgradeName = Upgrade_FEARCH_CHBOD03
End

CreateAHeroBling  // Body_EABOD01 // Captain of Gondor
	NameTag			 = CreateAHero:BlingName_CG_CHBOD01
	DescriptionTag	 = CreateAHero:BlingName_CG_CHBOD01
	GroupName		 = CreateAHero_Body
	BlingUpgradeName = Upgrade_CAPG_CHBOD01
End

CreateAHeroBling  // Body_EABOD02 // Captain of Gondor
	NameTag			 = CreateAHero:BlingName_CG_CHBOD02
	DescriptionTag	 = CreateAHero:BlingName_CG_CHBOD02
	GroupName		 = CreateAHero_Body
	BlingUpgradeName = Upgrade_CAPG_CHBOD02
End

CreateAHeroBling  // Body_EABOD03 // Captain of Gondor
	NameTag			 = CreateAHero:BlingName_CG_CHBOD03
	DescriptionTag	 = CreateAHero:BlingName_CG_CHBOD03
	GroupName		 = CreateAHero_Body
	BlingUpgradeName = Upgrade_CAPG_CHBOD03
End

CreateAHeroBling  // Body_EABOD04 // Captain of Gondor
	NameTag			 = CreateAHero:BlingName_CG_CHBOD04
	DescriptionTag	 = CreateAHero:BlingName_CG_CHBOD04
	GroupName		 = CreateAHero_Body
	BlingUpgradeName = Upgrade_CAPG_CHBOD04
End

CreateAHeroBling  // Body_SMBOD01 // Shield Maiden
	NameTag			 = CreateAHero:BlingName_SM_CHBOD01
	DescriptionTag	 = CreateAHero:BlingName_SM_CHBOD01
	GroupName		 = CreateAHero_Body
	BlingUpgradeName = Upgrade_SHIM_CHBOD01
End

CreateAHeroBling  // Body_SMBOD02 // Shield Maiden
	NameTag			 = CreateAHero:BlingName_SM_CHBOD02
	DescriptionTag	 = CreateAHero:BlingName_SM_CHBOD02
	GroupName		 = CreateAHero_Body
	BlingUpgradeName = Upgrade_SHIM_CHBOD02
End

CreateAHeroBling  // Body_SMBOD03 // Shield Maiden
	NameTag			 = CreateAHero:BlingName_SM_CHBOD03
	DescriptionTag	 = CreateAHero:BlingName_SM_CHBOD03
	GroupName		 = CreateAHero_Body
	BlingUpgradeName = Upgrade_SHIM_CHBOD03
End

CreateAHeroBling  // Body_SMBOD04 // Shield Maiden
	NameTag			 = CreateAHero:BlingName_SM_CHBOD04
	DescriptionTag	 = CreateAHero:BlingName_SM_CHBOD04
	GroupName		 = CreateAHero_Body
	BlingUpgradeName = Upgrade_SHIM_CHBOD04
End

CreateAHeroBling  // Body_SMBOD05 // Shield Maiden
	NameTag			 = CreateAHero:BlingName_SM_CHBOD05
	DescriptionTag	 = CreateAHero:BlingName_SM_CHBOD05
	GroupName		 = CreateAHero_Body
	BlingUpgradeName = Upgrade_SHIM_CHBOD05
End

CreateAHeroBling  // Body_WIZBOD01 // Wizard
	NameTag			 = CreateAHero:BlingName_WIZ_CHBOD01
	DescriptionTag	 = CreateAHero:BlingName_WIZ_CHBOD01
	GroupName		 = CreateAHero_Body
	BlingUpgradeName = Upgrade_WIZ_CHBOD01
End

CreateAHeroBling  // Body_WIZBOD02 // Wizard
	NameTag			 = CreateAHero:BlingName_WIZ_CHBOD02
	DescriptionTag	 = CreateAHero:BlingName_WIZ_CHBOD02
	GroupName		 = CreateAHero_Body
	BlingUpgradeName = Upgrade_WIZ_CHBOD02
End

CreateAHeroBling  // Body_WIZBOD03 // Wizard
	NameTag			 = CreateAHero:BlingName_WIZ_CHBOD03
	DescriptionTag	 = CreateAHero:BlingName_WIZ_CHBOD03
	GroupName		 = CreateAHero_Body
	BlingUpgradeName = Upgrade_WIZ_CHBOD03
End

CreateAHeroBling  // Body_ORCBOD01 // ORC Raider
	NameTag			 = CreateAHero:BlingName_ORC_CHBOD01
	DescriptionTag	 = CreateAHero:BlingName_ORC_CHBOD01
	GroupName		 = CreateAHero_Body
	BlingUpgradeName = Upgrade_ORC_CHBOD01
End

CreateAHeroBling  // Body_ORCBOD02 // ORC Raider
	NameTag			 = CreateAHero:BlingName_ORC_CHBOD02
	DescriptionTag	 = CreateAHero:BlingName_ORC_CHBOD02
	GroupName		 = CreateAHero_Body
	BlingUpgradeName = Upgrade_ORC_CHBOD02
End

CreateAHeroBling  // Body_ORCBOD03 // ORC Raider
	NameTag			 = CreateAHero:BlingName_ORC_CHBOD03
	DescriptionTag	 = CreateAHero:BlingName_ORC_CHBOD03
	GroupName		 = CreateAHero_Body
	BlingUpgradeName = Upgrade_ORC_CHBOD03
End

CreateAHeroBling  // Body_TRLLBOD01 // TROLL
	NameTag			 = CreateAHero:BlingName_TRLL_CHBOD01
	DescriptionTag	 = CreateAHero:BlingName_TRLL_CHBOD01
	GroupName		 = CreateAHero_Body
	BlingUpgradeName = Upgrade_TRLL_CHBOD01
End

CreateAHeroBling  // Body_TRLLBOD02 // TROLL
	NameTag			 = CreateAHero:BlingName_TRLL_CHBOD02
	DescriptionTag	 = CreateAHero:BlingName_TRLL_CHBOD02
	GroupName		 = CreateAHero_Body
	BlingUpgradeName = Upgrade_TRLL_CHBOD02
End
CreateAHeroBling  // Body_TRLLBOD03 // TROLL
	NameTag			 = CreateAHero:BlingName_TRLL_CHBOD03
	DescriptionTag	 = CreateAHero:BlingName_TRLL_CHBOD03
	GroupName		 = CreateAHero_Body
	BlingUpgradeName = Upgrade_TRLL_CHBOD03
End
CreateAHeroBling  // Body_TRLLBOD04 // TROLL
	NameTag			 = CreateAHero:BlingName_TRLL_CHBOD04
	DescriptionTag	 = CreateAHero:BlingName_TRLL_CHBOD04
	GroupName		 = CreateAHero_Body
	BlingUpgradeName = Upgrade_TRLL_CHBOD04
End
CreateAHeroBling  // Body_TRLLBOD04 // TROLL
	NameTag			 = CreateAHero:BlingName_TRLL_CHBOD05
	DescriptionTag	 = CreateAHero:BlingName_TRLL_CHBOD05
	GroupName		 = CreateAHero_Body
	BlingUpgradeName = Upgrade_TRLL_CHBOD05
End
CreateAHeroBling  // Body_TRLLBOD04 // TROLL
	NameTag			 = CreateAHero:BlingName_TRLL_CHBOD06
	DescriptionTag	 = CreateAHero:BlingName_TRLL_CHBOD06
	GroupName		 = CreateAHero_Body
	BlingUpgradeName = Upgrade_TRLL_CHBOD06
End
CreateAHeroBling  // Body_TRLLBOD04 // TROLL
	NameTag			 = CreateAHero:BlingName_TRLL_CHBOD07
	DescriptionTag	 = CreateAHero:BlingName_TRLL_CHBOD07
	GroupName		 = CreateAHero_Body
	BlingUpgradeName = Upgrade_TRLL_CHBOD07
End
CreateAHeroBling  // Body_TRLLBOD04 // TROLL
	NameTag			 = CreateAHero:BlingName_TRLL_CHBOD08
	DescriptionTag	 = CreateAHero:BlingName_TRLL_CHBOD08
	GroupName		 = CreateAHero_Body
	BlingUpgradeName = Upgrade_TRLL_CHBOD08
End
CreateAHeroBling  // Body_TRLLBOD04 // TROLL
	NameTag			 = CreateAHero:BlingName_TRLL_CHBOD09
	DescriptionTag	 = CreateAHero:BlingName_TRLL_CHBOD09
	GroupName		 = CreateAHero_Body
	BlingUpgradeName = Upgrade_TRLL_CHBOD09
End

CreateAHeroBling  // Body_DWARFBOD01 // DWARF
	NameTag			 = CreateAHero:BlingName_DWARF_CHBOD01
	DescriptionTag	 = CreateAHero:BlingName_DWARF_CHBOD01
	GroupName		 = CreateAHero_Body
	BlingUpgradeName = Upgrade_DWARF_CHBOD01
End

CreateAHeroBling  // Body_DWARFBOD02 // DWARF
	NameTag			 = CreateAHero:BlingName_DWARF_CHBOD02
	DescriptionTag	 = CreateAHero:BlingName_DWARF_CHBOD02
	GroupName		 = CreateAHero_Body
	BlingUpgradeName = Upgrade_DWARF_CHBOD02
End

CreateAHeroBling  // Body_DWARFBOD03 // DWARF
	NameTag			 = CreateAHero:BlingName_DWARF_CHBOD03
	DescriptionTag	 = CreateAHero:BlingName_DWARF_CHBOD03
	GroupName		 = CreateAHero_Body
	BlingUpgradeName = Upgrade_DWARF_CHBOD03
End

CreateAHeroBling  // Body_DWARFBOD04 // DWARF
	NameTag			 = CreateAHero:BlingName_DWARF_CHBOD04
	DescriptionTag	 = CreateAHero:BlingName_DWARF_CHBOD04
	GroupName		 = CreateAHero_Body
	BlingUpgradeName = Upgrade_DWARF_CHBOD04
End

CreateAHeroBling  // Body_DWARFBOD05 // DWARF
	NameTag			 = CreateAHero:BlingName_DWARF_CHBOD05
	DescriptionTag	 = CreateAHero:BlingName_DWARF_CHBOD05
	GroupName		 = CreateAHero_Body
	BlingUpgradeName = Upgrade_DWARF_CHBOD05
End

CreateAHeroBling  // Body_DSAGEBOD01 // DSAGE
	NameTag			 = CreateAHero:BlingName_DSAGE_CHBOD01
	DescriptionTag	 = CreateAHero:BlingName_DSAGE_CHBOD01
	GroupName		 = CreateAHero_Body
	BlingUpgradeName = Upgrade_DSAGE_CHBOD01
End

CreateAHeroBling  // Body_DSAGEBOD02 // DSAGE
	NameTag			 = CreateAHero:BlingName_DSAGE_CHBOD02
	DescriptionTag	 = CreateAHero:BlingName_DSAGE_CHBOD02
	GroupName		 = CreateAHero_Body
	BlingUpgradeName = Upgrade_DSAGE_CHBOD02
End

CreateAHeroBling  // Body_DSAGEBOD03 // DSAGE
	NameTag			 = CreateAHero:BlingName_DSAGE_CHBOD03
	DescriptionTag	 = CreateAHero:BlingName_DSAGE_CHBOD03
	GroupName		 = CreateAHero_Body
	BlingUpgradeName = Upgrade_DSAGE_CHBOD03
End

CreateAHeroBling  // Body_DSAGEBOD04 // DSAGE
	NameTag			 = CreateAHero:BlingName_DSAGE_CHBOD04
	DescriptionTag	 = CreateAHero:BlingName_DSAGE_CHBOD04
	GroupName		 = CreateAHero_Body
	BlingUpgradeName = Upgrade_DSAGE_CHBOD04
End

CreateAHeroBling  // Body_DSAGEBOD05 // DSAGE
	NameTag			 = CreateAHero:BlingName_DSAGE_CHBOD05
	DescriptionTag	 = CreateAHero:BlingName_DSAGE_CHBOD05
	GroupName		 = CreateAHero_Body
	BlingUpgradeName = Upgrade_DSAGE_CHBOD05
End