//-----------------------------------------------------------------------------------------
// Attribute Bling for the Create A Hero unit.
// This file declares all of the Bling entries for the various hero attributes.
//-----------------------------------------------------------------------------------------
// ArmorAttribute
CreateAHeroBling
	GroupName			= CreateAHero_ArmorAttribute
	BlingUpgradeName	= Upgrade_ArmorAttribute01
End
CreateAHeroBling
	GroupName			= CreateAHero_ArmorAttribute
	BlingUpgradeName	= Upgrade_ArmorAttribute02
End
CreateAHeroBling
	GroupName			= CreateAHero_ArmorAttribute
	BlingUpgradeName	= Upgrade_ArmorAttribute03
End
CreateAHeroBling
	GroupName			= CreateAHero_ArmorAttribute
	BlingUpgradeName	= Upgrade_ArmorAttribute04
End
CreateAHeroBling
	GroupName			= CreateAHero_ArmorAttribute
	BlingUpgradeName	= Upgrade_ArmorAttribute05
End
CreateAHeroBling
	GroupName			= CreateAHero_ArmorAttribute
	BlingUpgradeName	= Upgrade_ArmorAttribute06
End
CreateAHeroBling
	GroupName			= CreateAHero_ArmorAttribute
	BlingUpgradeName	= Upgrade_ArmorAttribute07
End
CreateAHeroBling
	GroupName			= CreateAHero_ArmorAttribute
	BlingUpgradeName	= Upgrade_ArmorAttribute08
End
CreateAHeroBling
	GroupName			= CreateAHero_ArmorAttribute
	BlingUpgradeName	= Upgrade_ArmorAttribute09
End
CreateAHeroBling
	GroupName			= CreateAHero_ArmorAttribute
	BlingUpgradeName	= Upgrade_ArmorAttribute10
End
CreateAHeroBling
	GroupName			= CreateAHero_ArmorAttribute
	BlingUpgradeName	= Upgrade_ArmorAttribute11
End
CreateAHeroBling
	GroupName			= CreateAHero_ArmorAttribute
	BlingUpgradeName	= Upgrade_ArmorAttribute12
End
CreateAHeroBling
	GroupName			= CreateAHero_ArmorAttribute
	BlingUpgradeName	= Upgrade_ArmorAttribute13
End
CreateAHeroBling
	GroupName			= CreateAHero_ArmorAttribute
	BlingUpgradeName	= Upgrade_ArmorAttribute14
End
CreateAHeroBling
	GroupName			= CreateAHero_ArmorAttribute
	BlingUpgradeName	= Upgrade_ArmorAttribute15
End
CreateAHeroBling
	GroupName			= CreateAHero_ArmorAttribute
	BlingUpgradeName	= Upgrade_ArmorAttribute16
End
CreateAHeroBling
	GroupName			= CreateAHero_ArmorAttribute
	BlingUpgradeName	= Upgrade_ArmorAttribute17
End
CreateAHeroBling
	GroupName			= CreateAHero_ArmorAttribute
	BlingUpgradeName	= Upgrade_ArmorAttribute18
End
CreateAHeroBling
	GroupName			= CreateAHero_ArmorAttribute
	BlingUpgradeName	= Upgrade_ArmorAttribute19
End
CreateAHeroBling
	GroupName			= CreateAHero_ArmorAttribute
	BlingUpgradeName	= Upgrade_ArmorAttribute20
End

//-------------------------------------------------------
// DamageMultAttribute
CreateAHeroBling
	GroupName			= CreateAHero_DamageMultAttribute
	BlingUpgradeName	= Upgrade_DamageMultAttribute01
End
CreateAHeroBling
	GroupName			= CreateAHero_DamageMultAttribute
	BlingUpgradeName	= Upgrade_DamageMultAttribute02
End
CreateAHeroBling
	GroupName			= CreateAHero_DamageMultAttribute
	BlingUpgradeName	= Upgrade_DamageMultAttribute03
End
CreateAHeroBling
	GroupName			= CreateAHero_DamageMultAttribute
	BlingUpgradeName	= Upgrade_DamageMultAttribute04
End
CreateAHeroBling
	GroupName			= CreateAHero_DamageMultAttribute
	BlingUpgradeName	= Upgrade_DamageMultAttribute05
End
CreateAHeroBling
	GroupName			= CreateAHero_DamageMultAttribute
	BlingUpgradeName	= Upgrade_DamageMultAttribute06
End
CreateAHeroBling
	GroupName			= CreateAHero_DamageMultAttribute
	BlingUpgradeName	= Upgrade_DamageMultAttribute07
End
CreateAHeroBling
	GroupName			= CreateAHero_DamageMultAttribute
	BlingUpgradeName	= Upgrade_DamageMultAttribute08
End
CreateAHeroBling
	GroupName			= CreateAHero_DamageMultAttribute
	BlingUpgradeName	= Upgrade_DamageMultAttribute09
End
CreateAHeroBling
	GroupName			= CreateAHero_DamageMultAttribute
	BlingUpgradeName	= Upgrade_DamageMultAttribute10
End
CreateAHeroBling
	GroupName			= CreateAHero_DamageMultAttribute
	BlingUpgradeName	= Upgrade_DamageMultAttribute11
End
CreateAHeroBling
	GroupName			= CreateAHero_DamageMultAttribute
	BlingUpgradeName	= Upgrade_DamageMultAttribute12
End
CreateAHeroBling
	GroupName			= CreateAHero_DamageMultAttribute
	BlingUpgradeName	= Upgrade_DamageMultAttribute13
End
CreateAHeroBling
	GroupName			= CreateAHero_DamageMultAttribute
	BlingUpgradeName	= Upgrade_DamageMultAttribute14
End
CreateAHeroBling
	GroupName			= CreateAHero_DamageMultAttribute
	BlingUpgradeName	= Upgrade_DamageMultAttribute15
End
CreateAHeroBling
	GroupName			= CreateAHero_DamageMultAttribute
	BlingUpgradeName	= Upgrade_DamageMultAttribute16
End
CreateAHeroBling
	GroupName			= CreateAHero_DamageMultAttribute
	BlingUpgradeName	= Upgrade_DamageMultAttribute17
End
CreateAHeroBling
	GroupName			= CreateAHero_DamageMultAttribute
	BlingUpgradeName	= Upgrade_DamageMultAttribute18
End
CreateAHeroBling
	GroupName			= CreateAHero_DamageMultAttribute
	BlingUpgradeName	= Upgrade_DamageMultAttribute19
End
CreateAHeroBling
	GroupName			= CreateAHero_DamageMultAttribute
	BlingUpgradeName	= Upgrade_DamageMultAttribute20
End

//-------------------------------------------------------
// VisionAttribute
CreateAHeroBling
	GroupName			= CreateAHero_VisionAttribute
	BlingUpgradeName	= Upgrade_VisionAttribute01
End
CreateAHeroBling
	GroupName			= CreateAHero_VisionAttribute
	BlingUpgradeName	= Upgrade_VisionAttribute02
End
CreateAHeroBling
	GroupName			= CreateAHero_VisionAttribute
	BlingUpgradeName	= Upgrade_VisionAttribute03
End
CreateAHeroBling
	GroupName			= CreateAHero_VisionAttribute
	BlingUpgradeName	= Upgrade_VisionAttribute04
End
CreateAHeroBling
	GroupName			= CreateAHero_VisionAttribute
	BlingUpgradeName	= Upgrade_VisionAttribute05
End
CreateAHeroBling
	GroupName			= CreateAHero_VisionAttribute
	BlingUpgradeName	= Upgrade_VisionAttribute06
End
CreateAHeroBling
	GroupName			= CreateAHero_VisionAttribute
	BlingUpgradeName	= Upgrade_VisionAttribute07
End
CreateAHeroBling
	GroupName			= CreateAHero_VisionAttribute
	BlingUpgradeName	= Upgrade_VisionAttribute08
End
CreateAHeroBling
	GroupName			= CreateAHero_VisionAttribute
	BlingUpgradeName	= Upgrade_VisionAttribute09
End
CreateAHeroBling
	GroupName			= CreateAHero_VisionAttribute
	BlingUpgradeName	= Upgrade_VisionAttribute10
End
CreateAHeroBling
	GroupName			= CreateAHero_VisionAttribute
	BlingUpgradeName	= Upgrade_VisionAttribute11
End
CreateAHeroBling
	GroupName			= CreateAHero_VisionAttribute
	BlingUpgradeName	= Upgrade_VisionAttribute12
End
CreateAHeroBling
	GroupName			= CreateAHero_VisionAttribute
	BlingUpgradeName	= Upgrade_VisionAttribute13
End
CreateAHeroBling
	GroupName			= CreateAHero_VisionAttribute
	BlingUpgradeName	= Upgrade_VisionAttribute14
End
CreateAHeroBling
	GroupName			= CreateAHero_VisionAttribute
	BlingUpgradeName	= Upgrade_VisionAttribute15
End
CreateAHeroBling
	GroupName			= CreateAHero_VisionAttribute
	BlingUpgradeName	= Upgrade_VisionAttribute16
End
CreateAHeroBling
	GroupName			= CreateAHero_VisionAttribute
	BlingUpgradeName	= Upgrade_VisionAttribute17
End
CreateAHeroBling
	GroupName			= CreateAHero_VisionAttribute
	BlingUpgradeName	= Upgrade_VisionAttribute18
End
CreateAHeroBling
	GroupName			= CreateAHero_VisionAttribute
	BlingUpgradeName	= Upgrade_VisionAttribute19
End
CreateAHeroBling
	GroupName			= CreateAHero_VisionAttribute
	BlingUpgradeName	= Upgrade_VisionAttribute20
End

//-------------------------------------------------------
// AutoHealAttribute
CreateAHeroBling
	GroupName			= CreateAHero_AutoHealAttribute
	BlingUpgradeName	= Upgrade_AutoHealAttribute01
End
CreateAHeroBling
	GroupName			= CreateAHero_AutoHealAttribute
	BlingUpgradeName	= Upgrade_AutoHealAttribute02
End
CreateAHeroBling
	GroupName			= CreateAHero_AutoHealAttribute
	BlingUpgradeName	= Upgrade_AutoHealAttribute03
End
CreateAHeroBling
	GroupName			= CreateAHero_AutoHealAttribute
	BlingUpgradeName	= Upgrade_AutoHealAttribute04
End
CreateAHeroBling
	GroupName			= CreateAHero_AutoHealAttribute
	BlingUpgradeName	= Upgrade_AutoHealAttribute05
End
CreateAHeroBling
	GroupName			= CreateAHero_AutoHealAttribute
	BlingUpgradeName	= Upgrade_AutoHealAttribute06
End
CreateAHeroBling
	GroupName			= CreateAHero_AutoHealAttribute
	BlingUpgradeName	= Upgrade_AutoHealAttribute07
End
CreateAHeroBling
	GroupName			= CreateAHero_AutoHealAttribute
	BlingUpgradeName	= Upgrade_AutoHealAttribute08
End
CreateAHeroBling
	GroupName			= CreateAHero_AutoHealAttribute
	BlingUpgradeName	= Upgrade_AutoHealAttribute09
End
CreateAHeroBling
	GroupName			= CreateAHero_AutoHealAttribute
	BlingUpgradeName	= Upgrade_AutoHealAttribute10
End
CreateAHeroBling
	GroupName			= CreateAHero_AutoHealAttribute
	BlingUpgradeName	= Upgrade_AutoHealAttribute11
End
CreateAHeroBling
	GroupName			= CreateAHero_AutoHealAttribute
	BlingUpgradeName	= Upgrade_AutoHealAttribute12
End
CreateAHeroBling
	GroupName			= CreateAHero_AutoHealAttribute
	BlingUpgradeName	= Upgrade_AutoHealAttribute13
End
CreateAHeroBling
	GroupName			= CreateAHero_AutoHealAttribute
	BlingUpgradeName	= Upgrade_AutoHealAttribute14
End
CreateAHeroBling
	GroupName			= CreateAHero_AutoHealAttribute
	BlingUpgradeName	= Upgrade_AutoHealAttribute15
End
CreateAHeroBling
	GroupName			= CreateAHero_AutoHealAttribute
	BlingUpgradeName	= Upgrade_AutoHealAttribute16
End
CreateAHeroBling
	GroupName			= CreateAHero_AutoHealAttribute
	BlingUpgradeName	= Upgrade_AutoHealAttribute17
End
CreateAHeroBling
	GroupName			= CreateAHero_AutoHealAttribute
	BlingUpgradeName	= Upgrade_AutoHealAttribute18
End
CreateAHeroBling
	GroupName			= CreateAHero_AutoHealAttribute
	BlingUpgradeName	= Upgrade_AutoHealAttribute19
End
CreateAHeroBling
	GroupName			= CreateAHero_AutoHealAttribute
	BlingUpgradeName	= Upgrade_AutoHealAttribute20
End

//-------------------------------------------------------
// HealthMultAttribute
CreateAHeroBling
	GroupName			= CreateAHero_HealthMultAttribute
	BlingUpgradeName	= Upgrade_HealthMultAttribute01
End
CreateAHeroBling
	GroupName			= CreateAHero_HealthMultAttribute
	BlingUpgradeName	= Upgrade_HealthMultAttribute02
End
CreateAHeroBling
	GroupName			= CreateAHero_HealthMultAttribute
	BlingUpgradeName	= Upgrade_HealthMultAttribute03
End
CreateAHeroBling
	GroupName			= CreateAHero_HealthMultAttribute
	BlingUpgradeName	= Upgrade_HealthMultAttribute04
End
CreateAHeroBling
	GroupName			= CreateAHero_HealthMultAttribute
	BlingUpgradeName	= Upgrade_HealthMultAttribute05
End
CreateAHeroBling
	GroupName			= CreateAHero_HealthMultAttribute
	BlingUpgradeName	= Upgrade_HealthMultAttribute06
End
CreateAHeroBling
	GroupName			= CreateAHero_HealthMultAttribute
	BlingUpgradeName	= Upgrade_HealthMultAttribute07
End
CreateAHeroBling
	GroupName			= CreateAHero_HealthMultAttribute
	BlingUpgradeName	= Upgrade_HealthMultAttribute08
End
CreateAHeroBling
	GroupName			= CreateAHero_HealthMultAttribute
	BlingUpgradeName	= Upgrade_HealthMultAttribute09
End
CreateAHeroBling
	GroupName			= CreateAHero_HealthMultAttribute
	BlingUpgradeName	= Upgrade_HealthMultAttribute10
End
CreateAHeroBling
	GroupName			= CreateAHero_HealthMultAttribute
	BlingUpgradeName	= Upgrade_HealthMultAttribute11
End
CreateAHeroBling
	GroupName			= CreateAHero_HealthMultAttribute
	BlingUpgradeName	= Upgrade_HealthMultAttribute12
End
CreateAHeroBling
	GroupName			= CreateAHero_HealthMultAttribute
	BlingUpgradeName	= Upgrade_HealthMultAttribute13
End
CreateAHeroBling
	GroupName			= CreateAHero_HealthMultAttribute
	BlingUpgradeName	= Upgrade_HealthMultAttribute14
End
CreateAHeroBling
	GroupName			= CreateAHero_HealthMultAttribute
	BlingUpgradeName	= Upgrade_HealthMultAttribute15
End
CreateAHeroBling
	GroupName			= CreateAHero_HealthMultAttribute
	BlingUpgradeName	= Upgrade_HealthMultAttribute16
End
CreateAHeroBling
	GroupName			= CreateAHero_HealthMultAttribute
	BlingUpgradeName	= Upgrade_HealthMultAttribute17
End
CreateAHeroBling
	GroupName			= CreateAHero_HealthMultAttribute
	BlingUpgradeName	= Upgrade_HealthMultAttribute18
End
CreateAHeroBling
	GroupName			= CreateAHero_HealthMultAttribute
	BlingUpgradeName	= Upgrade_HealthMultAttribute19
End
CreateAHeroBling
	GroupName			= CreateAHero_HealthMultAttribute
	BlingUpgradeName	= Upgrade_HealthMultAttribute20
End

