DefaultModelConditionState
	Model				 = CHHW_CG_U_SKN
	Skeleton			 = CHHW_CG_U_SKL
	ModelAnimationPrefix = CHHW_CG
	PortraitImageName	 = CPGamling
	ButtonImageName		 = CPGamlingAlpha
End


//--------------------------------------------------------------------------------------------------------------------------------------
// CAPTAIN OF GONDOR -	Upgrade_CreateAHero_ClassHeroOfTheWest/Upgrade_CreateAHero_SubClass_2
ModelConditionState	= MOUNTED CREATE_A_HERO_00
	Model				 = CHHW_MW_M_SKN
	Skeleton			 = CHHW_MW_M_SKL
	ModelAnimationPrefix = CHHW_MW
	PortraitImageName	 = CPCaptainofGondor
	ButtonImageName		 = HICAHCaptainGondor
End
// CAPTAIN OF GONDOR -	Upgrade_CreateAHero_ClassHeroOfTheWest/Upgrade_CreateAHero_SubClass_2 (MOUNTED)
ModelConditionState	= CREATE_A_HERO_00
	Model				 = CHHW_CG_U_SKN
	Skeleton			 = CHHW_CG_U_SKL
	ModelAnimationPrefix = CHHW_CG
	PortraitImageName	 = CPCaptainofGondor
	ButtonImageName		 = HICAHCaptainGondor
End
// CAPTAIN OF GONDOR -	Upgrade_CreateAHero_ClassHeroOfTheWest/Upgrade_CreateAHero_SubClass_2 (Hero Creation Screen)
ModelConditionState	= CREATE_A_HERO_01
	Model				 = CHHW_CG_C_SKN
	Skeleton			 = CHHW_CG_C_SKL
	ModelAnimationPrefix = CHHW_CG
	PortraitImageName	 = CPCaptainofGondor
	ButtonImageName		 = HICAHCaptainGondor
End

//--------------------------------------------------------------------------------------------------------------------------------------
// Shield Maiden Upgrade_CreateAHero_ClassHeroOfTheWest_SubClass_1 MOUNTED
ModelConditionState	= MOUNTED CREATE_A_HERO_02
	Model				 = CHHW_SM_M_SKN
	Skeleton			 = CHHW_SM_M_SKL
	ModelAnimationPrefix = CHHW_SM
	PortraitImageName	 = CPShieldMaiden
	ButtonImageName		 = HICAHShieldMaiden
End
// Shield Maiden Upgrade_CreateAHero_ClassHeroOfTheWest_SubClass_1
ModelConditionState	= CREATE_A_HERO_02
	Model				 = CHHW_SM_U_SKN
	Skeleton			 = CHHW_SM_U_SKL
	ModelAnimationPrefix = CHHW_SM
	PortraitImageName	 = CPShieldMaiden
	ButtonImageName		 = HICAHShieldMaiden
End
// Shield Maiden Upgrade_CreateAHero_ClassHeroOfTheWest_SubClass_1 + Upgrade_CreateAHeroMapMode
ModelConditionState	= CREATE_A_HERO_03
	Model				 = CHHW_SM_C_SKN
	Skeleton			 = CHHW_SM_C_SKL
	ModelAnimationPrefix = CHHW_SM
	PortraitImageName	 = CPShieldMaiden
	ButtonImageName		 = HICAHShieldMaiden
End

//--------------------------------------------------------------------------------------------------------------------------------------
// WIZARD WANDERER Upgrade_CreateAHero_ClassIstariWizard/Upgrade_CreateAHero_SubClass_0
ModelConditionState	= CREATE_A_HERO_04
	Model				 = CHWZ_YW_U_SKN
	Skeleton			 = CHWZ_YW_U_SKL
	ModelAnimationPrefix = CHWZ_YW
	PortraitImageName	 = CPWanderer
	ButtonImageName		 = HICAHWanderer
	WeaponLaunchBone	 = PRIMARY WizStaff02_FXBO
End
// WIZARD WANDERER Upgrade_CreateAHeroMapMode Upgrade_CreateAHero_ClassIstariWizard/Upgrade_CreateAHero_SubClass_0
ModelConditionState	= CREATE_A_HERO_05
	Model				 = CHWZ_YW_C_SKN
	Skeleton			 = CHWZ_YW_C_SKL
	ModelAnimationPrefix = CHWZ_YW
	PortraitImageName	 = CPWanderer
	ButtonImageName		 = HICAHWanderer
	WeaponLaunchBone	 = PRIMARY WizStaff02_FXBO
End

//--------------------------------------------------------------------------------------------------------------------------------------
// WIZARD AVATAR Upgrade_CreateAHero_ClassIstariWizard Upgrade_CreateAHero_SubClass_2
ModelConditionState	= CREATE_A_HERO_06
	Model				 = CHWZ_AV_U_SKN
	Skeleton			 = CHWZ_YW_U_SKL
	ModelAnimationPrefix = CHWZ_YW
	PortraitImageName	 = CPAvatar
	ButtonImageName		 = HICAHAvatar
	WeaponLaunchBone	 = PRIMARY WizStaff02_FXBO
End
// WIZARD AVATAR Upgrade_CreateAHeroMapMode Upgrade_CreateAHero_ClassIstariWizard Upgrade_CreateAHero_SubClass_2 (Creation Screen)
ModelConditionState	= CREATE_A_HERO_07
	Model				 = CHWZ_AV_C_SKN
	Skeleton			 = CHWZ_YW_C_SKL
	ModelAnimationPrefix = CHWZ_YW
	PortraitImageName	 = CPAvatar
	ButtonImageName		 = HICAHAvatar
	WeaponLaunchBone	 = PRIMARY WizStaff02_FXBO
End

//--------------------------------------------------------------------------------------------------------------------------------------
// WIZARD HERMIT Upgrade_CreateAHero_ClassIstariWizard Upgrade_CreateAHero_SubClass_3
ModelConditionState	= CREATE_A_HERO_08
	Model				 = CHWZ_HR_U_SKN
	Skeleton			 = CHWZ_YW_U_SKL
	ModelAnimationPrefix = CHWZ_YW
	PortraitImageName	 = CPHermit
	ButtonImageName		 = HICAHHermit
	WeaponLaunchBone	 = PRIMARY WizStaff02_FXBO
End
// WIZARD HERMIT Upgrade_CreateAHeroMapMode Upgrade_CreateAHero_ClassIstariWizard Upgrade_CreateAHero_SubClass_3
ModelConditionState	= CREATE_A_HERO_09
	Model				 = CHWZ_HR_C_SKN
	Skeleton			 = CHWZ_YW_C_SKL
	ModelAnimationPrefix = CHWZ_YW
	PortraitImageName	 = CPHermit
	ButtonImageName		 = HICAHHermit
	WeaponLaunchBone	 = PRIMARY WizStaff02_FXBO
End

//--------------------------------------------------------------------------------------------------------------------------------------
// TROLL Upgrade_CreateAHero_ClassServantsOfSauron/Upgrade_CreateAHero_SubClass_0	
ModelConditionState	= CREATE_A_HERO_10
	Model				 = CHSS_TL_U_SKN
	Skeleton			 = CHSS_TL_U_SKL
	ModelAnimationPrefix = CHSS_TL
	PortraitImageName	 = CPTroll
	ButtonImageName		 = HICAHTroll
	WeaponLaunchBone	= PRIMARY Bat_HandL
End
// TROLL Upgrade_CreateAHeroMapMode Upgrade_CreateAHero_ClassServantsOfSauron/Upgrade_CreateAHero_SubClass_0	
ModelConditionState	= CREATE_A_HERO_11
	Model				 = CHSS_TL_C_SKN
	Skeleton			 = CHSS_TL_C_SKL
	ModelAnimationPrefix = CHSS_TL
	PortraitImageName	 = CPTroll
	ButtonImageName		 = HICAHTroll
	WeaponLaunchBone	= PRIMARY Bat_HandL
End

//--------------------------------------------------------------------------------------------------------------------------------------
// ELF ARCHER Upgrade_CreateAHero_ClassArcher / Upgrade_CreateAHero_SubClass_0
ModelConditionState	= CREATE_A_HERO_12 INVISIBLE_STEALTH
	Model				 = CHAR_EL_U_SKN
	Skeleton			 = CHAR_AR_U_SKL
	ModelAnimationPrefix = CHAR_AR
	PortraitImageName	 = CPMaleElfArcher
	ButtonImageName		 = HICAHMaleElfArcher
	ParticleSysBone		= NONE Predator FollowBone:Yes Persist:SPAWN PersistID:100
	ParticleSysBone		= NONE Predator02 FollowBone:Yes Persist:SPAWN PersistID:101
	WeaponLaunchBone	= PRIMARY ARROW
End
ModelConditionState	= CREATE_A_HERO_12
	Model				 = CHAR_EL_U_SKN
	Skeleton			 = CHAR_AR_U_SKL
	ModelAnimationPrefix = CHAR_AR
	PortraitImageName	 = CPMaleElfArcher
	ButtonImageName		 = HICAHMaleElfArcher
	ParticleSysBone		= NONE Predator FollowBone:Yes Persist:HOLD PersistID:100
	ParticleSysBone		= NONE Predator02 FollowBone:Yes Persist:HOLD PersistID:101
	WeaponLaunchBone	= PRIMARY ARROW
End
// ELF ARCHER Upgrade_CreateAHeroMapMode Upgrade_CreateAHero_ClassArcher / Upgrade_CreateAHero_SubClass_0
ModelConditionState	= CREATE_A_HERO_13 INVISIBLE_STEALTH
	Model				 = CHAR_EL_C_SKN
	Skeleton			 = CHAR_AR_C_SKL
	ModelAnimationPrefix = CHAR_AR
	PortraitImageName	 = CPMaleElfArcher
	ButtonImageName		 = HICAHMaleElfArcher
	ParticleSysBone		= NONE Predator FollowBone:Yes Persist:SPAWN PersistID:100
	ParticleSysBone		= NONE Predator02 FollowBone:Yes Persist:SPAWN PersistID:101
	WeaponLaunchBone	= PRIMARY ARROW
End
ModelConditionState	= CREATE_A_HERO_13
	Model				 = CHAR_EL_C_SKN
	Skeleton			 = CHAR_AR_C_SKL
	ModelAnimationPrefix = CHAR_AR
	PortraitImageName	 = CPMaleElfArcher
	ButtonImageName		 = HICAHMaleElfArcher
	ParticleSysBone		= NONE Predator FollowBone:Yes Persist:HOLD PersistID:100
	ParticleSysBone		= NONE Predator02 FollowBone:Yes Persist:HOLD PersistID:101
	WeaponLaunchBone	= PRIMARY ARROW
End

//--------------------------------------------------------------------------------------------------------------------------------------
// FEMALE ELVEN ARCHER Upgrade_CreateAHero_ClassArcher Upgrade_CreateAHero_SubClass_1
ModelConditionState	= CREATE_A_HERO_14 INVISIBLE_STEALTH
	Model				 = CHAR_FE_U_SKN
	Skeleton			 = CHAR_FE_U_SKL
	ModelAnimationPrefix = CHAR_FE
	PortraitImageName	 = CPFemaleElfArcher
	ButtonImageName		 = HICAHFemaleElvenArcher
	WeaponLaunchBone	= PRIMARY B_Hand_L
	ParticleSysBone		= NONE Predator FollowBone:Yes Persist:SPAWN PersistID:100
	ParticleSysBone		= NONE Predator02 FollowBone:Yes Persist:SPAWN PersistID:101
	WeaponLaunchBone	= PRIMARY ARROW
End
ModelConditionState	= CREATE_A_HERO_14
	Model				 = CHAR_FE_U_SKN
	Skeleton			 = CHAR_FE_U_SKL
	ModelAnimationPrefix = CHAR_FE
	PortraitImageName	 = CPFemaleElfArcher
	ButtonImageName		 = HICAHFemaleElvenArcher
	WeaponLaunchBone	= PRIMARY B_Hand_L
	ParticleSysBone		= NONE Predator FollowBone:Yes Persist:HOLD PersistID:100
	ParticleSysBone		= NONE Predator02 FollowBone:Yes Persist:HOLD PersistID:101
	WeaponLaunchBone	= PRIMARY ARROW
End
// FEMALE ELVEN ARCHER Upgrade_CreateAHeroMapMode Upgrade_CreateAHero_ClassArcher Upgrade_CreateAHero_SubClass_1
ModelConditionState	= CREATE_A_HERO_15 INVISIBLE_STEALTH
	Model				 = CHAR_FE_C_SKN
	Skeleton			 = CHAR_FE_C_SKL
	ModelAnimationPrefix = CHAR_FE
	PortraitImageName	 = CPFemaleElfArcher
	ButtonImageName		 = HICAHFemaleElvenArcher
	WeaponLaunchBone	= PRIMARY B_Hand_L
	ParticleSysBone		= NONE Predator FollowBone:Yes Persist:SPAWN PersistID:100
	ParticleSysBone		= NONE Predator02 FollowBone:Yes Persist:SPAWN PersistID:101
	WeaponLaunchBone	= PRIMARY ARROW
End
ModelConditionState	= CREATE_A_HERO_15
	Model				 = CHAR_FE_C_SKN
	Skeleton			 = CHAR_FE_C_SKL
	ModelAnimationPrefix = CHAR_FE
	PortraitImageName	 = CPFemaleElfArcher
	ButtonImageName		 = HICAHFemaleElvenArcher
	WeaponLaunchBone	= PRIMARY B_Hand_L
	ParticleSysBone		= NONE Predator FollowBone:Yes Persist:HOLD PersistID:100
	ParticleSysBone		= NONE Predator02 FollowBone:Yes Persist:HOLD PersistID:101
	WeaponLaunchBone	= PRIMARY ARROW
End

//--------------------------------------------------------------------------------------------------------------------------------------
// CORRUPTED MAN #1 Upgrade_CreateAHero_ClassCorruptedMan_SubClass_0
ModelConditionState	= CREATE_A_HERO_16 INVISIBLE_STEALTH
	Model				 = CHCM_CM_U_SKN1
	Skeleton			 = CHCM_CM_U_SKL
	ModelAnimationPrefix = CHCM_CM
	PortraitImageName	 = CPEasterling
	ButtonImageName		 = HICAHEasterling
	ParticleSysBone		= NONE Predator FollowBone:Yes Persist:SPAWN PersistID:100
	ParticleSysBone		= NONE Predator02 FollowBone:Yes Persist:SPAWN PersistID:101
	WeaponLaunchBone	= PRIMARY ARROW
End
ModelConditionState	= CREATE_A_HERO_16
	Model				 = CHCM_CM_U_SKN1
	Skeleton			 = CHCM_CM_U_SKL
	ModelAnimationPrefix = CHCM_CM
	PortraitImageName	 = CPEasterling
	ButtonImageName		 = HICAHEasterling
	ParticleSysBone		= NONE Predator FollowBone:Yes Persist:HOLD PersistID:100
	ParticleSysBone		= NONE Predator02 FollowBone:Yes Persist:HOLD PersistID:101
	WeaponLaunchBone	= PRIMARY ARROW
End
// CORRUPTED MAN #1 Upgrade_CreateAHeroMapMode Upgrade_CreateAHero_ClassCorruptedMan_SubClass_0
ModelConditionState	= CREATE_A_HERO_17 INVISIBLE_STEALTH
	Model				 = CHCM_CM_C_SKN
	Skeleton			 = CHCM_CM_C_SKL
	ModelAnimationPrefix = CHCM_CM
	PortraitImageName	 = CPEasterling
	ButtonImageName		 = HICAHEasterling
	ParticleSysBone		= NONE Predator FollowBone:Yes Persist:SPAWN PersistID:100
	ParticleSysBone		= NONE Predator02 FollowBone:Yes Persist:SPAWN PersistID:101
	WeaponLaunchBone	= PRIMARY ARROW
End
ModelConditionState	= CREATE_A_HERO_17
	Model				 = CHCM_CM_C_SKN
	Skeleton			 = CHCM_CM_C_SKL
	ModelAnimationPrefix = CHCM_CM
	PortraitImageName	 = CPEasterling
	ButtonImageName		 = HICAHEasterling
	ParticleSysBone		= NONE Predator FollowBone:Yes Persist:HOLD PersistID:100
	ParticleSysBone		= NONE Predator02 FollowBone:Yes Persist:HOLD PersistID:101
	WeaponLaunchBone	= PRIMARY ARROW
End

//--------------------------------------------------------------------------------------------------------------------------------------
// CORRUPTED MAN #2 Upgrade_CreateAHero_ClassCorruptedMan_SubClass_1
ModelConditionState	= CREATE_A_HERO_18 INVISIBLE_STEALTH
	Model				 = CHCM_FN_U_SKN
	Skeleton			 = CHCM_CM_U_SKL
	ModelAnimationPrefix = CHCM_CM
	PortraitImageName	 = CPHaradrim
	ButtonImageName		 = HICAHHaradrim
	ParticleSysBone		= NONE Predator FollowBone:Yes Persist:SPAWN PersistID:100
	ParticleSysBone		= NONE Predator02 FollowBone:Yes Persist:SPAWN PersistID:101
	WeaponLaunchBone	= PRIMARY ARROW
End
ModelConditionState	= CREATE_A_HERO_18
	Model				 = CHCM_FN_U_SKN
	Skeleton			 = CHCM_CM_U_SKL
	ModelAnimationPrefix = CHCM_CM
	PortraitImageName	 = CPHaradrim
	ButtonImageName		 = HICAHHaradrim
	ParticleSysBone		= NONE Predator FollowBone:Yes Persist:HOLD PersistID:100
	ParticleSysBone		= NONE Predator02 FollowBone:Yes Persist:HOLD PersistID:101
	WeaponLaunchBone	= PRIMARY ARROW
End
// CORRUPTED MAN #2 Upgrade_CreateAHeroMapMode Upgrade_CreateAHero_ClassCorruptedMan_SubClass_1
ModelConditionState	= CREATE_A_HERO_19 INVISIBLE_STEALTH
	Model				 = CHCM_FN_C_SKN
	Skeleton			 = CHCM_CM_C_SKL
	ModelAnimationPrefix = CHCM_CM
	PortraitImageName	 = CPHaradrim
	ButtonImageName		 = HICAHHaradrim
	ParticleSysBone		= NONE Predator FollowBone:Yes Persist:SPAWN PersistID:100
	ParticleSysBone		= NONE Predator02 FollowBone:Yes Persist:SPAWN PersistID:101
	WeaponLaunchBone	= PRIMARY ARROW
End
ModelConditionState	= CREATE_A_HERO_19
	Model				 = CHCM_FN_C_SKN
	Skeleton			 = CHCM_CM_C_SKL
	ModelAnimationPrefix = CHCM_CM
	PortraitImageName	 = CPHaradrim
	ButtonImageName		 = HICAHHaradrim
	ParticleSysBone		= NONE Predator FollowBone:Yes Persist:HOLD PersistID:100
	ParticleSysBone		= NONE Predator02 FollowBone:Yes Persist:HOLD PersistID:101
	WeaponLaunchBone	= PRIMARY ARROW
End


//--------------------------------------------------------------------------------------------------------------------------------------
// DWARF Taskmaster		Upgrade_CreateAHero_ClassDwarf_SubClass_0
ModelConditionState	= CREATE_A_HERO_20
	Model				 = CHDW_TM_U_SKN
	Skeleton			 = CHDW_DW_U_SKL
	ModelAnimationPrefix = CHDW_DW
	PortraitImageName	 = CPDwarfTaskmaster
	ButtonImageName		 = HICAHDwarfTaskmaster
	WeaponLaunchBone	= TERTIARY Axe02
End
// DWARF Taskmaster Upgrade_CreateAHeroMapMode Upgrade_CreateAHero_ClassDwarf_SubClass_0
ModelConditionState	= CREATE_A_HERO_21
	Model				 = CHDW_TM_C_SKN
	Skeleton			 = CHDW_DW_C_SKL
	ModelAnimationPrefix = CHDW_DW
	PortraitImageName	 = CPDwarfTaskmaster
	ButtonImageName		 = HICAHDwarfTaskmaster
	WeaponLaunchBone	= TERTIARY Axe02
End
//--------------------------------------------------------------------------------------------------------------------------------------
// DWARF Sage Upgrade_CreateAHero_ClassDwarf_SubClass_1
ModelConditionState	= CREATE_A_HERO_22
	Model				 = CHDW_SG_U_SKN // Change
	Skeleton			 = CHDW_DW_U_SKL
	ModelAnimationPrefix = CHDW_DW
	PortraitImageName	 = CPDwarfSage
	ButtonImageName		 = HICAHDwarfSage
	WeaponLaunchBone	= TERTIARY Axe02
End
// DWARF Sage Upgrade_CreateAHeroMapMode Upgrade_CreateAHero_ClassDwarf_SubClass_1
ModelConditionState	= CREATE_A_HERO_23
	Model				 = CHDW_SG_C_SKN // Change
	Skeleton			 = CHDW_DW_C_SKL
	ModelAnimationPrefix = CHDW_DW
	PortraitImageName	 = CPDwarfSage
	ButtonImageName		 = HICAHDwarfSage
	WeaponLaunchBone	= TERTIARY Axe02
End

//--------------------------------------------------------------------------------------------------------------------------------------
// ORC RAIDER Upgrade_CreateAHero_ClassServantsOfSauron_SubClass_2
ModelConditionState	= CREATE_A_HERO_24
	Model				 = CHSS_OR_U_SKN
	Skeleton			 = CHSS_GB_U_SKL
	ModelAnimationPrefix = CHSS_GB
	PortraitImageName	 = CPOrcRaider
	ButtonImageName		 = HICAHOrcRaider
	WeaponLaunchBone	= PRIMARY B_HAND_R
End
// ORC RAIDER Upgrade_CreateAHeroMapMode Upgrade_CreateAHero_ClassServantsOfSauron_SubClass_2
ModelConditionState	= CREATE_A_HERO_25
	Model				 = CHSS_OR_C_SKN
	Skeleton			 = CHSS_GB_C_SKL
	ModelAnimationPrefix = CHSS_GB
	PortraitImageName	 = CPOrcRaider
	ButtonImageName		 = HICAHOrcRaider
	WeaponLaunchBone	= PRIMARY B_HAND_R
End

//--------------------------------------------------------------------------------------------------------------------------------------
// URUK Upgrade_CreateAHero_ClassServantsOfSauron_SubClass_3
ModelConditionState	= CREATE_A_HERO_26
	Model				 = CHSS_UT_U_SKN
	Skeleton			 = CHSS_UK_U_SKL
	ModelAnimationPrefix = CHSS_UK
	PortraitImageName	 = CPUruk
	ButtonImageName		 = HICAHUrukhai
	WeaponLaunchBone	= PRIMARY B_HandR
End
// URUK Upgrade_CreateAHeroMapMode Upgrade_CreateAHero_ClassServantsOfSauron_SubClass_3
ModelConditionState	= CREATE_A_HERO_27
	Model				 = CHSS_UK_C_SKN
	Skeleton			 = CHSS_UK_C_SKL
	ModelAnimationPrefix = CHSS_UK
	PortraitImageName	 = CPUruk
	ButtonImageName		 = HICAHUrukhai
	WeaponLaunchBone	= PRIMARY B_HandR
End

