//-------------------------------------------------------------------
// Create A Hero Attribute Modifiers
// Created by: Andrew Luby
// 09/26/2005
//-------------------------------------------------------------------

// Armor Attribute
//-------------------------------------------------------------------
Behavior = AttributeModifierUpgrade ModuleTag_ArmorAttribute01
	TriggeredBy			= Upgrade_ArmorAttribute01
	AttributeModifier	= ArmorAttribute01
End
Behavior = AttributeModifierUpgrade ModuleTag_ArmorAttribute02
	TriggeredBy			= Upgrade_ArmorAttribute02
	AttributeModifier	= ArmorAttribute02
End
Behavior = AttributeModifierUpgrade ModuleTag_ArmorAttribute03
	TriggeredBy			= Upgrade_ArmorAttribute03
	AttributeModifier	= ArmorAttribute03
End
Behavior = AttributeModifierUpgrade ModuleTag_ArmorAttribute04
	TriggeredBy			= Upgrade_ArmorAttribute04
	AttributeModifier	= ArmorAttribute04
End
Behavior = AttributeModifierUpgrade ModuleTag_ArmorAttribute05
	TriggeredBy			= Upgrade_ArmorAttribute05
	AttributeModifier	= ArmorAttribute05
End
Behavior = AttributeModifierUpgrade ModuleTag_ArmorAttribute06
	TriggeredBy			= Upgrade_ArmorAttribute06
	AttributeModifier	= ArmorAttribute06
End
Behavior = AttributeModifierUpgrade ModuleTag_ArmorAttribute07
	TriggeredBy			= Upgrade_ArmorAttribute07
	AttributeModifier	= ArmorAttribute07
End
Behavior = AttributeModifierUpgrade ModuleTag_ArmorAttribute08
	TriggeredBy			= Upgrade_ArmorAttribute08
	AttributeModifier	= ArmorAttribute08
End
Behavior = AttributeModifierUpgrade ModuleTag_ArmorAttribute09
	TriggeredBy			= Upgrade_ArmorAttribute09
	AttributeModifier	= ArmorAttribute09
End
Behavior = AttributeModifierUpgrade ModuleTag_ArmorAttribute10
	TriggeredBy			= Upgrade_ArmorAttribute10
	AttributeModifier	= ArmorAttribute10
End
Behavior = AttributeModifierUpgrade ModuleTag_ArmorAttribute11
	TriggeredBy			= Upgrade_ArmorAttribute11
	AttributeModifier	= ArmorAttribute11
End
Behavior = AttributeModifierUpgrade ModuleTag_ArmorAttribute12
	TriggeredBy			= Upgrade_ArmorAttribute12
	AttributeModifier	= ArmorAttribute12
End
Behavior = AttributeModifierUpgrade ModuleTag_ArmorAttribute13
TriggeredBy			= Upgrade_ArmorAttribute13
	AttributeModifier	= ArmorAttribute13
End
Behavior = AttributeModifierUpgrade ModuleTag_ArmorAttribute14
	TriggeredBy			= Upgrade_ArmorAttribute14
	AttributeModifier	= ArmorAttribute14
End
Behavior = AttributeModifierUpgrade ModuleTag_ArmorAttribute15
	TriggeredBy			= Upgrade_ArmorAttribute15
	AttributeModifier	= ArmorAttribute15
End
Behavior = AttributeModifierUpgrade ModuleTag_ArmorAttribute16
	TriggeredBy			= Upgrade_ArmorAttribute16
	AttributeModifier	= ArmorAttribute16
End
Behavior = AttributeModifierUpgrade ModuleTag_ArmorAttribute17
	TriggeredBy			= Upgrade_ArmorAttribute17
	AttributeModifier	= ArmorAttribute17
End
Behavior = AttributeModifierUpgrade ModuleTag_ArmorAttribute18
	TriggeredBy			= Upgrade_ArmorAttribute18
	AttributeModifier	= ArmorAttribute18
End
Behavior = AttributeModifierUpgrade ModuleTag_ArmorAttribute19
	TriggeredBy			= Upgrade_ArmorAttribute19
	AttributeModifier	= ArmorAttribute19
End
Behavior = AttributeModifierUpgrade ModuleTag_ArmorAttribute20
	TriggeredBy			= Upgrade_ArmorAttribute20
	AttributeModifier	= ArmorAttribute20
End

// DamageMultAttribute
//-------------------------------------------------------------------
Behavior = AttributeModifierUpgrade ModuleTag_DamageMultAttribute01
	TriggeredBy			= Upgrade_DamageMultAttribute01
	AttributeModifier	= DamageMultAttribute01
End
Behavior = AttributeModifierUpgrade ModuleTag_DamageMultAttribute02
	TriggeredBy			= Upgrade_DamageMultAttribute02
	AttributeModifier	= DamageMultAttribute02
End
Behavior = AttributeModifierUpgrade ModuleTag_DamageMultAttribute03
	TriggeredBy			= Upgrade_DamageMultAttribute03
	AttributeModifier	= DamageMultAttribute03
End
Behavior = AttributeModifierUpgrade ModuleTag_DamageMultAttribute04
	TriggeredBy			= Upgrade_DamageMultAttribute04
	AttributeModifier	= DamageMultAttribute04
End
Behavior = AttributeModifierUpgrade ModuleTag_DamageMultAttribute05
	TriggeredBy			= Upgrade_DamageMultAttribute05
	AttributeModifier	= DamageMultAttribute05
End
Behavior = AttributeModifierUpgrade ModuleTag_DamageMultAttribute06
	TriggeredBy			= Upgrade_DamageMultAttribute06
	AttributeModifier	= DamageMultAttribute06
End
Behavior = AttributeModifierUpgrade ModuleTag_DamageMultAttribute07
	TriggeredBy			= Upgrade_DamageMultAttribute07
	AttributeModifier	= DamageMultAttribute07
End
Behavior = AttributeModifierUpgrade ModuleTag_DamageMultAttribute08
	TriggeredBy			= Upgrade_DamageMultAttribute08
	AttributeModifier	= DamageMultAttribute08
End
Behavior = AttributeModifierUpgrade ModuleTag_DamageMultAttribute09
	TriggeredBy			= Upgrade_DamageMultAttribute09
	AttributeModifier	= DamageMultAttribute09
End
Behavior = AttributeModifierUpgrade ModuleTag_DamageMultAttribute10
	TriggeredBy			= Upgrade_DamageMultAttribute10
	AttributeModifier	= DamageMultAttribute10
End
Behavior = AttributeModifierUpgrade ModuleTag_DamageMultAttribute11
	TriggeredBy			= Upgrade_DamageMultAttribute11
	AttributeModifier	= DamageMultAttribute11
End
Behavior = AttributeModifierUpgrade ModuleTag_DamageMultAttribute12
	TriggeredBy			= Upgrade_DamageMultAttribute12
	AttributeModifier	= DamageMultAttribute12
End
Behavior = AttributeModifierUpgrade ModuleTag_DamageMultAttribute13
	TriggeredBy			= Upgrade_DamageMultAttribute13
	AttributeModifier	= DamageMultAttribute13
End
Behavior = AttributeModifierUpgrade ModuleTag_DamageMultAttribute14
	TriggeredBy			= Upgrade_DamageMultAttribute14
	AttributeModifier	= DamageMultAttribute14
End
Behavior = AttributeModifierUpgrade ModuleTag_DamageMultAttribute15
	TriggeredBy			= Upgrade_DamageMultAttribute15
	AttributeModifier	= DamageMultAttribute15
End
Behavior = AttributeModifierUpgrade ModuleTag_DamageMultAttribute16
	TriggeredBy			= Upgrade_DamageMultAttribute16
	AttributeModifier	= DamageMultAttribute16
End
Behavior = AttributeModifierUpgrade ModuleTag_DamageMultAttribute17
	TriggeredBy			= Upgrade_DamageMultAttribute17
	AttributeModifier	= DamageMultAttribute17
End
Behavior = AttributeModifierUpgrade ModuleTag_DamageMultAttribute18
	TriggeredBy			= Upgrade_DamageMultAttribute18
	AttributeModifier	= DamageMultAttribute18
End
Behavior = AttributeModifierUpgrade ModuleTag_DamageMultAttribute19
	TriggeredBy			= Upgrade_DamageMultAttribute19
	AttributeModifier	= DamageMultAttribute19
End
Behavior = AttributeModifierUpgrade ModuleTag_DamageMultAttribute20
	TriggeredBy			= Upgrade_DamageMultAttribute20
	AttributeModifier	= DamageMultAttribute20
End

// VisionAttribute
//-------------------------------------------------------------------
Behavior = AttributeModifierUpgrade ModuleTag_VisionAttribute01
	TriggeredBy			= Upgrade_VisionAttribute01
	AttributeModifier	= VisionAttribute01
End
Behavior = AttributeModifierUpgrade ModuleTag_VisionAttribute02
	TriggeredBy			= Upgrade_VisionAttribute02
	AttributeModifier	= VisionAttribute02
End
Behavior = AttributeModifierUpgrade ModuleTag_VisionAttribute03
	TriggeredBy			= Upgrade_VisionAttribute03
	AttributeModifier	= VisionAttribute03
End
Behavior = AttributeModifierUpgrade ModuleTag_VisionAttribute04
	TriggeredBy			= Upgrade_VisionAttribute04
	AttributeModifier	= VisionAttribute04
End
Behavior = AttributeModifierUpgrade ModuleTag_VisionAttribute05
	TriggeredBy			= Upgrade_VisionAttribute05
	AttributeModifier	= VisionAttribute05
End
Behavior = AttributeModifierUpgrade ModuleTag_VisionAttribute06
	TriggeredBy			= Upgrade_VisionAttribute06
	AttributeModifier	= VisionAttribute06
End
Behavior = AttributeModifierUpgrade ModuleTag_VisionAttribute07
	TriggeredBy			= Upgrade_VisionAttribute07
	AttributeModifier	= VisionAttribute07
End
Behavior = AttributeModifierUpgrade ModuleTag_VisionAttribute08
	TriggeredBy			= Upgrade_VisionAttribute08
	AttributeModifier	= VisionAttribute08
End
Behavior = AttributeModifierUpgrade ModuleTag_VisionAttribute09
	TriggeredBy			= Upgrade_VisionAttribute09
	AttributeModifier	= VisionAttribute09
End
Behavior = AttributeModifierUpgrade ModuleTag_VisionAttribute10
	TriggeredBy			= Upgrade_VisionAttribute10
	AttributeModifier	= VisionAttribute10
End
Behavior = AttributeModifierUpgrade ModuleTag_VisionAttribute11
	TriggeredBy			= Upgrade_VisionAttribute11
	AttributeModifier	= VisionAttribute11
End
Behavior = AttributeModifierUpgrade ModuleTag_VisionAttribute12
	TriggeredBy			= Upgrade_VisionAttribute12
	AttributeModifier	= VisionAttribute12
End
Behavior = AttributeModifierUpgrade ModuleTag_VisionAttribute13
	TriggeredBy			= Upgrade_VisionAttribute13
	AttributeModifier	= VisionAttribute13
End
Behavior = AttributeModifierUpgrade ModuleTag_VisionAttribute14
	TriggeredBy			= Upgrade_VisionAttribute14
	AttributeModifier	= VisionAttribute14
End
Behavior = AttributeModifierUpgrade ModuleTag_VisionAttribute15
	TriggeredBy			= Upgrade_VisionAttribute15
	AttributeModifier	= VisionAttribute15
End
Behavior = AttributeModifierUpgrade ModuleTag_VisionAttribute16
	TriggeredBy			= Upgrade_VisionAttribute16
	AttributeModifier	= VisionAttribute16
End
Behavior = AttributeModifierUpgrade ModuleTag_VisionAttribute17
	TriggeredBy			= Upgrade_VisionAttribute17
	AttributeModifier	= VisionAttribute17
End
Behavior = AttributeModifierUpgrade ModuleTag_VisionAttribute18
	TriggeredBy			= Upgrade_VisionAttribute18
	AttributeModifier	= VisionAttribute18
End
Behavior = AttributeModifierUpgrade ModuleTag_VisionAttribute19
	TriggeredBy			= Upgrade_VisionAttribute19
	AttributeModifier	= VisionAttribute19
End
Behavior = AttributeModifierUpgrade ModuleTag_VisionAttribute20
	TriggeredBy			= Upgrade_VisionAttribute20
	AttributeModifier	= VisionAttribute20
End

// AutoHealAttribute
//-------------------------------------------------------------------
Behavior = AttributeModifierUpgrade ModuleTag_AutoHealAttribute01
	TriggeredBy			= Upgrade_AutoHealAttribute01
	AttributeModifier	= AutoHealAttribute01
End
Behavior = AttributeModifierUpgrade ModuleTag_AutoHealAttribute02
	TriggeredBy			= Upgrade_AutoHealAttribute02
	AttributeModifier	= AutoHealAttribute02
End
Behavior = AttributeModifierUpgrade ModuleTag_AutoHealAttribute03
	TriggeredBy			= Upgrade_AutoHealAttribute03
	AttributeModifier	= AutoHealAttribute03
End
Behavior = AttributeModifierUpgrade ModuleTag_AutoHealAttribute04
	TriggeredBy			= Upgrade_AutoHealAttribute04
	AttributeModifier	= AutoHealAttribute04
End
Behavior = AttributeModifierUpgrade ModuleTag_AutoHealAttribute05
	TriggeredBy			= Upgrade_AutoHealAttribute05
	AttributeModifier	= AutoHealAttribute05
End
Behavior = AttributeModifierUpgrade ModuleTag_AutoHealAttribute06
	TriggeredBy			= Upgrade_AutoHealAttribute06
	AttributeModifier	= AutoHealAttribute06
End
Behavior = AttributeModifierUpgrade ModuleTag_AutoHealAttribute07
	TriggeredBy			= Upgrade_AutoHealAttribute07
	AttributeModifier	= AutoHealAttribute07
End
Behavior = AttributeModifierUpgrade ModuleTag_AutoHealAttribute08
	TriggeredBy			= Upgrade_AutoHealAttribute08
	AttributeModifier	= AutoHealAttribute08
End
Behavior = AttributeModifierUpgrade ModuleTag_AutoHealAttribute09
	TriggeredBy			= Upgrade_AutoHealAttribute09
	AttributeModifier	= AutoHealAttribute09
End
Behavior = AttributeModifierUpgrade ModuleTag_AutoHealAttribute10
	TriggeredBy			= Upgrade_AutoHealAttribute10
	AttributeModifier	= AutoHealAttribute10
End
Behavior = AttributeModifierUpgrade ModuleTag_AutoHealAttribute11
	TriggeredBy			= Upgrade_AutoHealAttribute11
	AttributeModifier	= AutoHealAttribute11
End
Behavior = AttributeModifierUpgrade ModuleTag_AutoHealAttribute12
	TriggeredBy			= Upgrade_AutoHealAttribute12
	AttributeModifier	= AutoHealAttribute12
End
Behavior = AttributeModifierUpgrade ModuleTag_AutoHealAttribute13
	TriggeredBy			= Upgrade_AutoHealAttribute13
	AttributeModifier	= AutoHealAttribute13
End
Behavior = AttributeModifierUpgrade ModuleTag_AutoHealAttribute14
	TriggeredBy			= Upgrade_AutoHealAttribute14
	AttributeModifier	= AutoHealAttribute14
End
Behavior = AttributeModifierUpgrade ModuleTag_AutoHealAttribute15
	TriggeredBy			= Upgrade_AutoHealAttribute15
	AttributeModifier	= AutoHealAttribute15
End
Behavior = AttributeModifierUpgrade ModuleTag_AutoHealAttribute16
	TriggeredBy			= Upgrade_AutoHealAttribute16
	AttributeModifier	= AutoHealAttribute16
End
Behavior = AttributeModifierUpgrade ModuleTag_AutoHealAttribute17
	TriggeredBy			= Upgrade_AutoHealAttribute17
	AttributeModifier	= AutoHealAttribute17
End
Behavior = AttributeModifierUpgrade ModuleTag_AutoHealAttribute18
	TriggeredBy			= Upgrade_AutoHealAttribute18
	AttributeModifier	= AutoHealAttribute18
End
Behavior = AttributeModifierUpgrade ModuleTag_AutoHealAttribute19
	TriggeredBy			= Upgrade_AutoHealAttribute19
	AttributeModifier	= AutoHealAttribute19
End
Behavior = AttributeModifierUpgrade ModuleTag_AutoHealAttribute20
	TriggeredBy			= Upgrade_AutoHealAttribute20
	AttributeModifier	= AutoHealAttribute20
End

// HealthMultAttribute
//-------------------------------------------------------------------
Behavior = AttributeModifierUpgrade ModuleTag_HealthMultAttribute01
	TriggeredBy			= Upgrade_HealthMultAttribute01
	AttributeModifier	= HealthMultAttribute01
End
Behavior = AttributeModifierUpgrade ModuleTag_HealthMultAttribute02
	TriggeredBy			= Upgrade_HealthMultAttribute02
	AttributeModifier	= HealthMultAttribute02
End
Behavior = AttributeModifierUpgrade ModuleTag_HealthMultAttribute03
	TriggeredBy			= Upgrade_HealthMultAttribute03
	AttributeModifier	= HealthMultAttribute03
End
Behavior = AttributeModifierUpgrade ModuleTag_HealthMultAttribute04
	TriggeredBy			= Upgrade_HealthMultAttribute04
	AttributeModifier	= HealthMultAttribute04
End
Behavior = AttributeModifierUpgrade ModuleTag_HealthMultAttribute05
	TriggeredBy			= Upgrade_HealthMultAttribute05
	AttributeModifier	= HealthMultAttribute05
End
Behavior = AttributeModifierUpgrade ModuleTag_HealthMultAttribute06
	TriggeredBy			= Upgrade_HealthMultAttribute06
	AttributeModifier	= HealthMultAttribute06
End
Behavior = AttributeModifierUpgrade ModuleTag_HealthMultAttribute07
	TriggeredBy			= Upgrade_HealthMultAttribute07
	AttributeModifier	= HealthMultAttribute07
End
Behavior = AttributeModifierUpgrade ModuleTag_HealthMultAttribute08
	TriggeredBy			= Upgrade_HealthMultAttribute08
	AttributeModifier	= HealthMultAttribute08
End
Behavior = AttributeModifierUpgrade ModuleTag_HealthMultAttribute09
	TriggeredBy			= Upgrade_HealthMultAttribute09
	AttributeModifier	= HealthMultAttribute09
End
Behavior = AttributeModifierUpgrade ModuleTag_HealthMultAttribute10
	TriggeredBy			= Upgrade_HealthMultAttribute10
	AttributeModifier	= HealthMultAttribute10
End
Behavior = AttributeModifierUpgrade ModuleTag_HealthMultAttribute11
	TriggeredBy			= Upgrade_HealthMultAttribute11
	AttributeModifier	= HealthMultAttribute11
End
Behavior = AttributeModifierUpgrade ModuleTag_HealthMultAttribute12
	TriggeredBy			= Upgrade_HealthMultAttribute12
	AttributeModifier	= HealthMultAttribute12
End
Behavior = AttributeModifierUpgrade ModuleTag_HealthMultAttribute13
	TriggeredBy			= Upgrade_HealthMultAttribute13
	AttributeModifier	= HealthMultAttribute13
End
Behavior = AttributeModifierUpgrade ModuleTag_HealthMultAttribute14
	TriggeredBy			= Upgrade_HealthMultAttribute14
	AttributeModifier	= HealthMultAttribute14
End
Behavior = AttributeModifierUpgrade ModuleTag_HealthMultAttribute15
	TriggeredBy			= Upgrade_HealthMultAttribute15
	AttributeModifier	= HealthMultAttribute15
End
Behavior = AttributeModifierUpgrade ModuleTag_HealthMultAttribute16
	TriggeredBy			= Upgrade_HealthMultAttribute16
	AttributeModifier	= HealthMultAttribute16
End
Behavior = AttributeModifierUpgrade ModuleTag_HealthMultAttribute17
	TriggeredBy			= Upgrade_HealthMultAttribute17
	AttributeModifier	= HealthMultAttribute17
End
Behavior = AttributeModifierUpgrade ModuleTag_HealthMultAttribute18
	TriggeredBy			= Upgrade_HealthMultAttribute18
	AttributeModifier	= HealthMultAttribute18
End
Behavior = AttributeModifierUpgrade ModuleTag_HealthMultAttribute19
	TriggeredBy			= Upgrade_HealthMultAttribute19
	AttributeModifier	= HealthMultAttribute19
End
Behavior = AttributeModifierUpgrade ModuleTag_HealthMultAttribute20
	TriggeredBy			= Upgrade_HealthMultAttribute20
	AttributeModifier	= HealthMultAttribute20
End
