

//=====================================================================================================
// This Section contains the RemoveUpgradeUpgrades for Create A Hero Weapons
//=====================================================================================================
Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_CreateAHero_Upgrade_CHW01
	TriggeredBy		= Upgrade_CHW01 
	UpgradeGroupsToRemove = CreateAHero_Weapon
End
	
Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_CreateAHero_Upgrade_CHW02
	TriggeredBy		= Upgrade_CHW02 
	UpgradeGroupsToRemove = CreateAHero_Weapon
End

Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_CreateAHero_Upgrade_CHW03
	TriggeredBy		= Upgrade_CHW03 
	UpgradeGroupsToRemove = CreateAHero_Weapon
End

Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_CreateAHero_Upgrade_CHW04
	TriggeredBy		= Upgrade_CHW04 
	UpgradeGroupsToRemove = CreateAHero_Weapon
End

Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_CreateAHero_Upgrade_CHW05
	TriggeredBy		= Upgrade_CHW05 
	UpgradeGroupsToRemove = CreateAHero_Weapon
End

Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_CreateAHero_Upgrade_CHW06
	TriggeredBy		= Upgrade_CHW06 
	UpgradeGroupsToRemove = CreateAHero_Weapon
End

Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_CreateAHero_Upgrade_CHW07
	TriggeredBy		= Upgrade_CHW07 
	UpgradeGroupsToRemove = CreateAHero_Weapon
End

Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_CreateAHero_Upgrade_CHW08
	TriggeredBy		= Upgrade_CHW08 
	UpgradeGroupsToRemove = CreateAHero_Weapon
End

Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_CreateAHero_Upgrade_CHW09
	TriggeredBy		= Upgrade_CHW09 
	UpgradeGroupsToRemove = CreateAHero_Weapon
End

Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_CreateAHero_Upgrade_CHW10
	TriggeredBy		= Upgrade_CHW10 
	UpgradeGroupsToRemove = CreateAHero_Weapon
End

Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_CreateAHero_Upgrade_CHW11
	TriggeredBy		= Upgrade_CHW11 
	UpgradeGroupsToRemove = CreateAHero_Weapon
End

Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_CreateAHero_Upgrade_CHW12
	TriggeredBy		= Upgrade_CHW12 
	UpgradeGroupsToRemove = CreateAHero_Weapon
End

Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_CreateAHero_Upgrade_CHW13
	TriggeredBy		= Upgrade_CHW13 
	UpgradeGroupsToRemove = CreateAHero_Weapon
End

Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_CreateAHero_Upgrade_CHW14
	TriggeredBy		= Upgrade_CHW14 
	UpgradeGroupsToRemove = CreateAHero_Weapon
End

Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_CreateAHero_Upgrade_CHW15
	TriggeredBy		= Upgrade_CHW15 
	UpgradeGroupsToRemove = CreateAHero_Weapon
End

Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_CreateAHero_Upgrade_CHW16
	TriggeredBy		= Upgrade_CHW16 
	UpgradeGroupsToRemove = CreateAHero_Weapon
End

Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_CreateAHero_Upgrade_CHW17
	TriggeredBy		= Upgrade_CHW17 
	UpgradeGroupsToRemove = CreateAHero_Weapon
End

Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_CreateAHero_Upgrade_CHW18
	TriggeredBy		= Upgrade_CHW18 
	UpgradeGroupsToRemove = CreateAHero_Weapon
End

Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_CreateAHero_Upgrade_CHW19
	TriggeredBy		= Upgrade_CHW19 
	UpgradeGroupsToRemove = CreateAHero_Weapon
End

Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_CreateAHero_Upgrade_CHW20
	TriggeredBy		= Upgrade_CHW20 
	UpgradeGroupsToRemove = CreateAHero_Weapon
End

Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_CreateAHero_Upgrade_CHW21
	TriggeredBy		= Upgrade_CHW21 
	UpgradeGroupsToRemove = CreateAHero_Weapon
End

Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_CreateAHero_Upgrade_CHW22
	TriggeredBy		= Upgrade_CHW22 
	UpgradeGroupsToRemove = CreateAHero_Weapon
End

Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_CreateAHero_Upgrade_CHW23
	TriggeredBy		= Upgrade_CHW23 
	UpgradeGroupsToRemove = CreateAHero_Weapon
End

Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_CreateAHero_Upgrade_CHW24
	TriggeredBy		= Upgrade_CHW24 
	UpgradeGroupsToRemove = CreateAHero_Weapon
End

Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_CreateAHero_Upgrade_CHW25
	TriggeredBy		= Upgrade_CHW25 
	UpgradeGroupsToRemove = CreateAHero_Weapon
End

Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_CreateAHero_Upgrade_CHW26
	TriggeredBy		= Upgrade_CHW26 
	UpgradeGroupsToRemove = CreateAHero_Weapon
End

Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_CreateAHero_Upgrade_CHW27
	TriggeredBy		= Upgrade_CHW27 
	UpgradeGroupsToRemove = CreateAHero_Weapon
End

Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_CreateAHero_Upgrade_CHW28
	TriggeredBy		= Upgrade_CHW28 
	UpgradeGroupsToRemove = CreateAHero_Weapon
End

Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_CreateAHero_Upgrade_CHW29
	TriggeredBy		= Upgrade_CHW29 
	UpgradeGroupsToRemove = CreateAHero_Weapon
End

Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_CreateAHero_Upgrade_CHW30
	TriggeredBy		= Upgrade_CHW30 
	UpgradeGroupsToRemove = CreateAHero_Weapon
End

Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_CreateAHero_Upgrade_CHW31
	TriggeredBy		= Upgrade_CHW31 
	UpgradeGroupsToRemove = CreateAHero_Weapon
End

Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_CreateAHero_Upgrade_CHW32
	TriggeredBy		= Upgrade_CHW32
	UpgradeGroupsToRemove = CreateAHero_Weapon
End

Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_CreateAHero_Upgrade_CHW33
	TriggeredBy		= Upgrade_CHW33
	UpgradeGroupsToRemove = CreateAHero_Weapon
End

Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_CreateAHero_Upgrade_CHW34
	TriggeredBy		= Upgrade_CHW34
	UpgradeGroupsToRemove = CreateAHero_Weapon
End

Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_CreateAHero_Upgrade_CHW35
	TriggeredBy		= Upgrade_CHW35 
	UpgradeGroupsToRemove = CreateAHero_Weapon
End

Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_CreateAHero_Upgrade_CHW36
	TriggeredBy		= Upgrade_CHW36
	UpgradeGroupsToRemove = CreateAHero_Weapon
End

Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_CreateAHero_Upgrade_CHW37
	TriggeredBy		= Upgrade_CHW37 
	UpgradeGroupsToRemove = CreateAHero_Weapon
End

Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_CreateAHero_Upgrade_CHW308
	TriggeredBy		= Upgrade_CHW38 
	UpgradeGroupsToRemove = CreateAHero_Weapon
End

Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_CreateAHero_Upgrade_CHW39
	TriggeredBy		= Upgrade_CHW39 
	UpgradeGroupsToRemove = CreateAHero_Weapon
End

Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_CreateAHero_Upgrade_CHW40
	TriggeredBy		= Upgrade_CHW40 
	UpgradeGroupsToRemove = CreateAHero_Weapon
End

Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_CreateAHero_Upgrade_CHW41
	TriggeredBy		= Upgrade_CHW41 
	UpgradeGroupsToRemove = CreateAHero_Weapon
End

Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_CreateAHero_Upgrade_CHW42
	TriggeredBy		= Upgrade_CHW42 
	UpgradeGroupsToRemove = CreateAHero_Weapon
End



//=====================================================================================================
// This section contains the RemoveUpgradeUpgrades for the Create a Hero Bling
//=====================================================================================================
	
// Shoulder Plates
	Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_CreateAHero_Upgrade_CorruptedMan_1_CHSP01
		TriggeredBy		= Upgrade_CorruptedMan_1_CHSP01
		UpgradeGroupsToRemove = CreateAHero_ShoulderPlates
	End
	Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_CreateAHero_Upgrade_CorruptedMan_1_CHSP02
		TriggeredBy		= Upgrade_CorruptedMan_1_CHSP02
		UpgradeGroupsToRemove = CreateAHero_ShoulderPlates
	End
	Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_CreateAHero_Upgrade_CorruptedMan_1_CHSP03     // White Corrupted
		TriggeredBy		= Upgrade_CM01_CHBOD04
		UpgradeGroupsToRemove = CreateAHero_Body
	End
	Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_CreateAHero_Upgrade_CorruptedMan_1_CHSP05     // White Corrupted
		TriggeredBy		= Upgrade_CM01_CHBOD05
		UpgradeGroupsToRemove = CreateAHero_Body
	End
	Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_CreateAHero_Upgrade_CorruptedMan_1_CHSP04     // Indian Corrupted
		TriggeredBy		= Upgrade_CM02_CHBOD05
		UpgradeGroupsToRemove = CreateAHero_Body
	End
	Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_CreateAHero_Upgrade_CorruptedMan_1_CHSP06     // Indian Corrupted
		TriggeredBy		= Upgrade_CM02_CHBOD04
		UpgradeGroupsToRemove = CreateAHero_Body
	End
	Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_CreateAHero_Upgrade_CorruptedMan_1_CHSP07
		TriggeredBy		= Upgrade_CorruptedMan_1_CHSP07
		UpgradeGroupsToRemove = CreateAHero_ShoulderPlates
	End
	Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_CreateAHero_Upgrade_DWARF_CHSP01
		TriggeredBy		= Upgrade_DWARF_CHSP01
		UpgradeGroupsToRemove = CreateAHero_ShoulderPlates
	End
	Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_CreateAHero_Upgrade_DWARF_CHSP02
		TriggeredBy		= Upgrade_DWARF_CHSP02
		UpgradeGroupsToRemove = CreateAHero_ShoulderPlates
	End
	Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_CreateAHero_Upgrade_DWARF_CHSP03
		TriggeredBy		= Upgrade_DWARF_CHSP03
		UpgradeGroupsToRemove = CreateAHero_ShoulderPlates
	End
	Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_CreateAHero_Upgrade_DWARF_CHSP04
		TriggeredBy		= Upgrade_DWARF_CHSP04
		UpgradeGroupsToRemove = CreateAHero_ShoulderPlates
	End
	Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_CreateAHero_Upgrade_DWARF_CHSP05
		TriggeredBy		= Upgrade_DWARF_CHSP05
		UpgradeGroupsToRemove = CreateAHero_ShoulderPlates
	End
	Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_CreateAHero_Upgrade_DWARF_CHSP06
		TriggeredBy		= Upgrade_DWARF_CHSP06
		UpgradeGroupsToRemove = CreateAHero_ShoulderPlates
	End
	Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_CreateAHero_Upgrade_CaptainOfGondor_CHSP01
		TriggeredBy		= Upgrade_CaptainOfGondor_CHSP01
		UpgradeGroupsToRemove = CreateAHero_ShoulderPlates
	End
	Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_CreateAHero_Upgrade_CaptainOfGondor_CHSP02
		TriggeredBy		= Upgrade_CaptainOfGondor_CHSP02
		UpgradeGroupsToRemove = CreateAHero_ShoulderPlates
	End
	Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_CreateAHero_Upgrade_CaptainOfGondor_CHSP04
		TriggeredBy		= Upgrade_CaptainOfGondor_CHSP04
		UpgradeGroupsToRemove = CreateAHero_ShoulderPlates
	End
	Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_CreateAHero_Upgrade_CaptainOfGondor_CHSP05
		TriggeredBy		= Upgrade_CaptainOfGondor_CHSP05
		UpgradeGroupsToRemove = CreateAHero_ShoulderPlates
	End
	Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_CreateAHero_Upgrade_ELFA_CHSP01
		TriggeredBy		= Upgrade_ELFA_CHSP01
		UpgradeGroupsToRemove = CreateAHero_ShoulderPlates
	End
	Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_CreateAHero_Upgrade_ELFA_CHSP02
		TriggeredBy		= Upgrade_ELFA_CHSP02
		UpgradeGroupsToRemove = CreateAHero_ShoulderPlates
	End
	Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_CreateAHero_Upgrade_ELFA_CHSP03
		TriggeredBy		= Upgrade_ELFA_CHSP03
		UpgradeGroupsToRemove = CreateAHero_ShoulderPlates
	End
	Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_CreateAHero_Upgrade_ELFA_CHSP04
		TriggeredBy		= Upgrade_ELFA_CHSP04
		UpgradeGroupsToRemove = CreateAHero_ShoulderPlates
	End
	Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_CreateAHero_Upgrade_SHIM_CHSP01
		TriggeredBy		= Upgrade_SHIM_CHSP01
		UpgradeGroupsToRemove = CreateAHero_ShoulderPlates
	End
	Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_CreateAHero_Upgrade_SHIM_CHSP02
		TriggeredBy		= Upgrade_SHIM_CHSP02
		UpgradeGroupsToRemove = CreateAHero_ShoulderPlates
	End
	Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_CreateAHero_Upgrade_SHIM_CHSP03
		TriggeredBy		= Upgrade_SHIM_CHSP03
		UpgradeGroupsToRemove = CreateAHero_ShoulderPlates
	End
	Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_CreateAHero_Upgrade_FEARCH_CHSP01
		TriggeredBy		= Upgrade_FEARCH_CHSP01
		UpgradeGroupsToRemove = CreateAHero_ShoulderPlates
	End
	Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_CreateAHero_Upgrade_FEARCH_CHSP02
		TriggeredBy		= Upgrade_FEARCH_CHSP02
		UpgradeGroupsToRemove = CreateAHero_ShoulderPlates
	End
	Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_CreateAHero_Upgrade_FEARCH_CHSP03
		TriggeredBy		= Upgrade_FEARCH_CHSP03
		UpgradeGroupsToRemove = CreateAHero_ShoulderPlates
	End
	Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_CreateAHero_Upgrade_FEARCH_CHSP04
		TriggeredBy		= Upgrade_FEARCH_CHSP04
		UpgradeGroupsToRemove = CreateAHero_ShoulderPlates
	End
	Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_CreateAHero_Upgrade_FEARCH_CHSP05
		TriggeredBy		= Upgrade_FEARCH_CHSP05
		UpgradeGroupsToRemove = CreateAHero_ShoulderPlates
	End
	Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_CreateAHero_Upgrade_FEARCH_CHSP06
		TriggeredBy		= Upgrade_FEARCH_CHSP06
		UpgradeGroupsToRemove = CreateAHero_ShoulderPlates
	End
	Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_CreateAHero_Upgrade_WIZ_CHSP01
		TriggeredBy		= Upgrade_WIZ_CHSP01
		UpgradeGroupsToRemove = CreateAHero_ShoulderPlates
	End
	Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_CreateAHero_Upgrade_WIZ_CHSP02
		TriggeredBy		= Upgrade_WIZ_CHSP02
		UpgradeGroupsToRemove = CreateAHero_ShoulderPlates
	End
// Head Gear
	Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_CreateAHero_Upgrade_CorruptedMan_1_CHH01
		TriggeredBy		= Upgrade_CorruptedMan_1_CHH01
		UpgradeGroupsToRemove = CreateAHero_Helmet
	End
	Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_CreateAHero_Upgrade_CorruptedMan_1_CHH02
		TriggeredBy		= Upgrade_CorruptedMan_1_CHH02
		UpgradeGroupsToRemove = CreateAHero_Helmet
	End
	Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_CreateAHero_Upgrade_CorruptedMan_1_CHH03
		TriggeredBy		= Upgrade_CorruptedMan_1_CHH03
		UpgradeGroupsToRemove = CreateAHero_Helmet
	End
	Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_CreateAHero_Upgrade_CorruptedMan_1_CHH04
		TriggeredBy		= Upgrade_CorruptedMan_1_CHH04
		UpgradeGroupsToRemove = CreateAHero_Helmet
	End
	Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_CreateAHero_Upgrade_CorruptedMan_1_CHH05
		TriggeredBy		= Upgrade_CorruptedMan_1_CHH05
		UpgradeGroupsToRemove = CreateAHero_Helmet
	End
	Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_CreateAHero_Upgrade_CorruptedMan_1_CHH08
		TriggeredBy		= Upgrade_CorruptedMan_1_CHH08
		UpgradeGroupsToRemove = CreateAHero_Helmet
	End
	Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_CreateAHero_Upgrade_DWARF_CHH01
		TriggeredBy		= Upgrade_DWARF_CHH01
		UpgradeGroupsToRemove = CreateAHero_Helmet
	End
	Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_CreateAHero_Upgrade_DWARF_CHH02
		TriggeredBy		= Upgrade_DWARF_CHH02
		UpgradeGroupsToRemove = CreateAHero_Helmet
	End
	Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_CreateAHero_Upgrade_DWARF_CHH03
		TriggeredBy		= Upgrade_DWARF_CHH03
		UpgradeGroupsToRemove = CreateAHero_Helmet
	End
	Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_CreateAHero_Upgrade_DWARF_CHH04
		TriggeredBy		= Upgrade_DWARF_CHH04
		UpgradeGroupsToRemove = CreateAHero_Helmet
	End
	Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_CreateAHero_Upgrade_DWARF_CHH05
		TriggeredBy		= Upgrade_DWARF_CHH05
		UpgradeGroupsToRemove = CreateAHero_Helmet
	End
	Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_CreateAHero_Upgrade_DWARF_CHH06
		TriggeredBy		= Upgrade_DWARF_CHH06
		UpgradeGroupsToRemove = CreateAHero_Helmet
	End
	Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_CreateAHero_Upgrade_CaptainOfGondor_CHH01
		TriggeredBy		= Upgrade_CaptainOfGondor_CHH01
		UpgradeGroupsToRemove = CreateAHero_Helmet
	End
	Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_CreateAHero_Upgrade_CaptainOfGondor_CHH02
		TriggeredBy		= Upgrade_CaptainOfGondor_CHH02
		UpgradeGroupsToRemove = CreateAHero_Helmet
	End
	Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_CreateAHero_Upgrade_CaptainOfGondor_CHH03
		TriggeredBy		= Upgrade_CaptainOfGondor_CHH03
		UpgradeGroupsToRemove = CreateAHero_Helmet
	End
	Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_CreateAHero_Upgrade_CaptainOfGondor_CHH05
		TriggeredBy		= Upgrade_CaptainOfGondor_CHH05
		UpgradeGroupsToRemove = CreateAHero_Helmet
	End
	Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_CreateAHero_Upgrade_CaptainOfGondor_CHH06
		TriggeredBy		= Upgrade_CaptainOfGondor_CHH06
		UpgradeGroupsToRemove = CreateAHero_Helmet
	End
	Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_CreateAHero_Upgrade_ELFA_CHH01
		TriggeredBy		= Upgrade_ELFA_CHH01
		UpgradeGroupsToRemove = CreateAHero_Helmet
	End
	Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_CreateAHero_Upgrade_ELFA_CHH02
		TriggeredBy		= Upgrade_ELFA_CHH02
		UpgradeGroupsToRemove = CreateAHero_Helmet
	End
	Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_CreateAHero_Upgrade_ELFA_CHH03
		TriggeredBy		= Upgrade_ELFA_CHH03
		UpgradeGroupsToRemove = CreateAHero_Helmet
	End
	Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_CreateAHero_Upgrade_SHIM_CHH01
		TriggeredBy		= Upgrade_SHIM_CHH01
		UpgradeGroupsToRemove = CreateAHero_Helmet
	End
	Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_CreateAHero_Upgrade_SHIM_CHH02
		TriggeredBy		= Upgrade_SHIM_CHH02
		UpgradeGroupsToRemove = CreateAHero_Helmet
	End
	Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_CreateAHero_Upgrade_SHIM_CHH03
		TriggeredBy		= Upgrade_SHIM_CHH03
		UpgradeGroupsToRemove = CreateAHero_Helmet
	End
	Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_CreateAHero_Upgrade_FEARCH_CHH01
		TriggeredBy		= Upgrade_FEARCH_CHH01
		UpgradeGroupsToRemove = CreateAHero_Helmet
	End
	Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_CreateAHero_Upgrade_FEARCH_CHH02
		TriggeredBy		= Upgrade_FEARCH_CHH02
		UpgradeGroupsToRemove = CreateAHero_Helmet
	End
	Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_CreateAHero_Upgrade_FEARCH_CHH03
		TriggeredBy		= Upgrade_FEARCH_CHH03
		UpgradeGroupsToRemove = CreateAHero_Helmet
	End
	Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_CreateAHero_Upgrade_FEARCH_CHH04
		TriggeredBy		= Upgrade_FEARCH_CHH04
		UpgradeGroupsToRemove = CreateAHero_Helmet
	End
	Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_CreateAHero_Upgrade_FEARCH_CHH05
		TriggeredBy		= Upgrade_FEARCH_CHH05
		UpgradeGroupsToRemove = CreateAHero_Helmet
	End
	Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_CreateAHero_Upgrade_FEARCH_CHH06
		TriggeredBy		= Upgrade_FEARCH_CHH06
		UpgradeGroupsToRemove = CreateAHero_Helmet
	End
// Boots
	Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_CreateAHero_Upgrade_CorruptedMan_1_CHB01
		TriggeredBy		= Upgrade_CorruptedMan_1_CHB01
		UpgradeGroupsToRemove = CreateAHero_Boots
	End
	Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_CreateAHero_Upgrade_CorruptedMan_1_CHB02
		TriggeredBy		= Upgrade_CorruptedMan_1_CHB02
		UpgradeGroupsToRemove = CreateAHero_Boots
	End
	Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_CreateAHero_Upgrade_CorruptedMan_1_CHB03
		TriggeredBy		= Upgrade_CorruptedMan_1_CHB03
		UpgradeGroupsToRemove = CreateAHero_Boots
	End
	Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_CreateAHero_Upgrade_CaptainOfGondor_CHB01
		TriggeredBy		= Upgrade_CaptainOfGondor_CHB01
		UpgradeGroupsToRemove = CreateAHero_Boots
	End
	Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_CreateAHero_Upgrade_CaptainOfGondor_CHB02
		TriggeredBy		= Upgrade_CaptainOfGondor_CHB02
		UpgradeGroupsToRemove = CreateAHero_Boots
	End
	Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_CreateAHero_Upgrade_CaptainOfGondor_CHB03
		TriggeredBy		= Upgrade_CaptainOfGondor_CHB03
		UpgradeGroupsToRemove = CreateAHero_Boots
	End
	Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_CreateAHero_Upgrade_CaptainOfGondor_CHB04
		TriggeredBy		= Upgrade_CaptainOfGondor_CHB04
		UpgradeGroupsToRemove = CreateAHero_Boots
	End
	Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_CreateAHero_Upgrade_CaptainOfGondor_CHB05
		TriggeredBy		= Upgrade_CaptainOfGondor_CHB05
		UpgradeGroupsToRemove = CreateAHero_Boots
	End
	Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_CreateAHero_Upgrade_ELFA_CHB01
		TriggeredBy		= Upgrade_ELFA_CHB01
		UpgradeGroupsToRemove = CreateAHero_Boots
	End
	Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_CreateAHero_Upgrade_ELFA_CHB02
		TriggeredBy		= Upgrade_ELFA_CHB02
		UpgradeGroupsToRemove = CreateAHero_Boots
	End
	Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_CreateAHero_Upgrade_ELFA_CHB03
		TriggeredBy		= Upgrade_ELFA_CHB03
		UpgradeGroupsToRemove = CreateAHero_Boots
	End
	Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_CreateAHero_Upgrade_SHIM_CHB01
		TriggeredBy		= Upgrade_SHIM_CHB01
		UpgradeGroupsToRemove = CreateAHero_Boots
	End
	Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_CreateAHero_Upgrade_SHIM_CHB02
		TriggeredBy		= Upgrade_SHIM_CHB02
		UpgradeGroupsToRemove = CreateAHero_Boots
	End
	Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_CreateAHero_Upgrade_SHIM_CHB03
		TriggeredBy		= Upgrade_SHIM_CHB03
		UpgradeGroupsToRemove = CreateAHero_Boots
	End
	Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_CreateAHero_Upgrade_FEARCH_CHB01
		TriggeredBy		= Upgrade_FEARCH_CHB01
		UpgradeGroupsToRemove = CreateAHero_Boots
	End
	Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_CreateAHero_Upgrade_FEARCH_CHB02
		TriggeredBy		= Upgrade_FEARCH_CHB02
		UpgradeGroupsToRemove = CreateAHero_Boots
	End
	Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_CreateAHero_Upgrade_FEARCH_CHB03
		TriggeredBy		= Upgrade_FEARCH_CHB03
		UpgradeGroupsToRemove = CreateAHero_Boots
	End
	Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_CreateAHero_Upgrade_FEARCH_CHB04
		TriggeredBy		= Upgrade_FEARCH_CHB04
		UpgradeGroupsToRemove = CreateAHero_Boots
	End
	Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_CreateAHero_Upgrade_FEARCH_CHB05
		TriggeredBy		= Upgrade_FEARCH_CHB05
		UpgradeGroupsToRemove = CreateAHero_Boots
	End
	Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_CreateAHero_Upgrade_FEARCH_CHB06
		TriggeredBy		= Upgrade_FEARCH_CHB06
		UpgradeGroupsToRemove = CreateAHero_Boots
	End
	Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_CreateAHero_Upgrade_DWARF_CHB01
		TriggeredBy		= Upgrade_DWARF_CHB01
		UpgradeGroupsToRemove = CreateAHero_Boots
	End
	Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_CreateAHero_Upgrade_DWARF_CHB02
		TriggeredBy		= Upgrade_DWARF_CHB02
		UpgradeGroupsToRemove = CreateAHero_Boots
	End
	Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_CreateAHero_Upgrade_DWARF_CHB03
		TriggeredBy		= Upgrade_DWARF_CHB03
		UpgradeGroupsToRemove = CreateAHero_Boots
	End
	Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_CreateAHero_Upgrade_DWARF_CHB04
		TriggeredBy		= Upgrade_DWARF_CHB04
		UpgradeGroupsToRemove = CreateAHero_Boots
	End
	Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_CreateAHero_Upgrade_TRLL_CHBO01
		TriggeredBy		= Upgrade_TRLL_CHBO01
		UpgradeGroupsToRemove = CreateAHero_Boots
	End
// Gauntlets
	Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_CreateAHero_Upgrade_CorruptedMan_1_CHG01
		TriggeredBy		= Upgrade_CorruptedMan_1_CHG01
		UpgradeGroupsToRemove = CreateAHero_Gauntlets
	End
	Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_CreateAHero_Upgrade_CorruptedMan_1_CHG02
		TriggeredBy		= Upgrade_CorruptedMan_1_CHG02
		UpgradeGroupsToRemove = CreateAHero_Gauntlets
	End
	Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_CreateAHero_Upgrade_CorruptedMan_1_CHG03
		TriggeredBy		= Upgrade_CorruptedMan_1_CHG03
		UpgradeGroupsToRemove = CreateAHero_Gauntlets
	End
	Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_CreateAHero_Upgrade_CaptainOfGondor_CHG01
		TriggeredBy		= Upgrade_CaptainOfGondor_CHG01
		UpgradeGroupsToRemove = CreateAHero_Gauntlets
	End
	Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_CreateAHero_Upgrade_CaptainOfGondor_CHG02
		TriggeredBy		= Upgrade_CaptainOfGondor_CHG02
		UpgradeGroupsToRemove = CreateAHero_Gauntlets
	End
	Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_CreateAHero_Upgrade_CaptainOfGondor_CHG03
		TriggeredBy		= Upgrade_CaptainOfGondor_CHG03
		UpgradeGroupsToRemove = CreateAHero_Gauntlets
	End
	Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_CreateAHero_Upgrade_CaptainOfGondor_CHG04
		TriggeredBy		= Upgrade_CaptainOfGondor_CHG04
		UpgradeGroupsToRemove = CreateAHero_Gauntlets
	End
	Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_CreateAHero_Upgrade_CaptainOfGondor_CHG05
		TriggeredBy		= Upgrade_CaptainOfGondor_CHG05
		UpgradeGroupsToRemove = CreateAHero_Gauntlets
	End
	Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_CreateAHero_Upgrade_ELFA_CHG01
		TriggeredBy		= Upgrade_ELFA_CHG01
		UpgradeGroupsToRemove = CreateAHero_Gauntlets
	End
	Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_CreateAHero_Upgrade_ELFA_CHG02
		TriggeredBy		= Upgrade_ELFA_CHG02
		UpgradeGroupsToRemove = CreateAHero_Gauntlets
	End
	Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_CreateAHero_Upgrade_ELFA_CHG03
		TriggeredBy		= Upgrade_ELFA_CHG03
		UpgradeGroupsToRemove = CreateAHero_Gauntlets
	End
	Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_CreateAHero_Upgrade_ELFA_CHG04
		TriggeredBy		= Upgrade_ELFA_CHG04
		UpgradeGroupsToRemove = CreateAHero_Gauntlets
	End
	Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_CreateAHero_Upgrade_SHIM_CHG01
		TriggeredBy		= Upgrade_SHIM_CHG01
		UpgradeGroupsToRemove = CreateAHero_Gauntlets
	End
	Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_CreateAHero_Upgrade_SHIM_CHG02
		TriggeredBy		= Upgrade_SHIM_CHG02
		UpgradeGroupsToRemove = CreateAHero_Gauntlets
	End
	Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_CreateAHero_Upgrade_FEARCH_CHG01
		TriggeredBy		= Upgrade_FEARCH_CHG01
		UpgradeGroupsToRemove = CreateAHero_Gauntlets
	End
	Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_CreateAHero_Upgrade_FEARCH_CHG02
		TriggeredBy		= Upgrade_FEARCH_CHG02
		UpgradeGroupsToRemove = CreateAHero_Gauntlets
	End
	Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_CreateAHero_Upgrade_FEARCH_CHG03
		TriggeredBy		= Upgrade_FEARCH_CHG03
		UpgradeGroupsToRemove = CreateAHero_Gauntlets
	End
	Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_CreateAHero_Upgrade_FEARCH_CHG04
		TriggeredBy		= Upgrade_FEARCH_CHG04
		UpgradeGroupsToRemove = CreateAHero_Gauntlets
	End
	Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_CreateAHero_Upgrade_FEARCH_CHG05
		TriggeredBy		= Upgrade_FEARCH_CHG05
		UpgradeGroupsToRemove = CreateAHero_Gauntlets
	End
	Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_CreateAHero_Upgrade_FEARCH_CHG06
		TriggeredBy		= Upgrade_FEARCH_CHG06
		UpgradeGroupsToRemove = CreateAHero_Gauntlets
	End
	Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_CreateAHero_Upgrade_DWARF_CHG01
		TriggeredBy		= Upgrade_DWARF_CHG01
		UpgradeGroupsToRemove = CreateAHero_Gauntlets
	End
	Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_CreateAHero_Upgrade_DWARF_CHG02
		TriggeredBy		= Upgrade_DWARF_CHG02
		UpgradeGroupsToRemove = CreateAHero_Gauntlets
	End
	Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_CreateAHero_Upgrade_DWARF_CHG03
		TriggeredBy		= Upgrade_DWARF_CHG03
		UpgradeGroupsToRemove = CreateAHero_Gauntlets
	End
	Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_CreateAHero_Upgrade_DWARF_CHG04
		TriggeredBy		= Upgrade_DWARF_CHG04
		UpgradeGroupsToRemove = CreateAHero_Gauntlets
	End
//=====================================================================================================
// This section contains the RemoveUpgradeUpgrades for the Create a Hero class
//=====================================================================================================

Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_CreateAHero_ClassHeroOfTheWest
	TriggeredBy		= Upgrade_CreateAHero_ClassHeroOfTheWest
	UpgradeToRemove	= Upgrade_CreateAHero_ClassIstariWizard Upgrade_CreateAHero_ClassDwarf Upgrade_CreateAHero_ClassCorruptedMan Upgrade_CreateAHero_ClassServantsOfSauron Upgrade_CreateAHero_ClassArcher Upgrade_CreateAHero_ClassOlogHai
End


Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_CreateAHero_ClassIstariWizard
	TriggeredBy		= Upgrade_CreateAHero_ClassIstariWizard
	UpgradeToRemove	= Upgrade_CreateAHero_ClassHeroOfTheWest Upgrade_CreateAHero_ClassDwarf Upgrade_CreateAHero_ClassCorruptedMan Upgrade_CreateAHero_ClassServantsOfSauron Upgrade_CreateAHero_ClassArcher Upgrade_CreateAHero_ClassOlogHai
End

Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_CreateAHero_ClassDwarf
	TriggeredBy		= Upgrade_CreateAHero_ClassDwarf
	UpgradeToRemove	= Upgrade_CreateAHero_ClassHeroOfTheWest Upgrade_CreateAHero_ClassIstariWizard Upgrade_CreateAHero_ClassCorruptedMan Upgrade_CreateAHero_ClassServantsOfSauron Upgrade_CreateAHero_ClassOlogHai Upgrade_CreateAHero_ClassArcher
End

//	Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_CreateAHero_ClassHorseman
//		TriggeredBy		= Upgrade_CreateAHero_ClassHorseman
//		UpgradeToRemove	= Upgrade_CreateAHero_ClassHeroOfTheWest Upgrade_CreateAHero_ClassIstariWizard Upgrade_CreateAHero_ClassDwarf  Upgrade_CreateAHero_ClassCorruptedMan Upgrade_CreateAHero_ClassServantsOfSauron Upgrade_CreateAHero_ClassArcher Upgrade_CreateAHero_ClassOlogHai
//	End

Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_CreateAHero_ClassCorruptedMan
	TriggeredBy		= Upgrade_CreateAHero_ClassCorruptedMan
	UpgradeToRemove	= Upgrade_CreateAHero_ClassHeroOfTheWest Upgrade_CreateAHero_ClassIstariWizard Upgrade_CreateAHero_ClassDwarf Upgrade_CreateAHero_ClassServantsOfSauron Upgrade_CreateAHero_ClassArcher Upgrade_CreateAHero_ClassOlogHai
End

Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_CreateAHero_ClassServantsOfSauron
	TriggeredBy		= Upgrade_CreateAHero_ClassServantsOfSauron
	UpgradeToRemove	= Upgrade_CreateAHero_ClassHeroOfTheWest Upgrade_CreateAHero_ClassIstariWizard Upgrade_CreateAHero_ClassDwarf Upgrade_CreateAHero_ClassCorruptedMan Upgrade_CreateAHero_ClassArcher Upgrade_CreateAHero_ClassOlogHai
End

Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_CreateAHero_ClassArcher
	TriggeredBy		= Upgrade_CreateAHero_ClassArcher
	UpgradeToRemove	= Upgrade_CreateAHero_ClassHeroOfTheWest Upgrade_CreateAHero_ClassIstariWizard Upgrade_CreateAHero_ClassDwarf Upgrade_CreateAHero_ClassCorruptedMan Upgrade_CreateAHero_ClassServantsOfSauron  Upgrade_CreateAHero_ClassOlogHai
End

Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_CreateAHero_ClassOlogHai
	TriggeredBy		= Upgrade_CreateAHero_ClassOlogHai
	UpgradeToRemove	= Upgrade_CreateAHero_ClassHeroOfTheWest Upgrade_CreateAHero_ClassIstariWizard Upgrade_CreateAHero_ClassDwarf Upgrade_CreateAHero_ClassCorruptedMan Upgrade_CreateAHero_ClassArcher Upgrade_CreateAHero_ClassServantsOfSauron
End

//=====================================================================================================
// This section contains the RemoveUpgradeUpgrades for the Create a Hero subclass
//=====================================================================================================

Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_CreateAHero_SubClass_0
	TriggeredBy		= Upgrade_CreateAHero_SubClass_0
	UpgradeToRemove	= Upgrade_CreateAHero_SubClass_1 Upgrade_CreateAHero_SubClass_2 Upgrade_CreateAHero_SubClass_3 Upgrade_CreateAHero_SubClass_4 Upgrade_CreateAHero_SubClass_5 Upgrade_CreateAHero_SubClass_6
End

Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_CreateAHero_SubClass_1
	TriggeredBy		= Upgrade_CreateAHero_SubClass_1
	UpgradeToRemove	= Upgrade_CreateAHero_SubClass_0 Upgrade_CreateAHero_SubClass_2 Upgrade_CreateAHero_SubClass_3 Upgrade_CreateAHero_SubClass_4 Upgrade_CreateAHero_SubClass_5 Upgrade_CreateAHero_SubClass_6
End

Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_CreateAHero_SubClass_2
	TriggeredBy		= Upgrade_CreateAHero_SubClass_2
	UpgradeToRemove	= Upgrade_CreateAHero_SubClass_0 Upgrade_CreateAHero_SubClass_1 Upgrade_CreateAHero_SubClass_3 Upgrade_CreateAHero_SubClass_4 Upgrade_CreateAHero_SubClass_5 Upgrade_CreateAHero_SubClass_6
End

Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_CreateAHero_SubClass_3
	TriggeredBy		= Upgrade_CreateAHero_SubClass_3
	UpgradeToRemove	= Upgrade_CreateAHero_SubClass_0 Upgrade_CreateAHero_SubClass_1 Upgrade_CreateAHero_SubClass_2  Upgrade_CreateAHero_SubClass_4 Upgrade_CreateAHero_SubClass_5 Upgrade_CreateAHero_SubClass_6
End

Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_CreateAHero_SubClass_4
	TriggeredBy		= Upgrade_CreateAHero_SubClass_4
	UpgradeToRemove	= Upgrade_CreateAHero_SubClass_0 Upgrade_CreateAHero_SubClass_1 Upgrade_CreateAHero_SubClass_2 Upgrade_CreateAHero_SubClass_3 Upgrade_CreateAHero_SubClass_5 Upgrade_CreateAHero_SubClass_6
End

Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_CreateAHero_SubClass_5
	TriggeredBy		= Upgrade_CreateAHero_SubClass_5
	UpgradeToRemove	= Upgrade_CreateAHero_SubClass_0 Upgrade_CreateAHero_SubClass_1 Upgrade_CreateAHero_SubClass_2 Upgrade_CreateAHero_SubClass_3 Upgrade_CreateAHero_SubClass_4 Upgrade_CreateAHero_SubClass_6
End

Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_CreateAHero_SubClass_6
	TriggeredBy		= Upgrade_CreateAHero_SubClass_6
	UpgradeToRemove	= Upgrade_CreateAHero_SubClass_0 Upgrade_CreateAHero_SubClass_1 Upgrade_CreateAHero_SubClass_2 Upgrade_CreateAHero_SubClass_3 Upgrade_CreateAHero_SubClass_4 Upgrade_CreateAHero_SubClass_5 
End

//-------------------------------------------------------
// Shoulder	Plates
Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_Uruk_CHSP01
  TriggeredBy			= Upgrade_Uruk_CHSP01
  UpgradeGroupsToRemove	= CreateAHero_ShoulderPlates
End

Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_Uruk_CHSP02
  TriggeredBy			= Upgrade_Uruk_CHSP02
  UpgradeGroupsToRemove	= CreateAHero_ShoulderPlates
End

Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_Uruk_CHSP03
  TriggeredBy			= Upgrade_Uruk_CHSP03
  UpgradeGroupsToRemove	= CreateAHero_ShoulderPlates
End

//Elf Archer
Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_ELFA_CHSP01
  TriggeredBy			= Upgrade_ELFA_CHSP01
  UpgradeGroupsToRemove	= CreateAHero_ShoulderPlates
End

Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_ELFA_CHSP02
  TriggeredBy			= Upgrade_ELFA_CHSP02
  UpgradeGroupsToRemove	= CreateAHero_ShoulderPlates
End

Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_ELFA_CHSP03
  TriggeredBy			= Upgrade_ELFA_CHSP03
  UpgradeGroupsToRemove	= CreateAHero_ShoulderPlates
End

Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_ELFA_CHSP04
  TriggeredBy			= Upgrade_ELFA_CHSP04
  UpgradeGroupsToRemove	= CreateAHero_ShoulderPlates
End

//Sheild Maiden
Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_SHIM_CHSP01
  TriggeredBy			= Upgrade_SHIM_CHSP01
  UpgradeGroupsToRemove	= CreateAHero_ShoulderPlates
End

Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_SHIM_CHSP02
  TriggeredBy			= Upgrade_SHIM_CHSP02
  UpgradeGroupsToRemove	= CreateAHero_ShoulderPlates
End

Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_SHIM_CHSP03
  TriggeredBy			= Upgrade_SHIM_CHSP03
  UpgradeGroupsToRemove	= CreateAHero_ShoulderPlates
End

//Female Elven Archer
Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_FEARCH_CHSP01
  TriggeredBy			= Upgrade_FEARCH_CHSP01
  UpgradeGroupsToRemove	= CreateAHero_ShoulderPlates
End

Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_FEARCH_CHSP02
  TriggeredBy			= Upgrade_FEARCH_CHSP02
  UpgradeGroupsToRemove	= CreateAHero_ShoulderPlates
End

Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_FEARCH_CHSP03
  TriggeredBy			= Upgrade_FEARCH_CHSP03
  UpgradeGroupsToRemove	= CreateAHero_ShoulderPlates
End

Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_FEARCH_CHSP04
  TriggeredBy			= Upgrade_FEARCH_CHSP04
  UpgradeGroupsToRemove	= CreateAHero_ShoulderPlates
End

Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_FEARCH_CHSP05
  TriggeredBy			= Upgrade_FEARCH_CHSP05
  UpgradeGroupsToRemove	= CreateAHero_ShoulderPlates
End
Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_FEARCH_CHSP06
  TriggeredBy			= Upgrade_FEARCH_CHSP06
  UpgradeGroupsToRemove	= CreateAHero_ShoulderPlates
End

//Dwarf
Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_DWARF_CHSP01
  TriggeredBy			= Upgrade_DWARF_CHSP01
  UpgradeGroupsToRemove	= CreateAHero_ShoulderPlates
End

Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_DWARF_CHSP02
  TriggeredBy			= Upgrade_DWARF_CHSP02
  UpgradeGroupsToRemove	= CreateAHero_ShoulderPlates
End

Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_DWARF_CHSP03
  TriggeredBy			= Upgrade_DWARF_CHSP03
  UpgradeGroupsToRemove	= CreateAHero_ShoulderPlates
End

Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_DWARF_CHSP04
  TriggeredBy			= Upgrade_DWARF_CHSP04
  UpgradeGroupsToRemove	= CreateAHero_ShoulderPlates
End

Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_DWARF_CHSP05
  TriggeredBy			= Upgrade_DWARF_CHSP05
  UpgradeGroupsToRemove	= CreateAHero_ShoulderPlates
End

Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_DWARF_CHSP06
  TriggeredBy			= Upgrade_DWARF_CHSP06
  UpgradeGroupsToRemove	= CreateAHero_ShoulderPlates
End

//Wizard
Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_WIZ_CHSP01
  TriggeredBy			= Upgrade_WIZ_CHSP01
  UpgradeGroupsToRemove	= CreateAHero_ShoulderPlates
End

Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_WIZ_CHSP02
  TriggeredBy			= Upgrade_WIZ_CHSP02
  UpgradeGroupsToRemove	= CreateAHero_ShoulderPlates
End

//Troll
Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_TRLL_CHSP01
  TriggeredBy			= Upgrade_TRLL_CHSP01
  UpgradeGroupsToRemove	= CreateAHero_ShoulderPlates
End

Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_TRLL_CHSP02
  TriggeredBy			= Upgrade_TRLL_CHSP02
  UpgradeGroupsToRemove	= CreateAHero_ShoulderPlates
End

Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_TRLL_CHSP03
  TriggeredBy			= Upgrade_TRLL_CHSP03
  UpgradeGroupsToRemove	= CreateAHero_ShoulderPlates
End

Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_TRLL_CHSP04
  TriggeredBy			= Upgrade_TRLL_CHSP04
  UpgradeGroupsToRemove	= CreateAHero_ShoulderPlates
End

Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_TRLL_CHSP05
  TriggeredBy			= Upgrade_TRLL_CHSP05
  UpgradeGroupsToRemove	= CreateAHero_ShoulderPlates
End

Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_TRLL_CHSP06
  TriggeredBy			= Upgrade_TRLL_CHSP06
  UpgradeGroupsToRemove	= CreateAHero_ShoulderPlates
End

// ORC
Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_ORC_CHSP01
  TriggeredBy			= Upgrade_ORC_CHSP01
  UpgradeGroupsToRemove	= CreateAHero_ShoulderPlates
End

Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_ORC_CHSP02
  TriggeredBy			= Upgrade_ORC_CHSP02
  UpgradeGroupsToRemove	= CreateAHero_ShoulderPlates
End
//-------------------------------------------------------
// Helmet
Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_Uruk_CHHAIR01
  TriggeredBy			= Upgrade_Uruk_CHHAIR01
  UpgradeGroupsToRemove	= CreateAHero_Helmet
End

Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_Uruk_CHH01
  TriggeredBy			= Upgrade_Uruk_CHH01
  UpgradeGroupsToRemove	= CreateAHero_Helmet
End

Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_Uruk_CHH02
  TriggeredBy			= Upgrade_Uruk_CHH02
  UpgradeGroupsToRemove	= CreateAHero_Helmet
End

Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_Uruk_CHH03
  TriggeredBy			= Upgrade_Uruk_CHH03
  UpgradeGroupsToRemove	= CreateAHero_Helmet
End

Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_Uruk_CHH04
  TriggeredBy			= Upgrade_Uruk_CHH04
  UpgradeGroupsToRemove	= CreateAHero_Helmet
End

// Elf Archer
Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_ELFA_CHH01
  TriggeredBy			= Upgrade_ELFA_CHH01
  UpgradeGroupsToRemove	= CreateAHero_Helmet
End

Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_ELFA_CHH02
  TriggeredBy			= Upgrade_ELFA_CHH02
  UpgradeGroupsToRemove	= CreateAHero_Helmet
End

Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_ELFA_CHH03
  TriggeredBy			= Upgrade_ELFA_CHH03
  UpgradeGroupsToRemove	= CreateAHero_Helmet
End

//Sheild Maiden
Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_SHIM_CHH01
  TriggeredBy			= Upgrade_SHIM_CHH01
  UpgradeGroupsToRemove	= CreateAHero_Helmet
End

Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_SHIM_CHH02
  TriggeredBy			= Upgrade_SHIM_CHH02
  UpgradeGroupsToRemove	= CreateAHero_Helmet
End
// Wizard
Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_WIZ_CHH01
  TriggeredBy			= Upgrade_WIZ_CHH01
  UpgradeGroupsToRemove	= CreateAHero_Helmet
End

Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_WIZ_CHH02
  TriggeredBy			= Upgrade_WIZ_CHH02
  UpgradeGroupsToRemove	= CreateAHero_Helmet
End

Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_WIZ_CHH03
  TriggeredBy			= Upgrade_WIZ_CHH03
  UpgradeGroupsToRemove	= CreateAHero_Helmet
End

Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_WIZ_CHH04
  TriggeredBy			= Upgrade_WIZ_CHH04
  UpgradeGroupsToRemove	= CreateAHero_Helmet
End

Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_WIZ_CHH05
  TriggeredBy			= Upgrade_WIZ_CHH05
  UpgradeGroupsToRemove	= CreateAHero_Helmet
End

Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_WIZ_CHH06
  TriggeredBy			= Upgrade_WIZ_CHH06
  UpgradeGroupsToRemove	= CreateAHero_Helmet
End

Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_WIZ_CHH07
  TriggeredBy			= Upgrade_WIZ_CHH07
  UpgradeGroupsToRemove	= CreateAHero_Helmet
End

//Female Elven Archer
Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_FEARCH_CHH01
  TriggeredBy			= Upgrade_FEARCH_CHH01
  UpgradeGroupsToRemove	= CreateAHero_Helmet
End

Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_FEARCH_CHH02
  TriggeredBy			= Upgrade_FEARCH_CHH02
  UpgradeGroupsToRemove	= CreateAHero_Helmet
End

Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_FEARCH_CHH03
  TriggeredBy			= Upgrade_FEARCH_CHH03
  UpgradeGroupsToRemove	= CreateAHero_Helmet
End

Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_FEARCH_CHH04
  TriggeredBy			= Upgrade_FEARCH_CHH04
  UpgradeGroupsToRemove	= CreateAHero_Helmet
End

Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_FEARCH_CHH05
  TriggeredBy			= Upgrade_FEARCH_CHH05
  UpgradeGroupsToRemove	= CreateAHero_Helmet
End

Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_FEARCH_CHH06
  TriggeredBy			= Upgrade_FEARCH_CHH06
  UpgradeGroupsToRemove	= CreateAHero_Helmet
End

//Dwarf
Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_DWARF_CHH01
  TriggeredBy			= Upgrade_DWARF_CHH01
  UpgradeGroupsToRemove	= CreateAHero_Helmet
End

Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_DWARF_CHH02
  TriggeredBy			= Upgrade_DWARF_CHH02
  UpgradeGroupsToRemove	= CreateAHero_Helmet
End

Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_DWARF_CHH03
  TriggeredBy			= Upgrade_DWARF_CHH03
  UpgradeGroupsToRemove	= CreateAHero_Helmet
End

Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_DWARF_CHH04
  TriggeredBy			= Upgrade_DWARF_CHH04
  UpgradeGroupsToRemove	= CreateAHero_Helmet
End

Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_DWARF_CHH05
  TriggeredBy			= Upgrade_DWARF_CHH05
  UpgradeGroupsToRemove	= CreateAHero_Helmet
End

Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_DWARF_CHH06
  TriggeredBy			= Upgrade_DWARF_CHH06
  UpgradeGroupsToRemove	= CreateAHero_Helmet
End


//Troll
Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_TRLL_CHH01
  TriggeredBy			= Upgrade_TRLL_CHH01
  UpgradeGroupsToRemove	= CreateAHero_Helmet
End

Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_TRLL_CHH02
  TriggeredBy			= Upgrade_TRLL_CHH02
  UpgradeGroupsToRemove	= CreateAHero_Helmet
End

Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_TRLL_CHH03
  TriggeredBy			= Upgrade_TRLL_CHH03
  UpgradeGroupsToRemove	= CreateAHero_Helmet
End

Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_TRLL_CHH04
  TriggeredBy			= Upgrade_TRLL_CHH04
  UpgradeGroupsToRemove	= CreateAHero_Helmet
End

Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_TRLL_CHH05
  TriggeredBy			= Upgrade_TRLL_CHH05
  UpgradeGroupsToRemove	= CreateAHero_Helmet
End

Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_TRLL_CHH06
  TriggeredBy			= Upgrade_TRLL_CHH06
  UpgradeGroupsToRemove	= CreateAHero_Helmet
End

Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_TRLL_CHH07
  TriggeredBy			= Upgrade_TRLL_CHH07
  UpgradeGroupsToRemove	= CreateAHero_Helmet
End

Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_TRLL_CHH08
  TriggeredBy			= Upgrade_TRLL_CHH08
  UpgradeGroupsToRemove	= CreateAHero_Helmet
End

// ORC
Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_ORC_CHH01
  TriggeredBy			= Upgrade_ORC_CHH01
  UpgradeGroupsToRemove	= CreateAHero_Helmet
End

// ORC
Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_ORC_CHH02
  TriggeredBy			= Upgrade_ORC_CHH02
  UpgradeGroupsToRemove	= CreateAHero_Helmet
End

//-------------------------------------------------------
// Gauntlets
Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_Uruk_CHG01
  TriggeredBy			= Upgrade_Uruk_CHG01
  UpgradeGroupsToRemove	= CreateAHero_Gauntlets
End

Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_Uruk_CHG02
  TriggeredBy			= Upgrade_Uruk_CHG02
  UpgradeGroupsToRemove	= CreateAHero_Gauntlets
End

Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_Uruk_CHG03
  TriggeredBy			= Upgrade_Uruk_CHG03
  UpgradeGroupsToRemove	= CreateAHero_Gauntlets
End

//Elf Archer
Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_ELFA_CHG01
  TriggeredBy			= Upgrade_ELFA_CHG01
  UpgradeGroupsToRemove	= CreateAHero_Gauntlets
End

Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_ELFA_CHG02
  TriggeredBy			= Upgrade_ELFA_CHG02
  UpgradeGroupsToRemove	= CreateAHero_Gauntlets
End

Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_ELFA_CHG03
  TriggeredBy			= Upgrade_ELFA_CHG03
  UpgradeGroupsToRemove	= CreateAHero_Gauntlets
End

Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_ELFA_CHG04
  TriggeredBy			= Upgrade_ELFA_CHG04
  UpgradeGroupsToRemove	= CreateAHero_Gauntlets
End

//Sheild Maiden
Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_SHIM_CHG01
  TriggeredBy			= Upgrade_SHIM_CHG01
  UpgradeGroupsToRemove	= CreateAHero_Gauntlets
End

Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_SHIM_CHG02
  TriggeredBy			= Upgrade_SHIM_CHG02
  UpgradeGroupsToRemove	= CreateAHero_Gauntlets
End

Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_SHIM_CHG03
  TriggeredBy			= Upgrade_SHIM_CHG03
  UpgradeGroupsToRemove	= CreateAHero_Gauntlets
End
//Female Elven Archer
Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_FEARCH_CHG01
  TriggeredBy			= Upgrade_FEARCH_CHG01
  UpgradeGroupsToRemove	= CreateAHero_Gauntlets
End

Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_FEARCH_CHG02
  TriggeredBy			= Upgrade_FEARCH_CHG02
  UpgradeGroupsToRemove	= CreateAHero_Gauntlets
End

Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_FEARCH_CHG03
  TriggeredBy			= Upgrade_FEARCH_CHG03
  UpgradeGroupsToRemove	= CreateAHero_Gauntlets
End

Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_FEARCH_CHG04
  TriggeredBy			= Upgrade_FEARCH_CHG04
  UpgradeGroupsToRemove	= CreateAHero_Gauntlets
End

Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_FEARCH_CHG05
  TriggeredBy			= Upgrade_FEARCH_CHG05
  UpgradeGroupsToRemove	= CreateAHero_Gauntlets
End

Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_FEARCH_CHG06
  TriggeredBy			= Upgrade_FEARCH_CHG06
  UpgradeGroupsToRemove	= CreateAHero_Gauntlets
End

//Troll
Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_TRLL_CHG01
  TriggeredBy			= Upgrade_TRLL_CHG01
  UpgradeGroupsToRemove	= CreateAHero_Gauntlets
End

Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_TRLL_CHG02
  TriggeredBy			= Upgrade_TRLL_CHG02
  UpgradeGroupsToRemove	= CreateAHero_Gauntlets
End

Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_TRLL_CHG03
  TriggeredBy			= Upgrade_TRLL_CHG03
  UpgradeGroupsToRemove	= CreateAHero_Gauntlets
End

Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_TRLL_CHG04
  TriggeredBy			= Upgrade_TRLL_CHG04
  UpgradeGroupsToRemove	= CreateAHero_Gauntlets
End

Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_TRLL_CHG05
  TriggeredBy			= Upgrade_TRLL_CHG05
  UpgradeGroupsToRemove	= CreateAHero_Gauntlets
End

Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_TRLL_CHG06
  TriggeredBy			= Upgrade_TRLL_CHG06
  UpgradeGroupsToRemove	= CreateAHero_Gauntlets
End

Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_TRLL_CHG07
  TriggeredBy			= Upgrade_TRLL_CHG07
  UpgradeGroupsToRemove	= CreateAHero_Gauntlets
End

Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_TRLL_CHG08
  TriggeredBy			= Upgrade_TRLL_CHG08
  UpgradeGroupsToRemove	= CreateAHero_Gauntlets
End

Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_TRLL_CHG09
  TriggeredBy			= Upgrade_TRLL_CHG09
  UpgradeGroupsToRemove	= CreateAHero_Gauntlets
End

Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_TRLL_CHG10
  TriggeredBy			= Upgrade_TRLL_CHG10
  UpgradeGroupsToRemove	= CreateAHero_Gauntlets
End

//Dwarf
Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_DWARF_CHG01
  TriggeredBy			= Upgrade_DWARF_CHG01
  UpgradeGroupsToRemove	= CreateAHero_Gauntlets
End

Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_DWARF_CHG02
  TriggeredBy			= Upgrade_DWARF_CHG02
  UpgradeGroupsToRemove	= CreateAHero_Gauntlets
End

Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_DWARF_CHG03
  TriggeredBy			= Upgrade_DWARF_CHG03
  UpgradeGroupsToRemove	= CreateAHero_Gauntlets
End

Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_DWARF_CHG04
  TriggeredBy			= Upgrade_DWARF_CHG04
  UpgradeGroupsToRemove	= CreateAHero_Gauntlets
End

// ORC

Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_ORC_CHG01
  TriggeredBy			= Upgrade_ORC_CHG01
  UpgradeGroupsToRemove	= CreateAHero_Gauntlets
End

Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_ORC_CHG02
  TriggeredBy			= Upgrade_ORC_CHG02
  UpgradeGroupsToRemove	= CreateAHero_Gauntlets
End
//-------------------------------------------------------
// Shield
Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_Uruk_CHS01
  TriggeredBy			= Upgrade_Uruk_CHS01
  UpgradeGroupsToRemove	= CreateAHero_Shield
End

Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_Uruk_CHS02
  TriggeredBy			= Upgrade_Uruk_CHS02
  UpgradeGroupsToRemove	= CreateAHero_Shield
End

Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_Uruk_CHS03
  TriggeredBy			= Upgrade_Uruk_CHS03
  UpgradeGroupsToRemove	= CreateAHero_Shield
End

Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_Uruk_CHS04
  TriggeredBy			= Upgrade_Uruk_CHS04
  UpgradeGroupsToRemove	= CreateAHero_Shield
End

Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_CAPG_CHS01
  TriggeredBy			= Upgrade_CAPG_CHS01
  UpgradeGroupsToRemove	= CreateAHero_Shield
End

Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_CAPG_CHS02
  TriggeredBy			= Upgrade_CAPG_CHS02
  UpgradeGroupsToRemove	= CreateAHero_Shield
End

Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_CAPG_CHS03
  TriggeredBy			= Upgrade_CAPG_CHS03
  UpgradeGroupsToRemove	= CreateAHero_Shield
End

Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_CAPG_CHS04
  TriggeredBy			= Upgrade_CAPG_CHS04
  UpgradeGroupsToRemove	= CreateAHero_Shield
End
//-------------------------------------------------------
// Boots
Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_Uruk_CHB01
  TriggeredBy			= Upgrade_Uruk_CHB01
  UpgradeGroupsToRemove	= CreateAHero_Boots
End

Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_Uruk_CHB02
  TriggeredBy			= Upgrade_Uruk_CHB02
  UpgradeGroupsToRemove	= CreateAHero_Boots
End

Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_Uruk_CHB03
  TriggeredBy			= Upgrade_Uruk_CHB03
  UpgradeGroupsToRemove	= CreateAHero_Boots
End

//Elf Archer
Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_ELFA_CHB01
  TriggeredBy			= Upgrade_ELFA_CHB01
  UpgradeGroupsToRemove	= CreateAHero_Boots
End

Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_ELFA_CHB02
  TriggeredBy			= Upgrade_ELFA_CHB02
  UpgradeGroupsToRemove	= CreateAHero_Boots
End

Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_ELFA_CHB03
  TriggeredBy			= Upgrade_ELFA_CHB03
  UpgradeGroupsToRemove	= CreateAHero_Boots
End

//Sheild Maiden
Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_SHIM_CHB01
  TriggeredBy			= Upgrade_SHIM_CHB01
  UpgradeGroupsToRemove	= CreateAHero_Boots
End

Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_SHIM_CHB02
  TriggeredBy			= Upgrade_SHIM_CHB02
  UpgradeGroupsToRemove	= CreateAHero_Boots
End

Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_SHIM_CHB03
  TriggeredBy			= Upgrade_SHIM_CHB03
  UpgradeGroupsToRemove	= CreateAHero_Boots
End

//Female Elven Archer
Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_FEARCH_CHB01
  TriggeredBy			= Upgrade_FEARCH_CHB01
  UpgradeGroupsToRemove	= CreateAHero_Boots
End

Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_FEARCH_CHB02
  TriggeredBy			= Upgrade_FEARCH_CHB02
  UpgradeGroupsToRemove	= CreateAHero_Boots
End

Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_FEARCH_CHB03
  TriggeredBy			= Upgrade_FEARCH_CHB03
  UpgradeGroupsToRemove	= CreateAHero_Boots
End

Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_FEARCH_CHB04
  TriggeredBy			= Upgrade_FEARCH_CHB04
  UpgradeGroupsToRemove	= CreateAHero_Boots
End

Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_FEARCH_CHB05
  TriggeredBy			= Upgrade_FEARCH_CHB05
  UpgradeGroupsToRemove	= CreateAHero_Boots
End

Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_FEARCH_CHB06
  TriggeredBy			= Upgrade_FEARCH_CHB06
  UpgradeGroupsToRemove	= CreateAHero_Boots
End

//Dwarf
Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_DWARF_CHB01
  TriggeredBy			= Upgrade_DWARF_CHB01
  UpgradeGroupsToRemove	= CreateAHero_Boots
End

Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_DWARF_CHB02
  TriggeredBy			= Upgrade_DWARF_CHB02
  UpgradeGroupsToRemove	= CreateAHero_Boots
End

Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_DWARF_CHB03
  TriggeredBy			= Upgrade_DWARF_CHB03
  UpgradeGroupsToRemove	= CreateAHero_Boots
End

Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_DWARF_CHB04
  TriggeredBy			= Upgrade_DWARF_CHB04
  UpgradeGroupsToRemove	= CreateAHero_Boots
End

// ORC
Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_ORC_CHB01
  TriggeredBy			= Upgrade_ORC_CHB01
  UpgradeGroupsToRemove	= CreateAHero_Boots
End
Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_ORC_CHB02
  TriggeredBy			= Upgrade_ORC_CHB02
  UpgradeGroupsToRemove	= CreateAHero_Boots
End
Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_ORC_CHB03
  TriggeredBy			= Upgrade_ORC_CHB03
  UpgradeGroupsToRemove	= CreateAHero_Boots
End
//-------------------------------------------------------
// Generic No Upgrades
Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_NoHelmet
	TriggeredBy				= Upgrade_NoHelmet
	UpgradeGroupsToRemove	= CreateAHero_Helmet
End
Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_NoShoulderPlates
	TriggeredBy				= Upgrade_NoShoulderPlates
	UpgradeGroupsToRemove	= CreateAHero_ShoulderPlates
End
Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_NoGauntlets
	TriggeredBy				= Upgrade_NoGauntlets
	UpgradeGroupsToRemove	= CreateAHero_Gauntlets
End
Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_NoShield
	TriggeredBy				= Upgrade_NoShield
	UpgradeGroupsToRemove	= CreateAHero_Shield
End
Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_NoBoots
	TriggeredBy				= Upgrade_NoBoots
	UpgradeGroupsToRemove	= CreateAHero_Boots
End
//-------------------------------------------------------
// Body

// Corrupted Man
Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_CM01_CHBOD01
  TriggeredBy			= Upgrade_CM01_CHBOD01
  UpgradeGroupsToRemove	= CreateAHero_Body
End

Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_CM01_CHBOD02
  TriggeredBy			= Upgrade_CM01_CHBOD02
  UpgradeGroupsToRemove	= CreateAHero_Body
End

Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_CM01_CHBOD03
  TriggeredBy			= Upgrade_CM01_CHBOD03
  UpgradeGroupsToRemove	= CreateAHero_Body
End

Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_CM01_CHBOD04
  TriggeredBy			= Upgrade_CM01_CHBOD04
  UpgradeGroupsToRemove	= CreateAHero_Body
End

Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_CM01_CHBOD05
  TriggeredBy			= Upgrade_CM01_CHBOD05
  UpgradeGroupsToRemove	= CreateAHero_Body
End

Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_CM01_CHBOD07
  TriggeredBy			= Upgrade_CM01_CHBOD07
  UpgradeGroupsToRemove	= CreateAHero_Body
End

Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_CM01_CHBOD08
  TriggeredBy			= Upgrade_CM01_CHBOD08
  UpgradeGroupsToRemove	= CreateAHero_Body
End

// Corrupted Man 2
Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_CM02_CHBOD01
  TriggeredBy			= Upgrade_CM02_CHBOD01
  UpgradeGroupsToRemove	= CreateAHero_Body
End

Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_CM02_CHBOD02
  TriggeredBy			= Upgrade_CM02_CHBOD02
  UpgradeGroupsToRemove	= CreateAHero_Body
End

Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_CM02_CHBOD03
  TriggeredBy			= Upgrade_CM02_CHBOD03
  UpgradeGroupsToRemove	= CreateAHero_Body
End

Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_CM02_CHBOD04
  TriggeredBy			= Upgrade_CM02_CHBOD04
  UpgradeGroupsToRemove	= CreateAHero_Body
End

Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_CM02_CHBOD05
  TriggeredBy			= Upgrade_CM02_CHBOD05
  UpgradeGroupsToRemove	= CreateAHero_Body
End

Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_CM02_CHBOD07
  TriggeredBy			= Upgrade_CM02_CHBOD07
  UpgradeGroupsToRemove	= CreateAHero_Body
End

Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_CM02_CHBOD08
  TriggeredBy			= Upgrade_CM02_CHBOD08
  UpgradeGroupsToRemove	= CreateAHero_Body
End

// Uruk Hai
Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_URUK_CHBOD01
  TriggeredBy			= Upgrade_URUK_CHBOD01
  UpgradeGroupsToRemove	= CreateAHero_Body
End

Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_URUK_CHBOD02
  TriggeredBy			= Upgrade_URUK_CHBOD02
  UpgradeGroupsToRemove	= CreateAHero_Body
End

Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_URUK_CHBOD03
  TriggeredBy			= Upgrade_URUK_CHBOD03
  UpgradeGroupsToRemove	= CreateAHero_Body
End

Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_URUK_CHBOD04
  TriggeredBy			= Upgrade_URUK_CHBOD04
  UpgradeGroupsToRemove	= CreateAHero_Body
End

// Elf Archer
Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_ELFA_CHBOD01
  TriggeredBy			= Upgrade_ELFA_CHBOD01
  UpgradeGroupsToRemove	= CreateAHero_Body
End

Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_ELFA_CHBOD02
  TriggeredBy			= Upgrade_ELFA_CHBOD02
  UpgradeGroupsToRemove	= CreateAHero_Body
End

Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_ELFA_CHBOD03
  TriggeredBy			= Upgrade_ELFA_CHBOD03
  UpgradeGroupsToRemove	= CreateAHero_Body
End

Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_ELFA_CHBOD04
  TriggeredBy			= Upgrade_ELFA_CHBOD04
  UpgradeGroupsToRemove	= CreateAHero_Body
End

// Female Elf Archer
Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_FEARCH_CHBOD01
  TriggeredBy			= Upgrade_FEARCH_CHBOD01
  UpgradeGroupsToRemove	= CreateAHero_Body
End

Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_FEARCH_CHBOD02
  TriggeredBy			= Upgrade_FEARCH_CHBOD02
  UpgradeGroupsToRemove	= CreateAHero_Body
End

Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_FEARCH_CHBOD03
  TriggeredBy			= Upgrade_FEARCH_CHBOD03
  UpgradeGroupsToRemove	= CreateAHero_Body
End

// Captain of Gondor
Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_CAPG_CHBOD01
  TriggeredBy			= Upgrade_CAPG_CHBOD01
  UpgradeGroupsToRemove	= CreateAHero_Body
End

Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_CAPG_CHBOD02
  TriggeredBy			= Upgrade_CAPG_CHBOD02
  UpgradeGroupsToRemove	= CreateAHero_Body
End

Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_CAPG_CHBOD03
  TriggeredBy			= Upgrade_CAPG_CHBOD03
  UpgradeGroupsToRemove	= CreateAHero_Body
End

Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_CAPG_CHBOD04
  TriggeredBy			= Upgrade_CAPG_CHBOD04
  UpgradeGroupsToRemove	= CreateAHero_Body
End

// Shield Maiden
Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_SHIM_CHBOD01
  TriggeredBy			= Upgrade_SHIM_CHBOD01
  UpgradeGroupsToRemove	= CreateAHero_Body
End

Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_SHIM_CHBOD02
  TriggeredBy			= Upgrade_SHIM_CHBOD02
  UpgradeGroupsToRemove	= CreateAHero_Body
End

Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_SHIM_CHBOD03
  TriggeredBy			= Upgrade_SHIM_CHBOD03
  UpgradeGroupsToRemove	= CreateAHero_Body
End

Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_SHIM_CHBOD04
  TriggeredBy			= Upgrade_SHIM_CHBOD04
  UpgradeGroupsToRemove	= CreateAHero_Body
End

Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_SHIM_CHBOD05
  TriggeredBy			= Upgrade_SHIM_CHBOD05
  UpgradeGroupsToRemove	= CreateAHero_Body
End

// Wizard
Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_WIZ_CHBOD01
  TriggeredBy			= Upgrade_WIZ_CHBOD01
  UpgradeGroupsToRemove	= CreateAHero_Body
End

Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_WIZ_CHBOD02
  TriggeredBy			= Upgrade_WIZ_CHBOD02
  UpgradeGroupsToRemove	= CreateAHero_Body
End

Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_WIZ_CHBOD03
  TriggeredBy			= Upgrade_WIZ_CHBOD03
  UpgradeGroupsToRemove	= CreateAHero_Body
End

// Orc Raider
Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_ORC_CHBOD01
  TriggeredBy			= Upgrade_ORC_CHBOD01
  UpgradeGroupsToRemove	= CreateAHero_Body
End

Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_ORC_CHBOD02
  TriggeredBy			= Upgrade_ORC_CHBOD02
  UpgradeGroupsToRemove	= CreateAHero_Body
End

Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_ORC_CHBOD03
  TriggeredBy			= Upgrade_ORC_CHBOD03
  UpgradeGroupsToRemove	= CreateAHero_Body
End

// TROLL
Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_TRLL_CHBOD01
  TriggeredBy			= Upgrade_TRLL_CHBOD01
  UpgradeGroupsToRemove	= CreateAHero_Body
End

Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_TRLL_CHBOD02
  TriggeredBy			= Upgrade_TRLL_CHBOD02
  UpgradeGroupsToRemove	= CreateAHero_Body
End

Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_TRLL_CHBOD03
  TriggeredBy			= Upgrade_TRLL_CHBOD03
  UpgradeGroupsToRemove	= CreateAHero_Body
End

Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_TRLL_CHBOD04
  TriggeredBy			= Upgrade_TRLL_CHBOD04
  UpgradeGroupsToRemove	= CreateAHero_Body
End

Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_TRLL_CHBOD05
  TriggeredBy			= Upgrade_TRLL_CHBOD05
  UpgradeGroupsToRemove	= CreateAHero_Body
End

Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_TRLL_CHBOD06
  TriggeredBy			= Upgrade_TRLL_CHBOD06
  UpgradeGroupsToRemove	= CreateAHero_Body
End

Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_TRLL_CHBOD07
  TriggeredBy			= Upgrade_TRLL_CHBOD07
  UpgradeGroupsToRemove	= CreateAHero_Body
End

Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_TRLL_CHBOD08
  TriggeredBy			= Upgrade_TRLL_CHBOD08
  UpgradeGroupsToRemove	= CreateAHero_Body
End

Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_TRLL_CHBOD09
  TriggeredBy			= Upgrade_TRLL_CHBOD09
  UpgradeGroupsToRemove	= CreateAHero_Body
End

// DWARF
Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_DWARF_CHBOD01
  TriggeredBy			= Upgrade_DWARF_CHBOD01
  UpgradeGroupsToRemove	= CreateAHero_Body
End

Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_DWARF_CHBOD02
  TriggeredBy			= Upgrade_DWARF_CHBOD02
  UpgradeGroupsToRemove	= CreateAHero_Body
End

Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_DWARF_CHBOD03
  TriggeredBy			= Upgrade_DWARF_CHBOD03
  UpgradeGroupsToRemove	= CreateAHero_Body
End

Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_DWARF_CHBOD04
  TriggeredBy			= Upgrade_DWARF_CHBOD04
  UpgradeGroupsToRemove	= CreateAHero_Body
End

Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_DWARF_CHBOD05
  TriggeredBy			= Upgrade_DWARF_CHBOD05
  UpgradeGroupsToRemove	= CreateAHero_Body
End

// DSAGE
Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_DSAGE_CHBOD01
  TriggeredBy			= Upgrade_DSAGE_CHBOD01
  UpgradeGroupsToRemove	= CreateAHero_Body
End

Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_DSAGE_CHBOD02
  TriggeredBy			= Upgrade_DSAGE_CHBOD02
  UpgradeGroupsToRemove	= CreateAHero_Body
End

Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_DSAGE_CHBOD03
  TriggeredBy			= Upgrade_DSAGE_CHBOD03
  UpgradeGroupsToRemove	= CreateAHero_Body
End

Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_DSAGE_CHBOD04
  TriggeredBy			= Upgrade_DSAGE_CHBOD04
  UpgradeGroupsToRemove	= CreateAHero_Body
End

Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_DSAGE_CHBOD05
  TriggeredBy			= Upgrade_DSAGE_CHBOD05
  UpgradeGroupsToRemove	= CreateAHero_Body
End
