Behavior = AISpecialPowerUpdate AthelasAI
	CommandButtonName = Command_CreateAHero_SpecialAbilityAthelas
	SpecialPowerAIType = AI_SPECIAL_POWER_SELFAOEHEALHEROS
End

Behavior = AISpecialPowerUpdate ElendilAI
	CommandButtonName = Command_CreateAHero_SpecialAbilityElendil
	SpecialPowerAIType = AI_SPECIAL_POWER_ELENDIL
End

Behavior = AISpecialPowerUpdate BladeMasterAI
	CommandButtonName = Command_CreateAHero_SpecialAbilityBladeMaster
	SpecialPowerAIType = AI_SPECIAL_POWER_BASIC_SELF_BUFF
End

Behavior = AISpecialPowerUpdate ShieldMaidenAI
	CommandButtonName = Command_CreateAHero_EowynShieldMaiden
	SpecialPowerAIType = AI_SPECIAL_POWER_BASIC_SELF_BUFF
End

Behavior = AISpecialPowerUpdate WordOfPowerAI
	CommandButtonName = Command_CreateAHero_SpecialAbilityWordOfPower
	SpecialPowerAIType = AI_SPECIAL_POWER_BASIC_SELF_BUFF
End

Behavior = AISpecialPowerUpdate ForcePushL1AI
	CommandButtonName = Command_CreateAHero_SpecialAbilityForcePush_Level1
	SpecialPowerAIType = AI_SPECIAL_POWER_GANDALF_WIZARD_BLAST
End

Behavior = AISpecialPowerUpdate ForcePushL2AI
	CommandButtonName = Command_CreateAHero_SpecialAbilityForcePush_Level2
	SpecialPowerAIType = AI_SPECIAL_POWER_GANDALF_WIZARD_BLAST
End

Behavior = AISpecialPowerUpdate ForcePushL3AI
	CommandButtonName = Command_CreateAHero_SpecialAbilityForcePush_Level3
	SpecialPowerAIType = AI_SPECIAL_POWER_GANDALF_WIZARD_BLAST
End

Behavior = AISpecialPowerUpdate ConvertEnemyL1AI
	CommandButtonName = Command_CreateAHero_SpecialAbilityConvertEnemy_L1
	SpecialPowerAIType = AI_SPECIAL_POWER_DOMINATE_ENEMY
End

Behavior = AISpecialPowerUpdate ConvertEnemyL2AI
	CommandButtonName = Command_CreateAHero_SpecialAbilityConvertEnemy_L2
	SpecialPowerAIType = AI_SPECIAL_POWER_DOMINATE_ENEMY
End

Behavior = AISpecialPowerUpdate CurseEnemyL1AI
	CommandButtonName = Command_CreateAHero_SpecialAbilityCurseEnemy_Level1
	SpecialPowerAIType = AI_SPECIAL_POWER_ENEMY_TYPE_KILLER_RANGED
End

Behavior = AISpecialPowerUpdate CurseEnemyL2AI
	CommandButtonName = Command_CreateAHero_SpecialAbilityCurseEnemy_Level2
	SpecialPowerAIType = AI_SPECIAL_POWER_ENEMY_TYPE_KILLER_RANGED
End

Behavior = AISpecialPowerUpdate CurseEnemyL3AI
	CommandButtonName = Command_CreateAHero_SpecialAbilityCurseEnemy_Level3
	SpecialPowerAIType = AI_SPECIAL_POWER_ENEMY_TYPE_KILLER_RANGED
End 

Behavior = AISpecialPowerUpdate FireballL1AI
	CommandButtonName = Command_CreateAHero_Fireball_Level1
	SpecialPowerAIType = AI_SPECIAL_POWER_ENEMY_TYPE_KILLER_RANGED
End

Behavior = AISpecialPowerUpdate FireballL2AI
	CommandButtonName = Command_CreateAHero_Fireball_Level2
	SpecialPowerAIType = AI_SPECIAL_POWER_ENEMY_TYPE_KILLER_RANGED
End

Behavior = AISpecialPowerUpdate FireballL3AI
	CommandButtonName = Command_CreateAHero_Fireball_Level3
	SpecialPowerAIType = AI_SPECIAL_POWER_ENEMY_TYPE_KILLER_RANGED
End 

Behavior = AISpecialPowerUpdate LightBlastL1AI
	CommandButtonName = Command_CreateAHero_LightBlast_L1
	SpecialPowerAIType = AI_SPECIAL_POWER_ENEMY_TYPE_KILLER_RANGED
End

Behavior = AISpecialPowerUpdate LightBlastL2AI
	CommandButtonName = Command_CreateAHero_LightBlast_L2
	SpecialPowerAIType = AI_SPECIAL_POWER_ENEMY_TYPE_KILLER_RANGED
End

Behavior = AISpecialPowerUpdate LightBlastL3AI
	CommandButtonName = Command_CreateAHero_LightBlast_L3
	SpecialPowerAIType = AI_SPECIAL_POWER_ENEMY_TYPE_KILLER_RANGED
End 

Behavior = AISpecialPowerUpdate SummonAlliesHotWL1AI
	CommandButtonName = Command_CreateAHero_HotW_SummonAllies_Level1
	SpecialPowerAIType = AI_SPECIAL_POWER_TARGETAOE_SUMMON
	SpecialPowerRadius = 30.0
End

Behavior = AISpecialPowerUpdate SummonAlliesHotWL2AI
	CommandButtonName = Command_CreateAHero_HotW_SummonAllies_Level2
	SpecialPowerAIType = AI_SPECIAL_POWER_TARGETAOE_SUMMON
	SpecialPowerRadius = 30.0
End

Behavior = AISpecialPowerUpdate SummonAlliesHotWL3AI
	CommandButtonName = Command_CreateAHero_HotW_SummonAllies_Level3
	SpecialPowerAIType = AI_SPECIAL_POWER_TARGETAOE_SUMMON
	SpecialPowerRadius = 30.0
End

Behavior = AISpecialPowerUpdate SummonAlliesHotWL4AI
	CommandButtonName = Command_CreateAHero_HotW_SummonAllies_Level4
	SpecialPowerAIType = AI_SPECIAL_POWER_TARGETAOE_SUMMON
	SpecialPowerRadius = 30.0
End

Behavior = AISpecialPowerUpdate SummonAlliesSoSL1AI
	CommandButtonName = Command_CreateAHero_SoS_SummonAllies_Level1
	SpecialPowerAIType = AI_SPECIAL_POWER_TARGETAOE_SUMMON
	SpecialPowerRadius = 30.0
End

Behavior = AISpecialPowerUpdate SummonAlliesSoSL2AI
	CommandButtonName = Command_CreateAHero_SoS_SummonAllies_Level2
	SpecialPowerAIType = AI_SPECIAL_POWER_TARGETAOE_SUMMON
	SpecialPowerRadius = 30.0
End

Behavior = AISpecialPowerUpdate SummonAlliesSoSL3AI
	CommandButtonName = Command_CreateAHero_SoS_SummonAllies_Level3
	SpecialPowerAIType = AI_SPECIAL_POWER_TARGETAOE_SUMMON
	SpecialPowerRadius = 30.0
End

Behavior = AISpecialPowerUpdate SummonAlliesSoSL4AI
	CommandButtonName = Command_CreateAHero_SoS_SummonAllies_Level4
	SpecialPowerAIType = AI_SPECIAL_POWER_TARGETAOE_SUMMON
	SpecialPowerRadius = 30.0
End

Behavior = AISpecialPowerUpdate AToggleWeaponAI
	CommandButtonName = Command_CreateAHero_A_ToggleWeapon
	SpecialPowerAIType = AI_SPECIAL_POWER_TOGGLE_MELEE_AND_RANGE
End

Behavior = AISpecialPowerUpdate CMToggleWeaponL1AI
	CommandButtonName = Command_CreateAHero_CM_ToggleWeapon
	SpecialPowerAIType = AI_SPECIAL_POWER_TOGGLE_MELEE_AND_RANGE
End

Behavior = AISpecialPowerUpdate CMToggleWeapoL2nAI
	CommandButtonName = Command_CreateAHero_CM_ToggleWeapon_Level2
	SpecialPowerAIType = AI_SPECIAL_POWER_TOGGLE_MELEE_AND_RANGE
End

Behavior = AISpecialPowerUpdate BallLightningL1AI
	CommandButtonName = Command_CreateAHero_BallLightning_L1
	SpecialPowerAIType = AI_SPECIAL_POWER_ENEMY_TYPE_KILLER_RANGED
End

Behavior = AISpecialPowerUpdate BallLightningL2AI
	CommandButtonName = Command_CreateAHero_BallLightning_L2
	SpecialPowerAIType = AI_SPECIAL_POWER_ENEMY_TYPE_KILLER_RANGED
End

Behavior = AISpecialPowerUpdate BallLightningL3AI
	CommandButtonName = Command_CreateAHero_BallLightning_L3
	SpecialPowerAIType = AI_SPECIAL_POWER_ENEMY_TYPE_KILLER_RANGED
End 

Behavior = AISpecialPowerUpdate InvulnerabilityL1AI
	CommandButtonName = Command_CreateAHero_Invulnerability_Level1
	SpecialPowerAIType = AI_SPECIAL_POWER_BASIC_SELF_BUFF
End

Behavior = AISpecialPowerUpdate InvulnerabilityL2AI
	CommandButtonName = Command_CreateAHero_Invulnerability_Level2
	SpecialPowerAIType = AI_SPECIAL_POWER_BASIC_SELF_BUFF
End

Behavior = AISpecialPowerUpdate InvulnerabilityL3AI
	CommandButtonName = Command_CreateAHero_Invulnerability_Level3
	SpecialPowerAIType = AI_SPECIAL_POWER_BASIC_SELF_BUFF
End

Behavior = AISpecialPowerUpdate CrippleStrikeRangedL1AI
	CommandButtonName = Command_CreateAHero_CrippleStrikeRanged_Level1
	SpecialPowerAIType = AI_SPECIAL_POWER_ENEMY_TYPE_KILLER_RANGED
End

Behavior = AISpecialPowerUpdate CrippleStrikeRangedL2AI
	CommandButtonName = Command_CreateAHero_CrippleStrikeRanged_Level2
	SpecialPowerAIType = AI_SPECIAL_POWER_ENEMY_TYPE_KILLER_RANGED
End

Behavior = AISpecialPowerUpdate CrippleStrikeRangedL3AI
	CommandButtonName = Command_CreateAHero_CrippleStrikeRanged_Level3
	SpecialPowerAIType = AI_SPECIAL_POWER_ENEMY_TYPE_KILLER_RANGED
End

Behavior = AISpecialPowerUpdate CrippleStrikeRangedL4AI
	CommandButtonName = Command_CreateAHero_CrippleStrikeRanged_Level4
	SpecialPowerAIType = AI_SPECIAL_POWER_ENEMY_TYPE_KILLER_RANGED
End

Behavior = AISpecialPowerUpdate CrippleStrikeMeleeHotWL1AI
	CommandButtonName = Command_CreateAHero_HotW_CrippleStrikeMelee_Level1
	SpecialPowerAIType = AI_SPECIAL_POWER_ENEMY_TYPE_KILLER
End

Behavior = AISpecialPowerUpdate CrippleStrikeMeleeHotWL2AI
	CommandButtonName = Command_CreateAHero_HotW_CrippleStrikeMelee_Level2
	SpecialPowerAIType = AI_SPECIAL_POWER_ENEMY_TYPE_KILLER
End

Behavior = AISpecialPowerUpdate CrippleStrikeMeleeHotWL3AI
	CommandButtonName = Command_CreateAHero_HotW_CrippleStrikeMelee_Level3
	SpecialPowerAIType = AI_SPECIAL_POWER_ENEMY_TYPE_KILLER
End

Behavior = AISpecialPowerUpdate CrippleStrikeMeleeHotWL4AI
	CommandButtonName = Command_CreateAHero_HotW_CrippleStrikeMelee_Level4
	SpecialPowerAIType = AI_SPECIAL_POWER_ENEMY_TYPE_KILLER
End

Behavior = AISpecialPowerUpdate CrippleStrikeMeleeSoSL1AI
	CommandButtonName = Command_CreateAHero_SoS_CrippleStrikeMelee_Level1
	SpecialPowerAIType = AI_SPECIAL_POWER_ENEMY_TYPE_KILLER
End

Behavior = AISpecialPowerUpdate CrippleStrikeMeleeSoSL2AI
	CommandButtonName = Command_CreateAHero_SoS_CrippleStrikeMelee_Level2
	SpecialPowerAIType = AI_SPECIAL_POWER_ENEMY_TYPE_KILLER
End

Behavior = AISpecialPowerUpdate CrippleStrikeMeleeSoSL3AI
	CommandButtonName = Command_CreateAHero_SoS_CrippleStrikeMelee_Level3
	SpecialPowerAIType = AI_SPECIAL_POWER_ENEMY_TYPE_KILLER
End

Behavior = AISpecialPowerUpdate CrippleStrikeMeleeSoSL4AI
	CommandButtonName = Command_CreateAHero_SoS_CrippleStrikeMelee_Level4
	SpecialPowerAIType = AI_SPECIAL_POWER_ENEMY_TYPE_KILLER
End

Behavior = AISpecialPowerUpdate ToggleMountedAI
	CommandButtonName = Command_CreateAHero_ToggleMounted
	SpecialPowerAIType = AI_SPECIAL_POWER_TOGGLE_MOUNTED
End

Behavior = AISpecialPowerUpdate TrainAlliesL1AI
	CommandButtonName = Command_CreateAHero_SpecialAbilityCreateAHeroTrainAllies_Level_1
	SpecialPowerAIType = AI_SPECIAL_POWER_GIVEXP_AOE
End

Behavior = AISpecialPowerUpdate TrainAlliesL2AI
	CommandButtonName = Command_CreateAHero_SpecialAbilityCreateAHeroTrainAllies_Level_2
	SpecialPowerAIType = AI_SPECIAL_POWER_GIVEXP_AOE
End

Behavior = AISpecialPowerUpdate TrainAlliesL3AI
	CommandButtonName = Command_CreateAHero_SpecialAbilityCreateAHeroTrainAllies_Level_3
	SpecialPowerAIType = AI_SPECIAL_POWER_GIVEXP_AOE
End

Behavior = AISpecialPowerUpdate WordOfPoultryL1AI
	CommandButtonName = Command_CreateAHero_WordOfPoultry_Level1
	SpecialPowerAIType = AI_SPECIAL_POWER_RANGED_AOE_ATTACK
End

Behavior = AISpecialPowerUpdate WordOfPoultryL2AI
	CommandButtonName = Command_CreateAHero_WordOfPoultry_Level2
	SpecialPowerAIType = AI_SPECIAL_POWER_RANGED_AOE_ATTACK
End

Behavior = AISpecialPowerUpdate ShieldCrushL1AI
	CommandButtonName = Command_CreateAHero_ShieldCrush_Level1
	SpecialPowerAIType = AI_SPECIAL_POWER_BASIC_SELF_BUFF
End

Behavior = AISpecialPowerUpdate ShieldCrushL3AI
	CommandButtonName = Command_CreateAHero_ShieldCrush_Level3
	SpecialPowerAIType = AI_SPECIAL_POWER_BASIC_SELF_BUFF
End

Behavior = AISpecialPowerUpdate StarlightAI
	CommandButtonName = Command_CreateAHero_Starlight
	SpecialPowerAIType = AI_SPECIAL_POWER_BASIC_SELF_BUFF
End

Behavior = AISpecialPowerUpdate ThrowSpearL1AI
	CommandButtonName = Command_CreateAHeroThrowSpear_Level1
	SpecialPowerAIType = AI_SPECIAL_POWER_ENEMY_TYPE_KILLER_RANGED
End

Behavior = AISpecialPowerUpdate ThrowSpearL2AI
	CommandButtonName = Command_CreateAHeroThrowSpear_Level2
	SpecialPowerAIType = AI_SPECIAL_POWER_ENEMY_TYPE_KILLER_RANGED
End

Behavior = AISpecialPowerUpdate ThrowSpearL3AI
	CommandButtonName = Command_CreateAHeroThrowSpear_Level3
	SpecialPowerAIType = AI_SPECIAL_POWER_ENEMY_TYPE_KILLER_RANGED
End

Behavior = AISpecialPowerUpdate ChargeAI
	CommandButtonName = Command_SpecialAbilityCreateAHeroHeroicCharge
	SpecialPowerAIType = AI_SPECIAL_POWER_CHARGE
End

Behavior = AISpecialPowerUpdate HowlOfRageL1AI
	CommandButtonName = Command_CreateAHero_HowlOfRage_Level1
	SpecialPowerAIType = AI_SPECIAL_POWER_BASIC_SELF_BUFF
End

Behavior = AISpecialPowerUpdate HowlOfRageL2AI
	CommandButtonName = Command_CreateAHero_HowlOfRage_Level2
	SpecialPowerAIType = AI_SPECIAL_POWER_BASIC_SELF_BUFF
End

Behavior = AISpecialPowerUpdate HowlOfRageL3AI
	CommandButtonName = Command_CreateAHero_HowlOfRage_Level3
	SpecialPowerAIType = AI_SPECIAL_POWER_BASIC_SELF_BUFF
End

Behavior = AISpecialPowerUpdate BerserkerRageL1AI
	CommandButtonName = Command_CreateAHero_BerserkerRage_Level1
	SpecialPowerAIType = AI_SPECIAL_POWER_BASIC_SELF_BUFF
End

Behavior = AISpecialPowerUpdate BerserkerRageL2AI
	CommandButtonName = Command_CreateAHero_BerserkerRage_Level2
	SpecialPowerAIType = AI_SPECIAL_POWER_BASIC_SELF_BUFF
End

Behavior = AISpecialPowerUpdate BerserkerRageL3AI
	CommandButtonName = Command_CreateAHero_BerserkerRage_Level3
	SpecialPowerAIType = AI_SPECIAL_POWER_BASIC_SELF_BUFF
End

Behavior = AISpecialPowerUpdate BerserkerRageL4AI
	CommandButtonName = Command_CreateAHero_BerserkerRage_Level4
	SpecialPowerAIType = AI_SPECIAL_POWER_BASIC_SELF_BUFF
End

Behavior = AISpecialPowerUpdate FirebombL1AI
	CommandButtonName = Command_CreateAHeroFireBomb_Level1
	SpecialPowerAIType = AI_SPECIAL_POWER_ENEMY_TYPE_KILLER_RANGED
End

Behavior = AISpecialPowerUpdate FirebombL2AI
	CommandButtonName = Command_CreateAHeroFireBomb_Level2
	SpecialPowerAIType = AI_SPECIAL_POWER_ENEMY_TYPE_KILLER_RANGED
End

Behavior = AISpecialPowerUpdate FirebombL3AI
	CommandButtonName = Command_CreateAHeroFireBomb_Level3
	SpecialPowerAIType = AI_SPECIAL_POWER_ENEMY_TYPE_KILLER_RANGED
End

Behavior = AISpecialPowerUpdate FirebombL4AI
	CommandButtonName = Command_CreateAHeroFireBomb_Level4
	SpecialPowerAIType = AI_SPECIAL_POWER_ENEMY_TYPE_KILLER_RANGED
End

Behavior = AISpecialPowerUpdate PoisonAttackL1AI
	CommandButtonName = Command_CreateAHeroPoisonAttack_Level1
	SpecialPowerAIType = AI_SPECIAL_POWER_BASIC_SELF_BUFF
End


Behavior = AISpecialPowerUpdate PoisonAttackL2AI
	CommandButtonName = Command_CreateAHeroPoisonAttack_Level2
	SpecialPowerAIType = AI_SPECIAL_POWER_BASIC_SELF_BUFF
End


Behavior = AISpecialPowerUpdate PoisonAttackL3AI
	CommandButtonName = Command_CreateAHeroPoisonAttack_Level3
	SpecialPowerAIType = AI_SPECIAL_POWER_BASIC_SELF_BUFF
End

Behavior = AISpecialPowerUpdate PoisonAttackL4AI
	CommandButtonName = Command_CreateAHeroPoisonAttack_Level4
	SpecialPowerAIType = AI_SPECIAL_POWER_BASIC_SELF_BUFF
End

Behavior = AISpecialPowerUpdate CoerceL1AI
	CommandButtonName = Command_CreateAHero_SpecialAbilityCoerce_Level1
	SpecialPowerAIType = AI_SPECIAL_POWER_DOMINATE_ENEMY
End

Behavior = AISpecialPowerUpdate CoerceL2AI
	CommandButtonName = Command_CreateAHero_SpecialAbilityCoerce_Level2
	SpecialPowerAIType = AI_SPECIAL_POWER_DOMINATE_ENEMY
End

Behavior = AISpecialPowerUpdate CoerceL3AI
	CommandButtonName = Command_CreateAHero_SpecialAbilityCoerce_Level3
	SpecialPowerAIType = AI_SPECIAL_POWER_DOMINATE_ENEMY
End

Behavior = AISpecialPowerUpdate AssassinL1AI
	CommandButtonName = Command_CreateAHeroAssassin_Level1
	SpecialPowerAIType = AI_SPECIAL_POWER_ENEMY_TYPE_KILLER
End

Behavior = AISpecialPowerUpdate AssassinL2AI
	CommandButtonName = Command_CreateAHeroAssassin_Level2
	SpecialPowerAIType = AI_SPECIAL_POWER_ENEMY_TYPE_KILLER
End

Behavior = AISpecialPowerUpdate AssassinL3AI
	CommandButtonName = Command_CreateAHeroAssassin_Level3
	SpecialPowerAIType = AI_SPECIAL_POWER_ENEMY_TYPE_KILLER
End

Behavior = AISpecialPowerUpdate AssassinL4AI
	CommandButtonName = Command_CreateAHeroAssassin_Level4
	SpecialPowerAIType = AI_SPECIAL_POWER_ENEMY_TYPE_KILLER
End

Behavior = AISpecialPowerUpdate RainOfArrowsL1AI
	CommandButtonName = Command_CreateAHero_RainOfArrows_Level1
	SpecialPowerAIType = AI_SPECIAL_POWER_RANGED_AOE_ATTACK
End

Behavior = AISpecialPowerUpdate RainOfArrowsL2AI
	CommandButtonName = Command_CreateAHero_RainOfArrows_Level2
	SpecialPowerAIType = AI_SPECIAL_POWER_RANGED_AOE_ATTACK
End

Behavior = AISpecialPowerUpdate RainOfArrowsL3AI
	CommandButtonName = Command_CreateAHero_RainOfArrows_Level3
	SpecialPowerAIType = AI_SPECIAL_POWER_RANGED_AOE_ATTACK
End

Behavior = AISpecialPowerUpdate HealingL1AI
	CommandButtonName = Command_CreateAHero_SpecialAbilityHealing_Level1
	SpecialPowerAIType = AI_SPECIAL_POWER_HEAL_AOE
End

Behavior = AISpecialPowerUpdate HealingL2AI
	CommandButtonName = Command_CreateAHero_SpecialAbilityHealing_Level2
	SpecialPowerAIType = AI_SPECIAL_POWER_HEAL_AOE
End

Behavior = AISpecialPowerUpdate ArrowBonusL1AI
	CommandButtonName = Command_CreateAHero_SpecialAbilityArrowBonus_Level1
	SpecialPowerAIType = AI_SPECIAL_POWER_BASIC_SELF_BUFF
End

Behavior = AISpecialPowerUpdate ArrowBonusL2AI
	CommandButtonName = Command_CreateAHero_SpecialAbilityArrowBonus_Level2
	SpecialPowerAIType = AI_SPECIAL_POWER_BASIC_SELF_BUFF
End

Behavior = AISpecialPowerUpdate ArrowBonusL3AI
	CommandButtonName = Command_CreateAHero_SpecialAbilityArrowBonus_Level3
	SpecialPowerAIType = AI_SPECIAL_POWER_BASIC_SELF_BUFF
End

Behavior = AISpecialPowerUpdate ArrowBonusL4AI
	CommandButtonName = Command_CreateAHero_SpecialAbilityArrowBonus_Level4
	SpecialPowerAIType = AI_SPECIAL_POWER_BASIC_SELF_BUFF
End

Behavior = AISpecialPowerUpdate SummonFamiliarL1AI
	CommandButtonName = Command_CreateAHero_SummonFamiliar_Level1
	SpecialPowerAIType = AI_SPECIAL_POWER_TARGETAOE_SUMMON
End

Behavior = AISpecialPowerUpdate SummonFamiliarL2AI
	CommandButtonName = Command_CreateAHero_SummonFamiliar_Level2
	SpecialPowerAIType = AI_SPECIAL_POWER_TARGETAOE_SUMMON
End

Behavior = AISpecialPowerUpdate SummonFamiliarL3AI
	CommandButtonName = Command_CreateAHero_SummonFamiliar_Level3
	SpecialPowerAIType = AI_SPECIAL_POWER_TARGETAOE_SUMMON
End

Behavior = AISpecialPowerUpdate SpawnTornadoL1AI
	CommandButtonName = Command_CreateAHero_SpawnTornado_Level1
	SpecialPowerAIType = AI_SPECIAL_POWER_TARGETAOE_SUMMON
End

Behavior = AISpecialPowerUpdate SpawnTornadoL2AI
	CommandButtonName = Command_CreateAHero_SpawnTornado_Level2
	SpecialPowerAIType = AI_SPECIAL_POWER_TARGETAOE_SUMMON
End

Behavior = AISpecialPowerUpdate SpawnTornadoL3AI
	CommandButtonName = Command_CreateAHero_SpawnTornado_Level3
	SpecialPowerAIType = AI_SPECIAL_POWER_TARGETAOE_SUMMON
End

Behavior = AISpecialPowerUpdate AxeThrowL1AI
	CommandButtonName = Command_CreateAHero_AxeThrow_Level1
	SpecialPowerAIType = AI_SPECIAL_POWER_ENEMY_TYPE_KILLER_RANGED
End

Behavior = AISpecialPowerUpdate AxeThrowL2AI
	CommandButtonName = Command_CreateAHero_AxeThrow_Level2
	SpecialPowerAIType = AI_SPECIAL_POWER_ENEMY_TYPE_KILLER_RANGED
End

Behavior = AISpecialPowerUpdate AxeThrowL3AI
	CommandButtonName = Command_CreateAHero_AxeThrow_Level3
	SpecialPowerAIType = AI_SPECIAL_POWER_ENEMY_TYPE_KILLER_RANGED
End

Behavior = AISpecialPowerUpdate EarthShakerL1AI
	CommandButtonName = Command_CreateAHero_EarthShaker_Level1
	SpecialPowerAIType = AI_SPECIAL_POWER_BASIC_SELF_BUFF
End

Behavior = AISpecialPowerUpdate EarthShakerL2AI
	CommandButtonName = Command_CreateAHero_EarthShaker_Level2
	SpecialPowerAIType = AI_SPECIAL_POWER_BASIC_SELF_BUFF
End

Behavior = AISpecialPowerUpdate EarthShakerL3AI
	CommandButtonName = Command_CreateAHero_EarthShaker_Level3
	SpecialPowerAIType = AI_SPECIAL_POWER_BASIC_SELF_BUFF
End

Behavior = AISpecialPowerUpdate LeapL1AI
	CommandButtonName = Command_CreateAHero_Leap_Level1
	SpecialPowerAIType = AI_SPECIAL_POWER_RANGED_AOE_ATTACK
	SpecialPowerRadius = 100
End

Behavior = AISpecialPowerUpdate LeapL2AI
	CommandButtonName = Command_CreateAHero_Leap_Level2
	SpecialPowerAIType = AI_SPECIAL_POWER_RANGED_AOE_ATTACK
	SpecialPowerRadius = 100
End

Behavior = AISpecialPowerUpdate TrollLeapL1AI
	CommandButtonName = Command_CreateAHero_TrollLeap_Level1
	SpecialPowerAIType = AI_SPECIAL_POWER_RANGED_AOE_ATTACK
	SpecialPowerRadius = 100
End

Behavior = AISpecialPowerUpdate TrollLeapL2AI
	CommandButtonName = Command_CreateAHero_TrollLeap_Level2
	SpecialPowerAIType = AI_SPECIAL_POWER_RANGED_AOE_ATTACK
	SpecialPowerRadius = 100
End

Behavior = AISpecialPowerUpdate ChargeL1AI
	CommandButtonName = Command_CreateAHero_Charge_Level1
	SpecialPowerAIType = AI_SPECIAL_POWER_CHARGE
End

Behavior = AISpecialPowerUpdate ChargeL2AI
	CommandButtonName = Command_CreateAHero_Charge_Level2
	SpecialPowerAIType = AI_SPECIAL_POWER_CHARGE
End

Behavior = AISpecialPowerUpdate ChargeL3AI
	CommandButtonName = Command_CreateAHero_Charge_Level3
	SpecialPowerAIType = AI_SPECIAL_POWER_CHARGE
End

Behavior = AISpecialPowerUpdate BombardL1AI
	CommandButtonName = Command_CreateAHero_Bombard_Level1
	SpecialPowerAIType = AI_SPECIAL_POWER_RANGED_AOE_ATTACK
End

Behavior = AISpecialPowerUpdate BombardL2AI
	CommandButtonName = Command_CreateAHero_Bombard_Level2
	SpecialPowerAIType = AI_SPECIAL_POWER_RANGED_AOE_ATTACK
End

Behavior = AISpecialPowerUpdate BombardL3AI
	CommandButtonName = Command_CreateAHero_Bombard_Level3
	SpecialPowerAIType = AI_SPECIAL_POWER_RANGED_AOE_ATTACK
End

Behavior = AISpecialPowerUpdate BattleRageL1AI
	CommandButtonName = Command_CreateAHero_BattleRage_Level1
	SpecialPowerAIType = AI_SPECIAL_POWER_BASIC_SELF_BUFF
End

Behavior = AISpecialPowerUpdate BattleRageL2AI
	CommandButtonName = Command_CreateAHero_BattleRage_Level2
	SpecialPowerAIType = AI_SPECIAL_POWER_BASIC_SELF_BUFF
End

Behavior = AISpecialPowerUpdate BattleRageL3AI
	CommandButtonName = Command_CreateAHero_BattleRage_Level3
	SpecialPowerAIType = AI_SPECIAL_POWER_BASIC_SELF_BUFF
End

Behavior = AISpecialPowerUpdate BattleRageL4AI
	CommandButtonName = Command_CreateAHero_BattleRage_Level4
	SpecialPowerAIType = AI_SPECIAL_POWER_BASIC_SELF_BUFF
End







