
//-------------------------------------------------------------------------------------------------
// Starting units (heroes and armies) for each faction
//-------------------------------------------------------------------------------------------------


//-------------------------------------------------------------------------------------------------
// Men of the West starting armies
//-------------------------------------------------------------------------------------------------

LivingWorldPlayerArmy
	Name = TheodenPlayerArmy
	DisplayNameTag = LWA:MenHeroArmy
	ArmyEntry
		ThingTemplate = RohanTheoden
		Quantity = 1
	End
End

LivingWorldPlayerArmy
	Name = AragornPlayerArmy
	DisplayNameTag = LWA:MenHeroArmy	
	ArmyEntry
		ThingTemplate = GondorAragornMP
		Quantity = 1
	End
End

LivingWorldPlayerArmy
	Name = BoromirPlayerArmy
	DisplayNameTag = LWA:MenHeroArmy	
	ArmyEntry
		ThingTemplate = GondorBoromir
		Quantity = 1
	End
End

LivingWorldPlayerArmy
	Name = MenOfTheWest_StartingArmy
	DisplayNameTag = LWA:MenOfTheWestGarrison
	ArmyEntry
		ThingTemplate = GondorArcherHorde
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = GondorFighterHorde
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = GondorKnightHorde
		Quantity = 1
	End
End


//-------------------------------------------------------------------------------------------------
// Elven starting armies
//-------------------------------------------------------------------------------------------------

LivingWorldPlayerArmy
	Name = ThranduilPlayerArmy
	DisplayNameTag = LWA:ElvesHeroArmy
	ArmyEntry
		ThingTemplate = ElvenThranduil
		Quantity = 1
	End
End

LivingWorldPlayerArmy
	Name = ElrondPlayerArmy
	DisplayNameTag = LWA:ElvesHeroArmy	
	ArmyEntry
		ThingTemplate = ElvenElrond
		Quantity = 1
	End
End

LivingWorldPlayerArmy
	Name = HaldirPlayerArmy
	DisplayNameTag = LWA:ElvesHeroArmy	
	ArmyEntry
		ThingTemplate = ElvenHaldir
		Quantity = 1
	End
End

LivingWorldPlayerArmy
	Name = Elven_StartingArmy
	DisplayNameTag = LWA:ElvesGarrison
	ArmyEntry
		ThingTemplate = ElvenLorienWarriorHorde
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = ElvenLorienArcherHorde
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = ElvenRivendellLancerHorde
		Quantity = 1
	End
End


//-------------------------------------------------------------------------------------------------
// Dwarven starting armies
//-------------------------------------------------------------------------------------------------

LivingWorldPlayerArmy
	Name = GimliPlayerArmy
	DisplayNameTag = LWA:DwarvesHeroArmy
	ArmyEntry
		ThingTemplate = DwarvenGimli
		Quantity = 1
	End
End

LivingWorldPlayerArmy
	Name = GloinPlayerArmy
	DisplayNameTag = LWA:DwarvesHeroArmy	
	ArmyEntry
		ThingTemplate = DwarvenGloin
		Quantity = 1
	End
End

LivingWorldPlayerArmy
	Name = DainPlayerArmy
	DisplayNameTag = LWA:DwarvesHeroArmy	
	ArmyEntry
		ThingTemplate = DwarvenDain
		Quantity = 1
	End
End

LivingWorldPlayerArmy
	Name = Dwarven_StartingArmy
	DisplayNameTag = LWA:DwarvesGarrison
	ArmyEntry
		ThingTemplate = DwarvenGuardianHorde
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = DwarvenAxeThrowerHorde
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = DwarvenBattleWagon
		Quantity = 1
	End
End


//-------------------------------------------------------------------------------------------------
// Corrupted Wild starting armies
//-------------------------------------------------------------------------------------------------

LivingWorldPlayerArmy
	Name = ShelobPlayerArmy
	DisplayNameTag = LWA:WildHeroArmy
	ArmyEntry
		ThingTemplate = WildShelob
		Quantity = 1
	End
End

LivingWorldPlayerArmy
	Name = DrogothPlayerArmy
	DisplayNameTag = LWA:WildHeroArmy
	ArmyEntry
		ThingTemplate = Drogoth
		Quantity = 1
	End
End	

LivingWorldPlayerArmy
	Name = GorkilPlayerArmy
	DisplayNameTag = LWA:WildHeroArmy
	ArmyEntry
		ThingTemplate = WildGoblinKing
		Quantity = 1
	End	
End

LivingWorldPlayerArmy
	Name = CorruptedWild_StartingArmy
	DisplayNameTag = LWA:WildGarrison
	ArmyEntry
		ThingTemplate = GoblinFighterHorde
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = GoblinArcherHorde
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = GoblinCaveTroll
		Quantity = 1
	End
End	


//-------------------------------------------------------------------------------------------------
// Mordor starting armies
//-------------------------------------------------------------------------------------------------

LivingWorldPlayerArmy
	Name = WitchKingPlayerArmy
	DisplayNameTag = LWA:MordorHeroArmy
	ArmyEntry
		ThingTemplate = MordorWitchKingOnFellBeast
		Quantity = 1
	End
End

LivingWorldPlayerArmy
	Name = FellBeast1PlayerArmy
	DisplayNameTag = LWA:MordorHeroArmy
	ArmyEntry
		ThingTemplate = MordorFellBeast
		Quantity = 1
	End
End	

LivingWorldPlayerArmy
	Name = FellBeast2PlayerArmy
	DisplayNameTag = LWA:MordorHeroArmy
	ArmyEntry
		ThingTemplate = MordorFellBeast
		Quantity = 1
	End	
End

LivingWorldPlayerArmy
	Name = Mordor_StartingArmy
	DisplayNameTag = LWA:MordorGarrison
	ArmyEntry
		ThingTemplate = MordorFighterHorde
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = MordorArcherHorde
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = MordorMountainTroll
		Quantity = 1
	End
End	


//-------------------------------------------------------------------------------------------------
// Isengard starting armies
//-------------------------------------------------------------------------------------------------

LivingWorldPlayerArmy
	Name = SarumanPlayerArmy
	DisplayNameTag = LWA:IsengardHeroArmy
	ArmyEntry
		ThingTemplate = IsengardSaruman
		Quantity = 1
	End
End

LivingWorldPlayerArmy
	Name = LurtzPlayerArmy
	DisplayNameTag = LWA:IsengardHeroArmy
	ArmyEntry
		ThingTemplate = IsengardLurtz
		Quantity = 1
	End
End	

LivingWorldPlayerArmy
	Name = SharkuPlayerArmy
	DisplayNameTag = LWA:IsengardHeroArmy
	ArmyEntry
		ThingTemplate = IsengardSharku
		Quantity = 1
	End	
End

LivingWorldPlayerArmy
	Name = Isengard_StartingArmy
	DisplayNameTag = LWA:IsengardGarrison
	ArmyEntry
		ThingTemplate = IsengardFighterHorde
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = IsengardUrukCrossbowHorde
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = IsengardWargRiderHorde
		Quantity = 1
	End
End	


//-------------------------------------------------------------------------------------------------
// Custom armies for the tutorial
//-------------------------------------------------------------------------------------------------

LivingWorldPlayerArmy
	Name = TheodenPlayerArmy_Tutorial
	DisplayNameTag = LWA:MenHeroArmy
	ArmyEntry
		ThingTemplate = RohanTheoden
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = RohanRohirrimHorde
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = RohanRohirrimHorde
		Quantity = 1
	End
End

LivingWorldPlayerArmy
	Name = AragornPlayerArmy_Tutorial		// Aragorn needs to beat the FellBeast1, so make sure this army is stronger
	DisplayNameTag = LWA:MenHeroArmy	
	ArmyEntry
		ThingTemplate = GondorAragornMP
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = GondorRangerHorde
		Quantity = 2
	End
	ArmyEntry
		ThingTemplate = RohanRohirrimHorde
		Quantity = 2
	End
End

LivingWorldPlayerArmy
	Name = BoromirPlayerArmy_Tutorial		// Boromir needs to lose to the WitchKing, so make sure this army is weaker
	DisplayNameTag = LWA:MenHeroArmy	
	ArmyEntry
		ThingTemplate = GondorBoromir
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = GondorFighterHorde
		Quantity = 1
	End
End

LivingWorldPlayerArmy
	Name = MenOfTheWest_Garrison1_Tutorial
	DisplayNameTag = LWA:MenOfTheWestGarrison
	ArmyEntry
		ThingTemplate = GondorArcherHorde
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = GondorTowerShieldGuardHorde
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = GondorTowerShieldGuardHorde
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = GondorKnightHorde
		Quantity = 1
	End
End

LivingWorldPlayerArmy
	Name = WitchKingPlayerArmy_Tutorial
	DisplayNameTag = LWA:MordorHeroArmy
	ArmyEntry
		ThingTemplate = MordorWitchKingOnFellBeast
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = MordorFighterHorde
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = MordorArcherHorde
		Quantity = 2
	End
	ArmyEntry
		ThingTemplate = MordorAttackTroll
		Quantity = 2
	End
End

LivingWorldPlayerArmy
	Name = FellBeast1PlayerArmy_Tutorial
	DisplayNameTag = LWA:MordorHeroArmy
	ArmyEntry
		ThingTemplate = MordorFellBeast
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = MordorArcherHorde
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = MordorFighterHorde
		Quantity = 2
	End
End	

LivingWorldPlayerArmy
	Name = FellBeast2PlayerArmy_Tutorial
	DisplayNameTag = LWA:MordorHeroArmy
	ArmyEntry
		ThingTemplate = MordorFellBeast
		Quantity = 1
	End	
	ArmyEntry
		ThingTemplate = MordorAttackTroll
		Quantity = 2
	End
	ArmyEntry
		ThingTemplate = MordorCorsairsOfUmbarHorde
		Quantity = 2
	End
End

LivingWorldPlayerArmy
	Name = Mordor_Garrison1_Tutorial
	DisplayNameTag = LWA:MordorGarrison
	ArmyEntry
		ThingTemplate = MordorFighterHorde
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = MordorArcherHorde
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = MordorMountainTroll
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = MordorDrummerTroll
		Quantity = 1
	End
End	
