//-------------------------------------------------------------------------------------------------
// The hacked cities continue...
//-------------------------------------------------------------------------------------------------


LivingWorldPlayerArmy
	Name = Shire_PlayerArmy
	DisplayNameTag = LWA:Shire
End

LivingWorldPlayerArmy
	Name = Bree_PlayerArmy
	DisplayNameTag = LWA:Bree
End

LivingWorldPlayerArmy
	Name = Rivendell_PlayerArmy
	DisplayNameTag = LWA:Rivendell
End

LivingWorldPlayerArmy
	Name = Moria_PlayerArmy
	DisplayNameTag = LWA:Moria
End

LivingWorldPlayerArmy
	Name = Lothlorien_PlayerArmy
	DisplayNameTag = LWA:Lothlorien
End

LivingWorldPlayerArmy
	Name = Edoras_PlayerArmy
	DisplayNameTag = LWA:Edoras
End

LivingWorldPlayerArmy
	Name = Isengard_PlayerArmy
	DisplayNameTag = LWA:Isengard_City
End

LivingWorldPlayerArmy
	Name = HelmsDeep_PlayerArmy
	DisplayNameTag = LWA:HelmsDeep
End

LivingWorldPlayerArmy
	Name = Osgiliath_PlayerArmy
	DisplayNameTag = LWA:Osgiliath
End

LivingWorldPlayerArmy
	Name = MinasTirith_PlayerArmy
	DisplayNameTag = LWA:MinasTirith
End

LivingWorldPlayerArmy
	Name = CirithUngol_PlayerArmy
	DisplayNameTag = LWA:CirithUngol
End

LivingWorldPlayerArmy
	Name = BlackGate_PlayerArmy
	DisplayNameTag = LWA:BlackGate
End

LivingWorldPlayerArmy
	Name = BaradDur_PlayerArmy
	DisplayNameTag = LWA:BaradDur
End

LivingWorldPlayerArmy
	Name = MtDoom_PlayerArmy
	DisplayNameTag = LWA:MtDoom
End

LivingWorldPlayerArmy
	Name = Fangorn_PlayerArmy
	DisplayNameTag = LWA:Fangorn
End

LivingWorldPlayerArmy
	Name = DeadMarshes_PlayerArmy
	DisplayNameTag = LWA:DeadMarshes
End