//-------------------------------------------------------------------------------------------------
//	Default settings for RTS battle in WOTR
//-------------------------------------------------------------------------------------------------


SecondsPerReinforcement	= 300		; In RTS: After the first army, each reinforcement army comes into battle 15 minutes later
StartingCashRTS		= 6000
StartingCashRTSWithFort	= 1500
InitialRevivalCostMultiplier = 2.0
InitialRevivalTimeMultiplier = 1.0

#include "LivingWorldVictoryTypes.inc"
