//-------------------------------------------------------------------------------------------------
// This file is meant to be included by almost all Campaign INIs
// when those files need to create the (hacked) cities 
//-------------------------------------------------------------------------------------------------


SpawnArmy
	; Name = Shire_Mouseover
	PlayerArmy = Shire_PlayerArmy
	Icon = City_Large
	PalantirMovie = Palantir_513
	Position = X:-850 Y:1300
	IsCity = Yes
End
SpawnArmy
	; Name = Bree_Mouseover
	PlayerArmy = Bree_PlayerArmy
	Icon = City_Small
	PalantirMovie = Palantir_514
	Position = X:-370 Y:1480
	IsCity = Yes
End
SpawnArmy
	; Name = Rivendell_Mouseover
	PlayerArmy = Rivendell_PlayerArmy
	Icon = City_Small
	PalantirMovie = Palantir_512
	Position = X:285 Y:1650
	IsCity = Yes
End
SpawnArmy
	; Name = Moria_Mouseover
	PlayerArmy = Moria_PlayerArmy
	Icon = City_Large
	PalantirMovie = Palantir_149
	Position = X:370 Y:1140
	IsCity = Yes
End
SpawnArmy
	; Name = Lothlorien_Mouseover
	PlayerArmy = Lothlorien_PlayerArmy
	Icon = City_Small
	PalantirMovie = Palantir_161
	Position = X:690 Y:1000
	IsCity = Yes
End
SpawnArmy
	; Name = Edoras_Mouseover
	PlayerArmy = Edoras_PlayerArmy
	Icon = City_Small
	PalantirMovie = Palantir_502
	Position = X:422 Y:258
	IsCity = Yes
End
SpawnArmy
	; Name = Isengard_Mouseover
	PlayerArmy = Isengard_PlayerArmy
	Icon = City_Large
	PalantirMovie = Palantir_158
	Position = X:160 Y:600
	IsCity = Yes
End
SpawnArmy
	; Name = HelmsDeep_Mouseover
	PlayerArmy = HelmsDeep_PlayerArmy
	Icon = City_Large
	PalantirMovie = Palantir_504
	Position = X:148 Y:360
	IsCity = Yes
End
SpawnArmy
	; Name = Osgiliath_Mouseover
	PlayerArmy = Osgiliath_PlayerArmy
	Icon = City_Large
	PalantirMovie = Palantir_152
	Position = X:1476 Y:-44
	IsCity = Yes
End
SpawnArmy
	; Name = MinasTirith_Mouseover
	PlayerArmy = MinasTirith_PlayerArmy
	Icon = City_Large
	PalantirMovie = Palantir_211
	Position = X:1250 Y:-30
	IsCity = Yes
End
SpawnArmy
	; Name = CirithUngol_Mouseover
	PlayerArmy = CirithUngol_PlayerArmy
	Icon = City_Small
	PalantirMovie = Palantir_515
	Position = X:1795 Y:30
	IsCity = Yes
End
SpawnArmy
	; Name = BlackGate_Mouseover
	PlayerArmy = BlackGate_PlayerArmy
	Icon = City_Large
	PalantirMovie = Palantir_155
	Position = X:1730 Y:440
	IsCity = Yes
End
SpawnArmy
	; Name = Fangorn_Mouseover
	PlayerArmy = Fangorn_PlayerArmy
	Icon = City_Large
	PalantirMovie = Palantir_604
	Position = X:390 Y:700
	IsCity = Yes
End
SpawnArmy
	; Name = DeadMarshes_Mouseover
	PlayerArmy = DeadMarshes_PlayerArmy
	Icon = City_Large
	PalantirMovie = Palantir_605
	Position = X:1475 Y:540
	IsCity = Yes
End
SpawnArmy
	; Name = MtDoom_Mouseover
	PlayerArmy = MtDoom_PlayerArmy
	Icon = City_Large
	PalantirMovie = Palantir_603
	Position = X:2100 Y:140
	IsCity = Yes
End
SpawnArmy
	; Name = BaradDur_Mouseover
	PlayerArmy = BaradDur_PlayerArmy
	Icon = City_Small
	PalantirMovie = Palantir_516
	Position = X:2460 Y:160
	IsCity = Yes
End
